Lustre: lustre/target/update_records.c File Reference
lustre/target/update_records.c File Reference
#include <lu_target.h>
#include <lustre_obdo.h>
#include <lustre_update.h>
#include <obd.h>
#include <obd_class.h>
#include "tgt_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_CLASS
#define UPDATE_RECORDS_BUFFER_SIZE 8192
#define UPDATE_PARAMS_BUFFER_SIZE 8192
Functions
void update_records_dump (const struct update_records *records, unsigned int mask, bool dump_updates)
Dump update record.
static unsigned int update_records_param_pack (struct update_params *params, const void *new_param, size_t new_param_size, unsigned int *param_count)
Pack parameters to update records.
static int update_records_update_pack (const struct lu_env *env, const struct lu_fid *fid, enum update_type op_type, struct update_ops *ops, unsigned int *op_count, size_t *max_op_size, struct update_params *params, unsigned int *param_count, size_t *max_param_size, unsigned int param_bufs_count, const void **param_bufs, size_t *param_sizes)
Pack update to update records.
static size_t update_records_update_size (__u32 param_count, size_t *sizes)
Calculate update_records size.
size_t update_records_create_size (const struct lu_env *env, const struct lu_fid *fid, const struct lu_attr *attr, const struct dt_allocation_hint *hint, struct dt_object_format *dof)
Calculate create update size.
int update_records_create_pack (const struct lu_env *env, struct update_ops *ops, unsigned int *op_count, size_t *max_ops_size, struct update_params *params, unsigned int *param_count, size_t *max_param_size, const struct lu_fid *fid, const struct lu_attr *attr, const struct dt_allocation_hint *hint, struct dt_object_format *dof)
Pack create update.
size_t update_records_attr_set_size (const struct lu_env *env, const struct lu_fid *fid, const struct lu_attr *attr)
Calculate attr set update size.
int update_records_attr_set_pack (const struct lu_env *env, struct update_ops *ops, unsigned int *op_count, size_t *max_ops_size, struct update_params *params, unsigned int *param_count, size_t *max_param_size, const struct lu_fid *fid, const struct lu_attr *attr)
Pack attr set update.
size_t update_records_ref_add_size (const struct lu_env *env, const struct lu_fid *fid)
Calculate ref add update size.
int update_records_ref_add_pack (const struct lu_env *env, struct update_ops *ops, unsigned int *op_count, size_t *max_ops_size, struct update_params *params, unsigned int *param_count, size_t *max_param_size, const struct lu_fid *fid)
Pack ref add update.
int update_records_noop_pack (const struct lu_env *env, struct update_ops *ops, unsigned int *op_count, size_t *max_ops_size, struct update_params *params, unsigned int *param_count, size_t *max_param_size, const struct lu_fid *fid)
Pack noop update.
size_t update_records_ref_del_size (const struct lu_env *env, const struct lu_fid *fid)
Calculate ref del update size.
int update_records_ref_del_pack (const struct lu_env *env, struct update_ops *ops, unsigned int *op_count, size_t *max_ops_size, struct update_params *params, unsigned int *param_count, size_t *max_param_size, const struct lu_fid *fid)
Pack ref del update.
size_t update_records_object_destroy_size (const struct lu_env *env, const struct lu_fid *fid)
Calculate object destroy update size.
int update_records_object_destroy_pack (const struct lu_env *env, struct update_ops *ops, unsigned int *op_count, size_t *max_ops_size, struct update_params *params, unsigned int *param_count, size_t *max_param_size, const struct lu_fid *fid)
Pack object destroy update.
size_t update_records_index_insert_size (const struct lu_env *env, const struct lu_fid *fid, const struct dt_rec *rec, const struct dt_key *key)
Calculate index insert update size.
int update_records_index_insert_pack (const struct lu_env *env, struct update_ops *ops, unsigned int *op_count, size_t *max_ops_size, struct update_params *params, unsigned int *param_count, size_t *max_param_size, const struct lu_fid *fid, const struct dt_rec *rec, const struct dt_key *key)
Pack index insert update.
size_t update_records_index_delete_size (const struct lu_env *env, const struct lu_fid *fid, const struct dt_key *key)
Calculate index delete update size.
int update_records_index_delete_pack (const struct lu_env *env, struct update_ops *ops, unsigned int *op_count, size_t *max_ops_size, struct update_params *params, unsigned int *param_count, size_t *max_param_size, const struct lu_fid *fid, const struct dt_key *key)
Pack index delete update.
size_t update_records_xattr_set_size (const struct lu_env *env, const struct lu_fid *fid, const struct lu_buf *buf, const char *name, __u32 flag)
Calculate xattr set size.
int update_records_xattr_set_pack (const struct lu_env *env, struct update_ops *ops, unsigned int *op_count, size_t *max_ops_size, struct update_params *params, unsigned int *param_count, size_t *max_param_size, const struct lu_fid *fid, const struct lu_buf *buf, const char *name, __u32 flag)
Pack xattr set update.
size_t update_records_xattr_del_size (const struct lu_env *env, const struct lu_fid *fid, const char *name)
Calculate xattr delete update size.
int update_records_xattr_del_pack (const struct lu_env *env, struct update_ops *ops, unsigned int *op_count, size_t *max_ops_size, struct update_params *params, unsigned int *param_count, size_t *max_param_size, const struct lu_fid *fid, const char *name)
Pack xattr delete update.
size_t update_records_write_size (const struct lu_env *env, const struct lu_fid *fid, const struct lu_buf *buf, __u64 pos)
Calculate write update size.
int update_records_write_pack (const struct lu_env *env, struct update_ops *ops, unsigned int *op_count, size_t *max_ops_size, struct update_params *params, unsigned int *param_count, size_t *max_param_size, const struct lu_fid *fid, const struct lu_buf *buf, __u64 pos)
Pack write update.
size_t update_records_punch_size (const struct lu_env *env, const struct lu_fid *fid, __u64 start, __u64 end)
Calculate size of punch update.
int update_records_punch_pack (const struct lu_env *env, struct update_ops *ops, unsigned int *op_count, size_t *max_ops_size, struct update_params *params, unsigned int *param_count, size_t *max_param_size, const struct lu_fid *fid, __u64 start, __u64 end)
Pack punch.
static int tur_update_records_create (struct thandle_update_records *tur)
Create update records in thandle_update_records.
int tur_update_records_extend (struct thandle_update_records *tur, size_t new_size)
Extend update records.
int tur_update_extend (struct thandle_update_records *tur, size_t new_op_size, size_t new_param_size)
Extend update records.
static int tur_update_params_create (struct thandle_update_records *tur)
Create update params in thandle_update_records.
int tur_update_params_extend (struct thandle_update_records *tur, size_t new_size)
Extend update params.
int check_and_prepare_update_record (const struct lu_env *env, struct thandle_update_records *tur)
Check and prepare whether it needs to record update.
static void update_key_fini (const struct lu_context *ctx, struct lu_context_key *key, void *data)
LU_KEY_INIT (update, struct update_thread_info)
LU_CONTEXT_KEY_DEFINE (update, LCT_MD_THREAD|LCT_MG_THREAD|LCT_DT_THREAD|LCT_TX_HANDLE|LCT_LOCAL)
LU_KEY_INIT_GENERIC (update)
void update_info_init (void)
void update_info_fini (void)
Define Documentation
#define DEBUG_SUBSYSTEM S_CLASS
Definition at line 41 of file update_records.c.
#define UPDATE_PARAMS_BUFFER_SIZE 8192
Definition at line 52 of file update_records.c.
Referenced by tur_update_extend(), and tur_update_params_create().
#define UPDATE_RECORDS_BUFFER_SIZE 8192
Definition at line 51 of file update_records.c.
Referenced by tur_update_extend(), and tur_update_records_create().
Function Documentation
int check_and_prepare_update_record (const struct lu_env * env, struct thandle_update_records * tur)
Check and prepare whether it needs to record update.
Checks if the transaction needs to record updates, and if it does, then initialize the update record buffer in the transaction.
Parameters:
[in] env execution environment
[in] th transaction handle
Return values:
0 if updates recording succeeds.
negative errno if updates recording fails.
Definition at line 1161 of file update_records.c.
References LLOG_MIN_CHUNK_SIZE, llog_rec_hdr::lrh_len, lur, llog_update_record::lur_hdr, llog_update_record::lur_update_rec, RETURN, thandle_update_records::tur_update_param_count, thandle_update_records::tur_update_params, tur_update_params_create(), thandle_update_records::tur_update_records, tur_update_records_create(), update_records::ur_batchid, update_records::ur_flags, update_records::ur_master_transno, update_records::ur_param_count, and update_records::ur_update_count.
Referenced by prepare_multiple_node_trans().
LU_CONTEXT_KEY_DEFINE (update , LCT_MD_THREAD|LCT_MG_THREAD|LCT_DT_THREAD|LCT_TX_HANDLE| LCT_LOCAL)
LU_KEY_INIT (update , struct update_thread_info)
LU_KEY_INIT_GENERIC (update)
int tur_update_extend (struct thandle_update_records * tur, size_t new_op_size, size_t new_param_size)
Extend update records.
Extend update records in thandle to make sure it is able to hold the update with certain update_op and params size.
Parameters:
[in] tur thandle_update_records to be extend
[in] new_op_size update_op size of the update record
[in] new_param_size params size of the update record
Return values:
0 if the update_records is being extended.
negative errno if the update_records is not being extended.
Definition at line 1054 of file update_records.c.
References ENTRY, llog_update_record_size(), RETURN, thandle_update_records::tur_update_param_count, thandle_update_records::tur_update_params, thandle_update_records::tur_update_params_buf_size, tur_update_params_extend(), thandle_update_records::tur_update_records, thandle_update_records::tur_update_records_buf_size, tur_update_records_extend(), UPDATE_PARAMS_BUFFER_SIZE, update_params_size(), and UPDATE_RECORDS_BUFFER_SIZE.
static int tur_update_params_create (struct thandle_update_records * tur) [static]
Create update params in thandle_update_records.
Allocate update_params for thandle_update_records, the initial size will be 4KB.
Parameters:
[in] tur thandle_update_records where update_params will be allocated
Return values:
0 if allocation succeeds.
negative errno if allocation fails.
Definition at line 1103 of file update_records.c.
References OBD_ALLOC_LARGE, thandle_update_records::tur_update_params, thandle_update_records::tur_update_params_buf_size, and UPDATE_PARAMS_BUFFER_SIZE.
Referenced by check_and_prepare_update_record().
int tur_update_params_extend (struct thandle_update_records * tur, size_t new_size)
Extend update params.
Extend update_params to the new size in thandle_update_records.
Parameters:
[in] tur thandle_update_records where update_params will be extended.
Return values:
0 if extension succeeds.
negative errno if extension fails.
Definition at line 1126 of file update_records.c.
References OBD_ALLOC_LARGE, OBD_FREE_LARGE, thandle_update_records::tur_update_params, and thandle_update_records::tur_update_params_buf_size.
Referenced by tur_update_extend().
static int tur_update_records_create (struct thandle_update_records * tur) [static]
Create update records in thandle_update_records.
Allocate update_records for thandle_update_records, the initial size will be 4KB.
Parameters:
[in] tur thandle_update_records where update_records will be allocated
Return values:
0 if allocation succeeds.
negative errno if allocation fails.
Definition at line 991 of file update_records.c.
References OBD_ALLOC_LARGE, thandle_update_records::tur_update_records, thandle_update_records::tur_update_records_buf_size, and UPDATE_RECORDS_BUFFER_SIZE.
Referenced by check_and_prepare_update_record().
int tur_update_records_extend (struct thandle_update_records * tur, size_t new_size)
Extend update records.
Extend update_records to the new size in thandle_update_records.
Parameters:
[in] tur thandle_update_records where update_records will be extended.
Return values:
0 if extension succeeds.
negative errno if extension fails.
Definition at line 1017 of file update_records.c.
References OBD_ALLOC_LARGE, OBD_FREE_LARGE, thandle_update_records::tur_update_records, and thandle_update_records::tur_update_records_buf_size.
Referenced by prepare_writing_updates(), and tur_update_extend().
void update_info_fini (void)
Definition at line 1232 of file update_records.c.
References lu_context_key_degister(), and update_thread_key.
Referenced by tgt_mod_exit().
void update_info_init (void)
Definition at line 1226 of file update_records.c.
References lu_context_key_register(), and update_thread_key.
Referenced by tgt_mod_init().
static void update_key_fini (const struct lu_context * ctx, struct lu_context_key * key, void * data) [static]
Definition at line 1192 of file update_records.c.
References OBD_FREE, OBD_FREE_LARGE, OBD_FREE_PTR, thandle_exec_args::ta_alloc_args, thandle_exec_args::ta_args, thandle_update_records::tur_update_params, thandle_update_records::tur_update_params_buf_size, thandle_update_records::tur_update_records, thandle_update_records::tur_update_records_buf_size, update_thread_info::uti_tea, and update_thread_info::uti_tur.
int update_records_attr_set_pack (const struct lu_env * env, struct update_ops * ops, unsigned int * op_count, size_t * max_ops_size, struct update_params * params, unsigned int * param_count, size_t * max_param_size, const struct lu_fid * fid, const struct lu_attr * attr)
Pack attr set update.
Pack attr_set update into update records.
Parameters:
[in] env execution environment
[in] ops ur_ops in update records
in|out] op_count pointer to the count of ops
in|out] max_op_size maximum size of the update
[in] params ur_params in update records
in|out] param_count pointer to the count of params
in|out] max_param_size maximum size of the parameter
[in] fid FID of the object to set attr
[in] attr attribute of attr set
Return values:
0 if packing succeeds.
negative errno if packing fails.
Definition at line 410 of file update_records.c.
References lu_attr::la_valid, lustre_set_wire_obdo(), obdo::o_valid, obdo_from_la(), OUT_ATTR_SET, size, update_env_info(), update_records_update_pack(), and update_thread_info::uti_obdo.
size_t update_records_attr_set_size (const struct lu_env * env, const struct lu_fid * fid, const struct lu_attr * attr)
Calculate attr set update size.
Parameters:
[in] env execution environment
[in] ops ur_ops in update records
[in] fid FID of the object to set attr
[in] attr attribute of attr set
Return values:
size of attr set update.
Definition at line 382 of file update_records.c.
References size, and update_records_update_size().
int update_records_create_pack (const struct lu_env * env, struct update_ops * ops, unsigned int * op_count, size_t * max_ops_size, struct update_params * params, unsigned int * param_count, size_t * max_param_size, const struct lu_fid * fid, const struct lu_attr * attr, const struct dt_allocation_hint * hint, struct dt_object_format * dof)
Pack create update.
Pack create update into update records.
Parameters:
[in] env execution environment
[in] ops ur_ops in update records
in|out] op_count pointer to the count of ops
in|out] max_op_size maximum size of the update
[in] params ur_params in update records
in|out] param_count pointer to the count of params
in|out] max_param_size maximum size of the parameter
[in] fid FID of the object to be created
[in] attr attribute of the object to be created
[in] hint creation hint
[in] dof creation format information
Return values:
0 if packing succeeds.
negative errno if packing fails.
Definition at line 327 of file update_records.c.
References dt_allocation_hint::dah_parent, dt_object::do_lu, fid_cpu_to_le(), lu_attr::la_valid, lu_object_fid(), lustre_set_wire_obdo(), obdo::o_valid, obdo_from_la(), OUT_CREATE, update_env_info(), update_records_update_pack(), and update_thread_info::uti_obdo.
size_t update_records_create_size (const struct lu_env * env, const struct lu_fid * fid, const struct lu_attr * attr, const struct dt_allocation_hint * hint, struct dt_object_format * dof)
Calculate create update size.
Parameters:
[in] env execution environment
[in] ops ur_ops in update records
[in] fid FID of the object to be created
[in] attr attribute of the object to be created
[in] hint creation hint
[in] dof creation format information
Return values:
size of create update.
Definition at line 284 of file update_records.c.
References dt_allocation_hint::dah_parent, and update_records_update_size().
void update_records_dump (const struct update_records * records, unsigned int mask, bool dump_updates)
Dump update record.
Dump all of updates in the update_records, mostly for debugging purpose.
Parameters:
[in] records update records to be dumpped
[in] mask debug level mask
[in] dump_params if dump all of updates the updates.
Definition at line 63 of file update_records.c.
References CDEBUG, DFID, LPU64, object_update_param::oup_len, PFID, update_ops::uops_op, update_op_next_op(), update_op_str(), update_params_get_param(), update_records_get_params(), update_records::ur_batchid, update_records::ur_flags, update_records::ur_master_transno, update_records::ur_ops, update_records::ur_param_count, and update_records::ur_update_count.
Referenced by distribute_txn_replay_handle(), dtrq_append_updates(), dtrq_list_dump(), prepare_writing_updates(), and sub_updates_write().
int update_records_index_delete_pack (const struct lu_env * env, struct update_ops * ops, unsigned int * op_count, size_t * max_ops_size, struct update_params * params, unsigned int * param_count, size_t * max_param_size, const struct lu_fid * fid, const struct dt_key * key)
Pack index delete update.
Pack index delete update into update records.
Parameters:
[in] env execution environment
[in] ops ur_ops in update records
in|out] op_count pointer to the count of ops
in|out] max_op_size maximum size of the update
[in] params ur_params in update records
in|ount] param_count pointer to the count of params
in|out] max_param_size maximum size of the parameter
[in] fid FID of the object to delete index
[in] key key of deletion
Return values:
0 if packing succeeds.
negative errno if packing fails.
Definition at line 716 of file update_records.c.
References OUT_INDEX_DELETE, size, and update_records_update_pack().
size_t update_records_index_delete_size (const struct lu_env * env, const struct lu_fid * fid, const struct dt_key * key)
Calculate index delete update size.
Parameters:
[in] env execution environment
[in] fid FID of the object to delete index
[in] key key of deletion
Return values:
the size of index delete update
Definition at line 688 of file update_records.c.
References size, and update_records_update_size().
int update_records_index_insert_pack (const struct lu_env * env, struct update_ops * ops, unsigned int * op_count, size_t * max_ops_size, struct update_params * params, unsigned int * param_count, size_t * max_param_size, const struct lu_fid * fid, const struct dt_rec * rec, const struct dt_key * key)
Pack index insert update.
Pack index insert update into update records.
Parameters:
[in] env execution environment
[in] ops ur_ops in update records
[in] op_count pointer to the count of ops
in|out] max_op_size maximum size of the update
[in] params ur_params in update records
[in] param_count pointer to the count of params
in|out] max_param_size maximum size of the parameter
[in] fid FID of the object to insert index
[in] rec record of insertion
[in] key key of insertion
Return values:
0 if packing succeeds.
negative errno if packing fails.
Definition at line 649 of file update_records.c.
References cpu_to_le32, fid_cpu_to_le(), OUT_INDEX_INSERT, dt_insert_rec::rec_fid, dt_insert_rec::rec_type, and update_records_update_pack().
size_t update_records_index_insert_size (const struct lu_env * env, const struct lu_fid * fid, const struct dt_rec * rec, const struct dt_key * key)
Calculate index insert update size.
Parameters:
[in] env execution environment
[in] fid FID of the object to insert index
[in] rec record of insertion
[in] key key of insertion
Return values:
the size of index insert update.
Definition at line 618 of file update_records.c.
References update_records_index_insert_size(), and update_records_update_size().
Referenced by update_records_index_insert_size().
int update_records_noop_pack (const struct lu_env * env, struct update_ops * ops, unsigned int * op_count, size_t * max_ops_size, struct update_params * params, unsigned int * param_count, size_t * max_param_size, const struct lu_fid * fid)
Pack noop update.
Pack no op update into update records. Note: no op means the update does not need do anything, which is only used in test case to verify large size record.
Parameters:
[in] env execution environment
[in] ops ur_ops in update records
in|out] op_count pointer to the count of ops
in|out] max_op_size maximum size of the update
[in] params ur_params in update records
in|out] param_count pointer to the count of params
in|out] max_param_size maximum size of the parameter
[in] fid FID of the object to add reference
Return values:
0 if packing succeeds.
negative errno if packing fails.
Definition at line 499 of file update_records.c.
References OUT_NOOP, and update_records_update_pack().
int update_records_object_destroy_pack (const struct lu_env * env, struct update_ops * ops, unsigned int * op_count, size_t * max_ops_size, struct update_params * params, unsigned int * param_count, size_t * max_param_size, const struct lu_fid * fid)
Pack object destroy update.
Pack object destroy update into update records.
Parameters:
[in] env execution environment
[in] ops ur_ops in update records
in|out] op_count pointer to the count of ops
in|out] max_op_size maximum size of the update
[in] params ur_params in update records
in|out] param_count pointer to the count of params
in|out] max_param_size maximum size of the parameter
[in] fid FID of the object to delete reference
Return values:
0 if packing succeeds.
negative errno if packing fails.
Definition at line 593 of file update_records.c.
References OUT_DESTROY, and update_records_update_pack().
size_t update_records_object_destroy_size (const struct lu_env * env, const struct lu_fid * fid)
Calculate object destroy update size.
Parameters:
[in] env execution environment
[in] fid FID of the object to delete reference
Return values:
size of object destroy update.
Definition at line 569 of file update_records.c.
References update_records_update_size().
static unsigned int update_records_param_pack (struct update_params * params, const void * new_param, size_t new_param_size, unsigned int * param_count) [static]
Pack parameters to update records.
Find and insert parameter to update records, if the parameter already exists in params, then just return the offset of this parameter, otherwise insert the parameter and return its offset
Parameters:
[in] params update params in which to insert parameter
[in] new_param parameters to be inserted.
[in] new_param_size the size of new_param
Return values:
index inside params if parameter insertion succeeds.
negative errno if it fails.
Definition at line 128 of file update_records.c.
References object_update_param::oup_buf, object_update_param::oup_len, update_params_get_param(), and update_params_size().
Referenced by update_records_update_pack().
int update_records_punch_pack (const struct lu_env * env, struct update_ops * ops, unsigned int * op_count, size_t * max_ops_size, struct update_params * params, unsigned int * param_count, size_t * max_param_size, const struct lu_fid * fid, __u64 start, __u64 end)
Pack punch.
Pack punch update into update records.
Parameters:
[in] env execution environment
[in] ops ur_ops in update records
in|out] op_count pointer to the count of ops
in|out] max_op_size maximum size of the update
[in] params ur_params in update records
in|out] param_count pointer to the count of params
in|out] max_param_size maximum size of the parameter
[in] fid FID of the object to write into
[in] start start offset of punch
[in] end end offet of punch
Return values:
0 if packing succeeds.
negative errno if packing fails.
Definition at line 958 of file update_records.c.
References cpu_to_le64, OUT_PUNCH, and update_records_update_pack().
size_t update_records_punch_size (const struct lu_env * env, const struct lu_fid * fid, __u64 start, __u64 end)
Calculate size of punch update.
Parameters:
[in] env execution environment
[in] fid FID of the object to write into
[in] start start offset of punch
[in] end end offet of punch
Return values:
size of update punch.
Definition at line 929 of file update_records.c.
References update_records_update_size().
int update_records_ref_add_pack (const struct lu_env * env, struct update_ops * ops, unsigned int * op_count, size_t * max_ops_size, struct update_params * params, unsigned int * param_count, size_t * max_param_size, const struct lu_fid * fid)
Pack ref add update.
Pack ref add update into update records.
Parameters:
[in] env execution environment
[in] ops ur_ops in update records
in|out] op_count pointer to the count of ops
in|out] max_op_size maximum size of the update
[in] params ur_params in update records
in|out] param_count pointer to the count of params
in|out] max_param_size maximum size of the parameter
[in] fid FID of the object to add reference
Return values:
0 if packing succeeds.
negative errno if packing fails.
Definition at line 465 of file update_records.c.
References OUT_REF_ADD, and update_records_update_pack().
size_t update_records_ref_add_size (const struct lu_env * env, const struct lu_fid * fid)
Calculate ref add update size.
Parameters:
[in] env execution environment
[in] fid FID of the object to add reference
Return values:
size of ref_add udpate.
Definition at line 441 of file update_records.c.
References update_records_update_size().
int update_records_ref_del_pack (const struct lu_env * env, struct update_ops * ops, unsigned int * op_count, size_t * max_ops_size, struct update_params * params, unsigned int * param_count, size_t * max_param_size, const struct lu_fid * fid)
Pack ref del update.
Pack ref del update into update records.
Parameters:
[in] env execution environment
[in] ops ur_ops in update records
in|out] op_count pointer to the count of ops
in|out] max_op_size maximum size of the update
[in] params ur_params in update records
[in] param_count pointer to the count of params
in|out] max_param_size maximum size of the parameter
[in] fid FID of the object to delete reference
Return values:
0 if packing succeeds.
negative errno if packing fails.
Definition at line 546 of file update_records.c.
References OUT_REF_DEL, and update_records_update_pack().
size_t update_records_ref_del_size (const struct lu_env * env, const struct lu_fid * fid)
Calculate ref del update size.
Parameters:
[in] env execution environment
[in] fid FID of the object to delete reference
Return values:
size of ref_del update.
Definition at line 522 of file update_records.c.
References update_records_update_size().
static int update_records_update_pack (const struct lu_env * env, const struct lu_fid * fid, enum update_type op_type, struct update_ops * ops, unsigned int * op_count, size_t * max_op_size, struct update_params * params, unsigned int * param_count, size_t * max_param_size, unsigned int param_bufs_count, const void ** param_bufs, size_t * param_sizes) [static]
Pack update to update records.
Pack the update and its parameters to the update records. First it will insert parameters, get the offset of these parameter, then fill the update with these offset. If insertion exceed the maximum size of current update records, it will return -E2BIG here, and the caller might extend the update_record size
See also:
lod_updates_pack.
Parameters:
[in] env execution environment
[in] fid FID of the update.
[in] op_type operation type of the update
[in] ops ur_ops in update records
in|out] op_count pointer to the count of ops
in|out] max_op_size maximum size of the update
[in] params ur_params in update records
in|out] param_count pointer to the count of params
in|out] max_param_size maximum size of the parameter
[in] param_bufs buffers of parameters
[in] params_buf_count the count of the parameter buffers
[in] param_size sizes of parameters
Return values:
0 if packing succeeds
negative errno if packing fails
Definition at line 184 of file update_records.c.
References CDEBUG, cfs_size_round(), D_INFO, DFID, PFID, unlikely, update_op::uop_fid, update_op::uop_param_count, update_op::uop_params_off, update_op::uop_type, update_op_size(), update_op_str(), update_ops_get_op(), and update_records_param_pack().
Referenced by update_records_attr_set_pack(), update_records_create_pack(), update_records_index_delete_pack(), update_records_index_insert_pack(), update_records_noop_pack(), update_records_object_destroy_pack(), update_records_punch_pack(), update_records_ref_add_pack(), update_records_ref_del_pack(), update_records_write_pack(), update_records_xattr_del_pack(), and update_records_xattr_set_pack().
static size_t update_records_update_size (__u32 param_count, size_t * sizes) [static]
Calculate update_records size.
Calculate update_records size by param_count and param_sizes array.
Parameters:
[in] param_count the count of parameters
[in] sizes the size array of these parameters
Return values:
the size of this update
Definition at line 257 of file update_records.c.
References cfs_size_round(), size, and update_op_size().
Referenced by update_records_attr_set_size(), update_records_create_size(), update_records_index_delete_size(), update_records_index_insert_size(), update_records_object_destroy_size(), update_records_punch_size(), update_records_ref_add_size(), update_records_ref_del_size(), update_records_write_size(), update_records_xattr_del_size(), and update_records_xattr_set_size().
int update_records_write_pack (const struct lu_env * env, struct update_ops * ops, unsigned int * op_count, size_t * max_ops_size, struct update_params * params, unsigned int * param_count, size_t * max_param_size, const struct lu_fid * fid, const struct lu_buf * buf, __u64 pos)
Pack write update.
Pack write update into update records.
Parameters:
[in] env execution environment
[in] ops ur_ops in update records
in|out] op_count pointer to the count of ops
in|out] max_op_size maximum size of the update
[in] params ur_params in update records
in|out] param_count pointer to the count of params
in|out] max_param_size maximum size of the parameter
[in] fid FID of the object to write into
[in] buf buffer to write which includes an embedded size field
[in] pos offet in the object to start writing at
Return values:
0 if packing succeeds.
negative errno if packing fails.
Definition at line 896 of file update_records.c.
References cpu_to_le64, lu_buf::lb_buf, lu_buf::lb_len, OUT_WRITE, update_records_update_pack(), and update_records_write_pack().
Referenced by update_records_write_pack().
size_t update_records_write_size (const struct lu_env * env, const struct lu_fid * fid, const struct lu_buf * buf, __u64 pos)
Calculate write update size.
Parameters:
[in] env execution environment
[in] fid FID of the object to write into
[in] buf buffer to write which includes an embedded size field
[in] pos offet in the object to start writing at
Return values:
size of write udpate.
Definition at line 866 of file update_records.c.
References lu_buf::lb_len, update_records_update_size(), and update_records_write_size().
Referenced by update_records_write_size().
int update_records_xattr_del_pack (const struct lu_env * env, struct update_ops * ops, unsigned int * op_count, size_t * max_ops_size, struct update_params * params, unsigned int * param_count, size_t * max_param_size, const struct lu_fid * fid, const char * name)
Pack xattr delete update.
Pack xattr delete update into update records.
Parameters:
[in] env execution environment
[in] ops ur_ops in update records
in|out] op_count pointer to the count of ops
in|out] max_op_size maximum size of the update
[in] params ur_params in update records
in|out] param_count pointer to the count of params
in|out] max_param_size maximum size of the parameter
[in] fid FID of the object to delete xattr
[in] name name of the xattr
Return values:
0 if packing succeeds.
negative errno if packing fails.
Definition at line 837 of file update_records.c.
References OUT_XATTR_DEL, size, and update_records_update_pack().
size_t update_records_xattr_del_size (const struct lu_env * env, const struct lu_fid * fid, const char * name)
Calculate xattr delete update size.
Parameters:
[in] env execution environment
[in] fid FID of the object to delete xattr
[in] name name of the xattr
Return values:
size of xattr delet updatee.
Definition at line 809 of file update_records.c.
References size, and update_records_update_size().
int update_records_xattr_set_pack (const struct lu_env * env, struct update_ops * ops, unsigned int * op_count, size_t * max_ops_size, struct update_params * params, unsigned int * param_count, size_t * max_param_size, const struct lu_fid * fid, const struct lu_buf * buf, const char * name, __u32 flag)
Pack xattr set update.
Pack xattr set update into update records.
Parameters:
[in] env execution environment
[in] ops ur_ops in update records
in|out] op_count pointer to the count of ops
in|out] max_op_size maximum size of the update
[in] params ur_params in update records
in|out] param_count pointer to the count of params
in|out] max_param_size maximum size of the parameter
[in] fid FID of the object to set xattr
[in] buf xattr to be set
[in] name name of the xattr
[in] flag flag for setting xattr
Return values:
0 if packing succeeds.
negative errno if packing fails.
Definition at line 777 of file update_records.c.
References cpu_to_le32, lu_buf::lb_buf, lu_buf::lb_len, OUT_XATTR_SET, update_records_update_pack(), and update_records_xattr_set_pack().
Referenced by update_records_xattr_set_pack().
size_t update_records_xattr_set_size (const struct lu_env * env, const struct lu_fid * fid, const struct lu_buf * buf, const char * name, __u32 flag)
Calculate xattr set size.
Parameters:
[in] env execution environment
[in] fid FID of the object to set xattr
[in] buf xattr to be set
[in] name name of the xattr
[in] flag flag for setting xattr
Return values:
size of xattr set update.
Definition at line 746 of file update_records.c.
References lu_buf::lb_len, update_records_update_size(), and update_records_xattr_set_size().
Referenced by update_records_xattr_set_size().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.