Lustre: lustre/utils/wiretest.c File Reference
lustre/utils/wiretest.c File Reference
#include <errno.h>
#include <limits.h>
#include <stdio.h>
#include <string.h>
#include <lustre/lustre_idl.h>
#include <lustre/lustre_lfsck_user.h>
#include <lustre_disk.h>
Defines
#define LASSERT(cond) if (!(cond)) { printf("failed " #cond "\n"); ret = 1; }
#define LASSERTF(cond, fmt,...) if (!(cond)) { printf("failed '" #cond "'" fmt, ## __VA_ARGS__);ret = 1;}
Functions
void lustre_assert_wire_constants (void)
int main ()
Variables
int ret
Define Documentation
#define LASSERT (cond) if (!(cond)) { printf("failed " #cond "\n"); ret = 1; }
Definition at line 48 of file wiretest.c.
#define LASSERTF (cond, fmt, ...) if (!(cond)) { printf("failed '" #cond "'" fmt, ## __VA_ARGS__);ret = 1;}
Definition at line 49 of file wiretest.c.
Function Documentation
void lustre_assert_wire_constants (void)
Definition at line 64 of file wiretest.c.
References CAPA_HMAC_KEY_MAX_LEN, CAPA_HMAC_MAX_LEN, CFS_RMTACL_PERM, CFS_RMTOWN_PERM, CFS_SETGID_PERM, CFS_SETGRP_PERM, CFS_SETUID_PERM, CHANGELOG_REC, CHANGELOG_USER_REC, CLASSERT, DEAD_HANDLE_MAGIC, DISP_ENQ_COMPLETE, DISP_ENQ_CREATE_REF, DISP_ENQ_OPEN_REF, DISP_IT_EXECD, DISP_LOOKUP_EXECD, DISP_LOOKUP_NEG, DISP_LOOKUP_POS, DISP_OPEN_CREATE, DISP_OPEN_LOCK, DISP_OPEN_OPEN, DLM_INTENT_IT_OFF, DLM_INTENT_REC_OFF, DLM_LOCKREPLY_OFF, DLM_LOCKREQ_OFF, DLM_REPLY_REC_OFF, DLM_REQ_REC_OFF, end, FID_OID_DOT_LUSTRE, FID_OID_DOT_LUSTRE_OBF, FID_OID_SPECIAL_BFL, FID_SEQ_DOT_LUSTRE, FID_SEQ_ECHO, FID_SEQ_IDIF, FID_SEQ_IDIF_MAX, FID_SEQ_IGIF, FID_SEQ_IGIF_MAX, FID_SEQ_LAYOUT_RBTREE, FID_SEQ_LLOG, FID_SEQ_LOCAL_FILE, FID_SEQ_LOV_DEFAULT, FID_SEQ_NORMAL, FID_SEQ_OST_MDT0, FID_SEQ_QUOTA, FID_SEQ_QUOTA_GLB, FID_SEQ_ROOT, FID_SEQ_RSVD, FID_SEQ_SPECIAL, FID_SEQ_START, FID_SEQ_UNUSED_END, FID_SEQ_UNUSED_START, FID_SEQ_UPDATE_LOG, FID_SEQ_UPDATE_LOG_DIR, FIEMAP_EXTENT_NET, FIEMAP_EXTENT_NO_DIRECT, FIEMAP_FLAG_DEVICE_ORDER, FLD_FIRST_OPC, FLD_LAST_OPC, FLD_QUERY, FLD_READ, HP_FLAG_COMPLETED, HP_FLAG_RETRY, HSM_FORCE_ACTION, HSM_GHOST_COPY, IDX_INFO_MAGIC, II_FL_NOHASH, II_FL_NONUNQ, II_FL_VARKEY, II_FL_VARREC, IOOBJ_MAX_BRW_BITS, IT_CREAT, IT_EXEC, IT_GETATTR, IT_GETXATTR, IT_LAYOUT, IT_LOOKUP, IT_OPEN, IT_PIN, IT_QUOTA_CONN, IT_QUOTA_DQACQ, IT_READDIR, IT_SETXATTR, IT_TRUNC, IT_UNLINK, LADVISE_MAGIC, LASSERTF, LAYOUT_INTENT_ACCESS, LAYOUT_INTENT_GLIMPSE, LAYOUT_INTENT_READ, LAYOUT_INTENT_RELEASE, LAYOUT_INTENT_RESTORE, LAYOUT_INTENT_TRUNC, LAYOUT_INTENT_WRITE, LCK_COS, LCK_CR, LCK_CW, LCK_EX, LCK_GROUP, LCK_MAXMODE, LCK_MINMODE, LCK_MODE_NUM, LCK_NL, LCK_PR, LCK_PW, LDF_COLLIDE, LDF_EMPTY, LDLM_BL_CALLBACK, LDLM_CANCEL, LDLM_CONVERT, LDLM_CP_CALLBACK, LDLM_ENQUEUE, LDLM_EXTENT, LDLM_FLOCK, LDLM_GL_CALLBACK, LDLM_IBITS, LDLM_LAST_OPC, LDLM_MAX_TYPE, LDLM_PLAIN, LDLM_SET_INFO, LE_CONDITIONAL_DESTROY, LE_FID_ACCESSED, LE_LASTID_REBUILDING, LE_LASTID_REBUILT, LE_PAIRS_VERIFY, LE_PEER_EXIT, LE_PHASE1_DONE, LE_PHASE2_DONE, LE_QUERY, LE_SET_LMV_MASTER, LE_SET_LMV_SLAVE, LE_SKIP_NLINK, LE_SKIP_NLINK_DECLARE, LE_START, LE_STOP, LEF_FROM_OST, LEF_QUERY_ALL, LEF_RECHECK_NAME_HASH, LEF_SET_LMV_ALL, LEF_SET_LMV_HASH, LEF_TO_OST, LFSCK_FIRST_OPC, LFSCK_LAST_OPC, LFSCK_NOTIFY, LFSCK_QUERY, LFSCK_TYPE_LAYOUT, LFSCK_TYPE_NAMESPACE, LFSCK_TYPE_SCRUB, LINK_EA_MAGIC, LIP_HDR_SIZE, LIP_MAGIC, LLOG_AGENT_ORIG_CTXT, LLOG_CATINFO, LLOG_CHANGELOG_ORIG_CTXT, LLOG_CHANGELOG_REPL_CTXT, LLOG_CHANGELOG_USER_ORIG_CTXT, LLOG_CONFIG_ORIG_CTXT, LLOG_CONFIG_REPL_CTXT, LLOG_FIRST_OPC, LLOG_GEN_REC, LLOG_HDR_MAGIC, LLOG_LAST_OPC, LLOG_LOGID_MAGIC, LLOG_MAX_CTXTS, LLOG_MDS_OST_ORIG_CTXT, LLOG_MDS_OST_REPL_CTXT, LLOG_ORIGIN_CONNECT, LLOG_ORIGIN_HANDLE_CLOSE, LLOG_ORIGIN_HANDLE_CREATE, LLOG_ORIGIN_HANDLE_DESTROY, LLOG_ORIGIN_HANDLE_NEXT_BLOCK, LLOG_ORIGIN_HANDLE_PREV_BLOCK, LLOG_ORIGIN_HANDLE_READ_HEADER, LLOG_ORIGIN_HANDLE_WRITE_REC, LLOG_SIZE_ORIG_CTXT, LLOG_SIZE_REPL_CTXT, LLOG_TEST_ORIG_CTXT, LLOG_TEST_REPL_CTXT, LLOG_UPDATELOG_ORIG_CTXT, LLOG_UPDATELOG_REPL_CTXT, LMAC_FID_ON_OST, LMAC_HSM, LMAC_NOT_IN_OI, LMAI_AGENT, LMAI_ORPHAN, LMAI_RELEASED, LMAI_REMOTE_PARENT, LMAI_STRIPED, LMV_HASH_FLAG_BAD_TYPE, LMV_HASH_FLAG_LOST_LMV, LMV_HASH_FLAG_MIGRATION, LMV_HASH_TYPE_MASK, LMV_MAGIC_STRIPE, LMV_MAGIC_V1, LOV_DESC_MAGIC, LOV_MAGIC_V1, LOV_MAGIC_V3, LOV_MAXPOOLNAME, LOV_PATTERN_CMOBD, LOV_PATTERN_FIRST, LOV_PATTERN_RAID0, LOV_PATTERN_RAID1, LQUOTA_FL_EDQUOT, LQUOTA_RES_DT, LQUOTA_RES_MD, LQUOTA_TYPE_GRP, LQUOTA_TYPE_USR, LU_PAGE_SIZE, LU_SEQ_RANGE_MDT, LU_SEQ_RANGE_OST, LUDA_64BITHASH, LUDA_FID, LUDA_TYPE, LUSTRE_APPEND_FL, LUSTRE_DIRECTIO_FL, LUSTRE_DIRSYNC_FL, LUSTRE_DLM_VERSION, LUSTRE_FID_INIT_OID, LUSTRE_IMMUTABLE_FL, LUSTRE_INDEX_FL, LUSTRE_INLINE_DATA_FL, LUSTRE_JOBID_SIZE, LUSTRE_LOG_VERSION, LUSTRE_MDS_VERSION, LUSTRE_MGS_VERSION, LUSTRE_MSG_MAGIC_V2, LUSTRE_MSG_MAGIC_V2_SWABBED, LUSTRE_NOATIME_FL, LUSTRE_NODUMP_FL, LUSTRE_OBD_VERSION, LUSTRE_ORPHAN_FL, LUSTRE_OST_VERSION, LUSTRE_RES_ID_HSH_OFF, LUSTRE_RES_ID_QUOTA_SEQ_OFF, LUSTRE_RES_ID_QUOTA_VER_OID_OFF, LUSTRE_RES_ID_SEQ_OFF, LUSTRE_RES_ID_VER_OID_OFF, LUSTRE_SYNC_FL, LUSTRE_TOPDIR_FL, LUSTRE_VERSION_MASK, MDS_ATTR_ATIME, MDS_ATTR_ATIME_SET, MDS_ATTR_ATTR_FLAG, MDS_ATTR_BLOCKS, MDS_ATTR_CTIME, MDS_ATTR_CTIME_SET, MDS_ATTR_FORCE, MDS_ATTR_FROM_OPEN, MDS_ATTR_GID, MDS_ATTR_KILL_SGID, MDS_ATTR_KILL_SUID, MDS_ATTR_MODE, MDS_ATTR_MTIME, MDS_ATTR_MTIME_SET, MDS_ATTR_SIZE, MDS_ATTR_UID, MDS_CLOSE, MDS_CONNECT, MDS_DIR_END_OFF, MDS_DISCONNECT, MDS_DONE_WRITING, MDS_FIRST_OPC, MDS_FMODE_CLOSED, MDS_FMODE_EXEC, MDS_GET_INFO, MDS_GET_ROOT, MDS_GETATTR, MDS_GETATTR_NAME, MDS_GETXATTR, MDS_HSM_ACTION, MDS_HSM_CT_REGISTER, MDS_HSM_CT_UNREGISTER, MDS_HSM_PROGRESS, MDS_HSM_REQUEST, MDS_HSM_STATE_GET, MDS_HSM_STATE_SET, MDS_INODELOCK_LAYOUT, MDS_INODELOCK_LOOKUP, MDS_INODELOCK_OPEN, MDS_INODELOCK_UPDATE, MDS_IS_SUBDIR, MDS_LAST_OPC, MDS_OPEN_APPEND, MDS_OPEN_BY_FID, MDS_OPEN_CREAT, MDS_OPEN_CREATED, MDS_OPEN_CROSS, MDS_OPEN_DELAY_CREATE, MDS_OPEN_DIRECTORY, MDS_OPEN_EXCL, MDS_OPEN_HAS_EA, MDS_OPEN_HAS_OBJS, MDS_OPEN_JOIN_FILE, MDS_OPEN_LOCK, MDS_OPEN_NEWSTRIPE, MDS_OPEN_NORESTORE, MDS_OPEN_OWNEROVERRIDE, MDS_OPEN_SYNC, MDS_OPEN_TRUNC, MDS_OPEN_VOLATILE, MDS_PIN, MDS_QUOTACHECK, MDS_QUOTACTL, MDS_READPAGE, MDS_REINT, MDS_SET_INFO, MDS_SETATTR64_REC, MDS_SETXATTR, MDS_STATFS, MDS_STATUS_CONN, MDS_STATUS_LOV, MDS_SWAP_LAYOUTS, MDS_SYNC, MDS_UNLINK64_REC, MDS_UNLINK_REC, MDS_UNPIN, MDS_WRITEPAGE, MGS_CONNECT, MGS_DISCONNECT, MGS_EXCEPTION, MGS_LAST_OPC, MGS_PARAM_MAXLEN, MGS_SET_INFO, MGS_TARGET_DEL, MGS_TARGET_REG, MSG_CONNECT_ASYNC, MSG_CONNECT_INITIAL, MSG_CONNECT_LIBCLIENT, MSG_CONNECT_NEXT_VER, MSG_CONNECT_RECONNECT, MSG_CONNECT_RECOVERING, MSG_CONNECT_REPLAYABLE, MSG_CONNECT_TRANSNO, MSG_DELAY_REPLAY, MSG_GEN_FLAG_MASK, MSG_LAST_REPLAY, MSG_LOCK_REPLAY_DONE, MSG_OP_FLAG_MASK, MSG_OP_FLAG_SHIFT, MSG_PTLRPC_BODY_OFF, MSG_PTLRPC_HEADER_OFF, MSG_REPLAY, MSG_REQ_REPLAY_DONE, MSG_RESENT, MSG_VERSION_REPLAY, MSGHDR_AT_SUPPORT, MSGHDR_CKSUM_INCOMPAT18, MTI_NAME_MAXLEN, name, OBD_BRW_ASYNC, OBD_BRW_CHECK, OBD_BRW_FROM_GRANT, OBD_BRW_GRANTED, OBD_BRW_MEMALLOC, OBD_BRW_NOCACHE, OBD_BRW_NOQUOTA, OBD_BRW_OVER_GRPQUOTA, OBD_BRW_OVER_USRQUOTA, OBD_BRW_READ, OBD_BRW_SOFT_SYNC, OBD_BRW_SRVLOCK, OBD_BRW_SYNC, OBD_BRW_WRITE, OBD_CFG_REC, OBD_CKSUM_ADLER, OBD_CKSUM_CRC32, OBD_CKSUM_CRC32C, OBD_CONNECT_64BITHASH, OBD_CONNECT_ACL, OBD_CONNECT_AT, OBD_CONNECT_ATTRFID, OBD_CONNECT_BRW_SIZE, OBD_CONNECT_BULK_MBITS, OBD_CONNECT_CANCELSET, OBD_CONNECT_CHANGE_QS, OBD_CONNECT_CKSUM, OBD_CONNECT_CROW, OBD_CONNECT_DIR_STRIPE, OBD_CONNECT_EINPROGRESS, OBD_CONNECT_FID, OBD_CONNECT_FLAGS2, OBD_CONNECT_FLOCK_DEAD, OBD_CONNECT_FLOCK_OWNER, OBD_CONNECT_FULL20, OBD_CONNECT_GRANT, OBD_CONNECT_GRANT_PARAM, OBD_CONNECT_GRANT_SHRINK, OBD_CONNECT_IBITS, OBD_CONNECT_IMP_RECOV, OBD_CONNECT_INDEX, OBD_CONNECT_JOBSTATS, OBD_CONNECT_JOIN, OBD_CONNECT_LAYOUTLOCK, OBD_CONNECT_LFSCK, OBD_CONNECT_LIGHTWEIGHT, OBD_CONNECT_LOCK_AHEAD, OBD_CONNECT_LOV_V3, OBD_CONNECT_LRU_RESIZE, OBD_CONNECT_LVB_TYPE, OBD_CONNECT_MAX_EASIZE, OBD_CONNECT_MAXBYTES, OBD_CONNECT_MDS, OBD_CONNECT_MDS_CAPA, OBD_CONNECT_MDS_MDS, OBD_CONNECT_MULTIMODRPCS, OBD_CONNECT_NANOSEC_TIME, OBD_CONNECT_NODEVOH, OBD_CONNECT_OBDOPACK, OBD_CONNECT_OPEN_BY_FID, OBD_CONNECT_OSS_CAPA, OBD_CONNECT_PINGLESS, OBD_CONNECT_QUOTA64, OBD_CONNECT_RDONLY, OBD_CONNECT_REAL, OBD_CONNECT_REQPORTAL, OBD_CONNECT_RMT_CLIENT, OBD_CONNECT_RMT_CLIENT_FORCE, OBD_CONNECT_SHORTIO, OBD_CONNECT_SKIP_ORPHAN, OBD_CONNECT_SOM, OBD_CONNECT_SRVLOCK, OBD_CONNECT_SUBTREE, OBD_CONNECT_TRANSNO, OBD_CONNECT_TRUNCLOCK, OBD_CONNECT_UMASK, OBD_CONNECT_UNLINK_CLOSE, OBD_CONNECT_VBR, OBD_CONNECT_VERSION, OBD_CONNECT_XATTR, OBD_FL_CKSUM_ADLER, OBD_FL_CKSUM_CRC32, OBD_FL_CKSUM_CRC32C, OBD_FL_CKSUM_RSVD2, OBD_FL_CKSUM_RSVD3, OBD_FL_CREATE_CROW, OBD_FL_DEBUG_CHECK, OBD_FL_DELORPHAN, OBD_FL_FLUSH, OBD_FL_IDONLY, OBD_FL_INLINEDATA, OBD_FL_LOCAL_MASK, OBD_FL_MMAP, OBD_FL_NO_GRPQUOTA, OBD_FL_NO_USRQUOTA, OBD_FL_NORPC, OBD_FL_NOSPC_BLK, OBD_FL_OBDMDEXISTS, OBD_FL_RECOV_RESEND, OBD_FL_RECREATE_OBJS, OBD_FL_SHORT_IO, OBD_FL_SHRINK_GRANT, OBD_FL_SRVLOCK, OBD_IDX_READ, OBD_LAST_OPC, OBD_LOG_CANCEL, OBD_MD_FLACL, OBD_MD_FLATIME, OBD_MD_FLBLKSZ, OBD_MD_FLBLOCKS, OBD_MD_FLCKSPLIT, OBD_MD_FLCKSUM, OBD_MD_FLCROSSREF, OBD_MD_FLCTIME, OBD_MD_FLDATAVERSION, OBD_MD_FLDIREA, OBD_MD_FLEASIZE, OBD_MD_FLEPOCH, OBD_MD_FLFID, OBD_MD_FLFLAGS, OBD_MD_FLGENER, OBD_MD_FLGETATTRLOCK, OBD_MD_FLGID, OBD_MD_FLGRANT, OBD_MD_FLGROUP, OBD_MD_FLGRPQUOTA, OBD_MD_FLHANDLE, OBD_MD_FLID, OBD_MD_FLMDSCAPA, OBD_MD_FLMODE, OBD_MD_FLMODEASIZE, OBD_MD_FLMTIME, OBD_MD_FLNLINK, OBD_MD_FLOSSCAPA, OBD_MD_FLQOS, OBD_MD_FLRDEV, OBD_MD_FLRMTLGETFACL, OBD_MD_FLRMTLSETFACL, OBD_MD_FLRMTPERM, OBD_MD_FLRMTRGETFACL, OBD_MD_FLRMTRSETFACL, OBD_MD_FLSIZE, OBD_MD_FLTYPE, OBD_MD_FLUID, OBD_MD_FLUSRQUOTA, OBD_MD_FLXATTR, OBD_MD_FLXATTRLS, OBD_MD_FLXATTRRM, OBD_MD_LINKNAME, OBD_MD_MDS, OBD_MD_MEA, OBD_MD_REINT, OBD_MD_TSTATE, OBD_OBJECT_EOF, OBD_PING, OBD_QC_CALLBACK, offsetof, OST_CLOSE, OST_CONNECT, OST_CREATE, OST_DESTROY, OST_DISCONNECT, OST_GET_INFO, OST_GETATTR, OST_LADVISE, OST_LAST_OPC, OST_LVB_ERR_INIT, OST_LVB_ERR_MASK, OST_MAX_PRECREATE, OST_MIN_PRECREATE, OST_OPEN, OST_PUNCH, OST_QUOTA_ADJUST_QUNIT, OST_QUOTACHECK, OST_QUOTACTL, OST_READ, OST_REPLY, OST_SET_INFO, OST_SETATTR, OST_STATFS, OST_SYNC, OST_SZ_REC, OST_WRITE, OUT_ATTR_GET, OUT_ATTR_SET, OUT_CREATE, OUT_DESTROY, OUT_INDEX_DELETE, OUT_INDEX_INSERT, OUT_INDEX_LOOKUP, OUT_PUNCH, OUT_READ, OUT_REF_ADD, OUT_REF_DEL, OUT_UPDATE, OUT_UPDATE_LAST_OPC, OUT_WRITE, OUT_XATTR_DEL, OUT_XATTR_GET, OUT_XATTR_SET, PTL_RPC_MSG_ERR, PTL_RPC_MSG_REPLY, PTL_RPC_MSG_REQUEST, PTLRPC_MSG_VERSION, PTLRPC_NUM_VERSIONS, Q_FINVALIDATE, Q_GETOINFO, Q_GETOQUOTA, Q_INITQUOTA, Q_QUOTACHECK, QUOTA_DQACQ, QUOTA_DQREL, QUOTA_LAST_OPC, QUOTABLOCK_BITS, QUOTABLOCK_SIZE, REINT_CREATE, REINT_LINK, REINT_MAX, REINT_MIGRATE, REINT_OPEN, REINT_RENAME, REINT_RMENTRY, REINT_SETATTR, REINT_SETXATTR, REINT_UNLINK, REPLY_REC_OFF, REQ_REC_OFF, RES_NAME_SIZE, SEC_CTX_FINI, SEC_CTX_INIT, SEC_CTX_INIT_CONT, SEC_LAST_OPC, SEQ_ALLOC_META, SEQ_ALLOC_SUPER, SEQ_FIRST_OPC, SEQ_LAST_OPC, SEQ_QUERY, start, and UPDATE_RECORD_CONTINUE.
Referenced by main(), and ptlrpc_init().
int main ()
Definition at line 55 of file wiretest.c.
References lustre_assert_wire_constants(), and ret.
Variable Documentation
int ret
Definition at line 51 of file wiretest.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.