Lustre: lustre/obdclass/uuid.c File Reference
lustre/obdclass/uuid.c File Reference
#include <libcfs/libcfs.h>
#include <obd_support.h>
#include <obd_class.h>
Defines
#define DEBUG_SUBSYSTEM S_CLASS
#define CONSUME(val, ptr) (val) = consume(sizeof(val), (ptr))
Functions
static size_t consume (size_t nob, __u8 **ptr)
static void uuid_unpack (class_uuid_t in, __u16 *uu, size_t nr)
void class_uuid_unparse (class_uuid_t uu, struct obd_uuid *out)
Define Documentation
#define CONSUME (val, ptr) (val) = consume(sizeof(val), (ptr))
Definition at line 58 of file uuid.c.
Referenced by uuid_unpack().
#define DEBUG_SUBSYSTEM S_CLASS
Definition at line 41 of file uuid.c.
Function Documentation
void class_uuid_unparse (class_uuid_t uu, struct obd_uuid * out)
Definition at line 70 of file uuid.c.
References ARRAY_SIZE, CLASSERT, obd_uuid::uuid, uuid, and uuid_unpack().
Referenced by ll_init_sbi(), lustre_start_mgc(), lwp_setup(), osd_scrub_setup(), and osp_init0().
static size_t consume (size_t nob, __u8 ** ptr) [inline, static]
Definition at line 47 of file uuid.c.
References LASSERT.
static void uuid_unpack (class_uuid_t in, __u16 * uu, size_t nr) [static]
Definition at line 60 of file uuid.c.
References CONSUME, and LASSERT.
Referenced by class_uuid_unparse().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.