Lustre: lustre/llite/vvp_internal.h File Reference
lustre/llite/vvp_internal.h File Reference
#include <lustre/lustre_idl.h>
#include <cl_object.h>
Data Structures
struct vvp_io
IO state private to VVP layer.
struct vvp_thread_info
struct vvp_session
struct vvp_object
VPP-private object state.
struct vvp_page
VVP-private page state.
struct vvp_device
struct vvp_lock
Defines
#define CLOBINVRNT(env, clob, expr) ((void)sizeof(env), (void)sizeof(clob), (void)sizeof !!(expr))
Enumerations
enum vvp_io_subtype { IO_NORMAL, IO_SPLICE }
Functions
static struct vvp_thread_info * vvp_env_info (const struct lu_env *env)
static struct cl_lock * vvp_env_lock (const struct lu_env *env)
static struct cl_attr * vvp_env_thread_attr (const struct lu_env *env)
static struct cl_io * vvp_env_thread_io (const struct lu_env *env)
static struct vvp_session * vvp_env_session (const struct lu_env *env)
static struct vvp_io * vvp_env_io (const struct lu_env *env)
static struct vvp_page * cl2vvp_page (const struct cl_page_slice *slice)
static pgoff_t vvp_index (struct vvp_page *vpg)
static struct lu_device * vvp2lu_dev (struct vvp_device *vdv)
static struct vvp_device * lu2vvp_dev (const struct lu_device *d)
static struct vvp_device * cl2vvp_dev (const struct cl_device *d)
static struct vvp_object * cl2vvp (const struct cl_object *obj)
static struct vvp_object * lu2vvp (const struct lu_object *obj)
static struct inode * vvp_object_inode (const struct cl_object *obj)
int vvp_object_invariant (const struct cl_object *obj)
struct vvp_object * cl_inode2vvp (struct inode *inode)
static struct page * cl2vm_page (const struct cl_page_slice *slice)
static struct vvp_lock * cl2vvp_lock (const struct cl_lock_slice *slice)
int lov_read_and_clear_async_rc (struct cl_object *clob)
int vvp_io_init (const struct lu_env *env, struct cl_object *obj, struct cl_io *io)
int vvp_io_write_commit (const struct lu_env *env, struct cl_io *io)
int vvp_lock_init (const struct lu_env *env, struct cl_object *obj, struct cl_lock *lock, const struct cl_io *io)
int vvp_page_init (const struct lu_env *env, struct cl_object *obj, struct cl_page *page, pgoff_t index)
struct lu_object * vvp_object_alloc (const struct lu_env *env, const struct lu_object_header *hdr, struct lu_device *dev)
int vvp_global_init (void)
A mutex serializing calls to vvp_inode_fini() under extreme memory pressure, when environments cannot be allocated.
void vvp_global_fini (void)
Variables
struct lu_device_type vvp_device_type
struct lu_context_key vvp_session_key
struct lu_context_key vvp_thread_key
struct kmem_cache * vvp_lock_kmem
struct kmem_cache * vvp_object_kmem
struct file_operations vvp_dump_pgcache_file_ops
Define Documentation
#define CLOBINVRNT (env, clob, expr) ((void)sizeof(env), (void)sizeof(clob), (void)sizeof !!(expr))
Definition at line 331 of file vvp_internal.h.
Referenced by vvp_io_advance(), vvp_io_fault_end(), vvp_io_fault_fini(), vvp_io_fini(), vvp_io_init(), vvp_io_one_lock_index(), vvp_io_read_start(), vvp_lock_enqueue(), vvp_lock_init(), and vvp_page_init().
Enumeration Type Documentation
enum vvp_io_subtype
Enumerator:
IO_NORMAL
normal IO
IO_SPLICE
io started from splice_{read|write}
Definition at line 54 of file vvp_internal.h.
Function Documentation
static struct page* cl2vm_page (const struct cl_page_slice * slice) [static, read]
Definition at line 311 of file vvp_internal.h.
References cl2vvp_page(), and vvp_page::vpg_page.
Referenced by vvp_page_assume(), vvp_page_delete(), vvp_page_discard(), vvp_page_disown(), vvp_page_export(), vvp_page_is_vmlocked(), vvp_page_make_ready(), vvp_page_prep_read(), vvp_page_prep_write(), and vvp_page_unassume().
static struct vvp_object* cl2vvp (const struct cl_object * obj) [static, read]
Definition at line 293 of file vvp_internal.h.
References vvp_object::vob_cl.
Referenced by vvp_object_inode(), vvp_page_init(), and vvp_transient_page_fini().
static struct vvp_device* cl2vvp_dev (const struct cl_device * d) [static, read]
Definition at line 288 of file vvp_internal.h.
References vvp_device::vdv_cl.
static struct vvp_lock* cl2vvp_lock (const struct cl_lock_slice * slice) [static, read]
Definition at line 316 of file vvp_internal.h.
References vvp_lock::vlk_cl.
Referenced by vvp_lock_fini().
static struct vvp_page* cl2vvp_page (const struct cl_page_slice * slice) [static, read]
Definition at line 259 of file vvp_internal.h.
References vvp_page::vpg_cl.
Referenced by cl2vm_page(), ll_io_read_page(), ll_read_ahead_page(), vvp_page_completion_read(), vvp_page_completion_write(), vvp_page_discard(), vvp_page_fini(), vvp_page_own(), vvp_page_print(), vvp_pgcache_page_show(), and vvp_transient_page_fini().
struct vvp_object* cl_inode2vvp (struct inode * inode) [read]
Definition at line 277 of file vvp_object.c.
References cl_object::co_lu, LASSERT, ll_i2info(), ll_inode_info::lli_clob, lu_object::lo_header, lu2vvp(), lu_object_locate(), and vvp_device_type.
Referenced by dirty_cnt(), ll_vm_close(), ll_vm_open(), and vvp_vmpage_error().
static struct vvp_object* lu2vvp (const struct lu_object * obj) [static, read]
Definition at line 298 of file vvp_internal.h.
References cl_object::co_lu, and vvp_object::vob_cl.
Referenced by cl_inode2vvp(), vvp_object_free(), vvp_object_init(), and vvp_object_print().
static struct vvp_device* lu2vvp_dev (const struct lu_device * d) [static, read]
Definition at line 283 of file vvp_internal.h.
References cl_device::cd_lu_dev, and vvp_device::vdv_cl.
Referenced by vvp_device_fini(), vvp_device_free(), vvp_device_init(), and vvp_object_init().
static struct lu_device* vvp2lu_dev (struct vvp_device * vdv) [static, read]
Definition at line 278 of file vvp_internal.h.
References cl_device::cd_lu_dev, and vvp_device::vdv_cl.
Referenced by vvp_device_alloc().
static struct vvp_thread_info* vvp_env_info (const struct lu_env * env) [static, read]
Definition at line 158 of file vvp_internal.h.
References LASSERT, lu_env::le_ctx, lu_context_key_get(), and vvp_thread_key.
Referenced by vvp_env_lock(), vvp_env_thread_attr(), vvp_env_thread_io(), and vvp_mmap_locks().
static struct vvp_io* vvp_env_io (const struct lu_env * env) [static, read]
Definition at line 209 of file vvp_internal.h.
References vvp_session::vs_ios, and vvp_env_session().
Referenced by can_populate_pages(), cl2vvp_io(), cl_is_normalio(), cl_setattr_ost(), ll_direct_IO(), ll_fault0(), ll_fault_io_init(), ll_file_io_generic(), ll_io_read_page(), ll_page_mkwrite0(), ll_readahead(), ll_write_begin(), ll_write_end(), vvp_io_init(), vvp_io_one_lock_index(), vvp_io_rw_lock(), and vvp_io_write_commit().
static struct cl_lock* vvp_env_lock (const struct lu_env * env) [static, read]
Definition at line 168 of file vvp_internal.h.
References vvp_thread_info::vti_lock, and vvp_env_info().
Referenced by cl_get_grouplock(), and cl_glimpse_lock().
static struct vvp_session* vvp_env_session (const struct lu_env * env) [static, read]
Definition at line 199 of file vvp_internal.h.
References LASSERT, lu_env::le_ses, lu_context_key_get(), and vvp_session_key.
Referenced by vvp_env_io().
static struct cl_attr* vvp_env_thread_attr (const struct lu_env * env) [static, read]
Definition at line 177 of file vvp_internal.h.
References vvp_thread_info::vti_attr, and vvp_env_info().
Referenced by ll_merge_attr(), ll_prepare_partial_page(), ll_readahead(), vvp_io_setattr_time(), and vvp_prep_size().
static struct cl_io* vvp_env_thread_io (const struct lu_env * env) [static, read]
Definition at line 186 of file vvp_internal.h.
References vvp_thread_info::vti_io, and vvp_env_info().
Referenced by cl_get_grouplock(), cl_io_get(), cl_setattr_ost(), cl_sync_file_range(), ll_data_version(), ll_fault_io_init(), ll_file_io_generic(), ll_ladvise(), and ll_writepage().
void vvp_global_fini (void)
Definition at line 302 of file vvp_dev.c.
References lu_device_type_fini(), lu_kmem_fini(), and vvp_device_type.
Referenced by lustre_exit(), and lustre_init().
int vvp_global_init (void)
A mutex serializing calls to vvp_inode_fini() under extreme memory pressure, when environments cannot be allocated.
Definition at line 282 of file vvp_dev.c.
References lu_device_type_init(), lu_kmem_fini(), lu_kmem_init(), and vvp_device_type.
Referenced by lustre_init().
static pgoff_t vvp_index (struct vvp_page * vpg) [inline, static]
Definition at line 264 of file vvp_internal.h.
References cl_page_slice::cpl_index, and vvp_page::vpg_cl.
Referenced by ll_io_read_page(), ll_prepare_partial_page(), page_list_sanity_check(), and vvp_io_fault_start().
int vvp_io_init (const struct lu_env * env, struct cl_object * obj, struct cl_io * io)
Definition at line 1448 of file vvp_io.c.
References CDEBUG, CERROR, cl_io::ci_ignore_layout, cl_io::ci_lockreq, cl_io::ci_restore_needed, cl_io::ci_rw, cl_io::ci_type, cl_io::ci_verify_layout, CILR_MANDATORY, CIT_MISC, CIT_READ, CIT_SETATTR, CIT_WRITE, cl_io_is_trunc(), cl_io_slice_add(), CL_IO_SLICE_CLEAN, CLOBINVRNT, cl_object::co_lu, cl_io_rw_common::crw_count, D_VFSTRACE, DFID, ENTRY, ll_get_fsname(), ll_i2info(), ll_layout_refresh(), ll_inode_info::lli_jobid, lu_object_fid(), lustre_get_jobid(), PFID, RETURN, cl_io::u, vvp_io::vui_cl, vvp_io::vui_layout_gen, vvp_io::vui_ra_valid, vvp_io::vui_tot_count, vvp_io::vui_tot_nrsegs, vvp_env_io(), vvp_object_inode(), and vvp_object_invariant().
int vvp_io_write_commit (const struct lu_env * env, struct cl_io * io)
Definition at line 968 of file vvp_io.c.
References CDEBUG, cl_io::ci_obj, cl_io_commit_async(), cl_io_is_mkwrite(), cl_page_discard(), cl_page_disown(), cl_page_list_del(), cl_page_list_fini(), cl_page_list_first(), cl_page_put(), cl_page_vmpage(), cl_page::cp_reference, D_VFSTRACE, ENTRY, ergo, LASSERT, LASSERTF, ll_merge_attr(), lu_ref_del(), page_list_sanity_check(), cl_page_list::pl_nr, RETURN, vvp_io::u, vvp_env_io(), vvp_io_commit_sync(), vvp_object_inode(), vvp_io::write, and write_commit_callback().
int vvp_lock_init (const struct lu_env * env, struct cl_object * obj, struct cl_lock * lock, const struct cl_io * io)
Definition at line 73 of file vvp_lock.c.
References cl_lock_slice_add(), CLOBINVRNT, OBD_SLAB_ALLOC_PTR_GFP, vvp_lock::vlk_cl, vvp_lock_kmem, and vvp_object_invariant().
struct lu_object* vvp_object_alloc (const struct lu_env * env, const struct lu_object_header * hdr, struct lu_device * dev) [read]
Definition at line 290 of file vvp_object.c.
References cfs_size_round(), cl_object_header_init(), cl_object::co_lu, cl_object::co_ops, cl_object_header::coh_lu, cl_object_header::coh_page_bufsize, lu_object::lo_ops, lu_object_add_top(), lu_object_init(), OBD_SLAB_ALLOC_PTR_GFP, vvp_object::vob_cl, vvp_object::vob_header, and vvp_object_kmem.
static struct inode* vvp_object_inode (const struct cl_object * obj) [static, read]
Definition at line 303 of file vvp_internal.h.
References cl2vvp(), and vvp_object::vob_inode.
Referenced by ll_io_read_page(), ll_page_mkwrite0(), ll_read_ahead_page(), ll_readahead(), vvp_attr_get(), vvp_attr_update(), vvp_io_fault_end(), vvp_io_fault_iter_init(), vvp_io_fault_start(), vvp_io_fini(), vvp_io_init(), vvp_io_read_start(), vvp_io_rw_end(), vvp_io_setattr_end(), vvp_io_setattr_fini(), vvp_io_setattr_start(), vvp_io_write_commit(), vvp_io_write_start(), vvp_object_glimpse(), vvp_object_invariant(), vvp_object_size_lock(), vvp_object_size_unlock(), vvp_page_completion_read(), vvp_page_completion_write(), vvp_page_delete(), vvp_pgcache_find(), vvp_pgcache_show(), vvp_prep_size(), vvp_prune(), vvp_req_attr_set(), and vvp_transient_page_is_vmlocked().
int vvp_object_invariant (const struct cl_object * obj)
Definition at line 59 of file vvp_object.c.
References ll_i2info(), ll_inode_info::lli_clob, and vvp_object_inode().
Referenced by vvp_io_advance(), vvp_io_fault_end(), vvp_io_fault_fini(), vvp_io_fini(), vvp_io_init(), vvp_io_one_lock_index(), vvp_io_read_start(), vvp_lock_enqueue(), vvp_lock_init(), and vvp_page_init().
int vvp_page_init (const struct lu_env * env, struct cl_object * obj, struct cl_page * page, pgoff_t index)
Definition at line 517 of file vvp_page.c.
References cl2vvp(), cl_object_page_slice(), cl_page_slice_add(), CLOBINVRNT, cl_page::cp_ref, cl_page::cp_type, cl_page::cp_vmpage, CPT_CACHEABLE, vvp_object::vob_transient_pages, vvp_page::vpg_cl, vvp_page::vpg_page, and vvp_object_invariant().
Variable Documentation
struct lu_device_type vvp_device_type
Definition at line 271 of file vvp_dev.c.
Referenced by cl_inode2vvp(), cl_sb_init(), vvp_global_fini(), vvp_global_init(), and vvp_pgcache_page_show().
struct file_operations vvp_dump_pgcache_file_ops
Definition at line 653 of file vvp_dev.c.
struct kmem_cache* vvp_lock_kmem
Definition at line 60 of file vvp_dev.c.
Referenced by vvp_lock_fini(), and vvp_lock_init().
struct kmem_cache* vvp_object_kmem
Definition at line 61 of file vvp_dev.c.
Referenced by vvp_object_alloc(), and vvp_object_free().
struct lu_context_key vvp_session_key
Definition at line 140 of file vvp_dev.c.
Referenced by vvp_env_session().
struct lu_context_key vvp_thread_key
Definition at line 164 of file vvp_dev.c.
Referenced by vvp_env_info().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.