Lustre: lustre/llite/vvp_io.c File Reference
lustre/llite/vvp_io.c File Reference
#include <obd.h>
#include "llite_internal.h"
#include "vvp_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LLITE
Functions
static struct vvp_io * cl2vvp_io (const struct lu_env *env, const struct cl_io_slice *slice)
static int cl_is_normalio (const struct lu_env *env, const struct cl_io *io)
True, if io is a normal io, False for splice_{read,write}.
static bool can_populate_pages (const struct lu_env *env, struct cl_io *io, struct inode *inode)
For swapping layout.
static void vvp_object_size_lock (struct cl_object *obj)
static void vvp_object_size_unlock (struct cl_object *obj)
static int vvp_prep_size (const struct lu_env *env, struct cl_object *obj, struct cl_io *io, loff_t start, size_t count, int *exceed)
Helper function that if necessary adjusts file size (inode->i_size), when position at the offset pos is accessed.
static int vvp_io_one_lock_index (const struct lu_env *env, struct cl_io *io, __u32 enqflags, enum cl_lock_mode mode, pgoff_t start, pgoff_t end)
static int vvp_io_one_lock (const struct lu_env *env, struct cl_io *io, __u32 enqflags, enum cl_lock_mode mode, loff_t start, loff_t end)
static int vvp_io_write_iter_init (const struct lu_env *env, const struct cl_io_slice *ios)
static void vvp_io_write_iter_fini (const struct lu_env *env, const struct cl_io_slice *ios)
static int vvp_io_fault_iter_init (const struct lu_env *env, const struct cl_io_slice *ios)
static void vvp_io_fini (const struct lu_env *env, const struct cl_io_slice *ios)
static void vvp_io_fault_fini (const struct lu_env *env, const struct cl_io_slice *ios)
static enum cl_lock_mode vvp_mode_from_vma (struct vm_area_struct *vma)
static int vvp_mmap_locks (const struct lu_env *env, struct vvp_io *vio, struct cl_io *io)
static void vvp_io_advance (const struct lu_env *env, const struct cl_io_slice *ios, size_t nob)
static void vvp_io_update_iov (const struct lu_env *env, struct vvp_io *vio, struct cl_io *io)
static int vvp_io_rw_lock (const struct lu_env *env, struct cl_io *io, enum cl_lock_mode mode, loff_t start, loff_t end)
static int vvp_io_read_lock (const struct lu_env *env, const struct cl_io_slice *ios)
static int vvp_io_fault_lock (const struct lu_env *env, const struct cl_io_slice *ios)
static int vvp_io_write_lock (const struct lu_env *env, const struct cl_io_slice *ios)
static int vvp_io_setattr_iter_init (const struct lu_env *env, const struct cl_io_slice *ios)
static int vvp_io_setattr_lock (const struct lu_env *env, const struct cl_io_slice *ios)
Implementation of cl_io_operations::cio_lock() method for CIT_SETATTR io.
static int vvp_do_vmtruncate (struct inode *inode, size_t size)
static int vvp_io_setattr_time (const struct lu_env *env, const struct cl_io_slice *ios)
static int vvp_io_setattr_start (const struct lu_env *env, const struct cl_io_slice *ios)
static void vvp_io_setattr_end (const struct lu_env *env, const struct cl_io_slice *ios)
static void vvp_io_setattr_fini (const struct lu_env *env, const struct cl_io_slice *ios)
static int vvp_io_read_start (const struct lu_env *env, const struct cl_io_slice *ios)
static int vvp_io_commit_sync (const struct lu_env *env, struct cl_io *io, struct cl_page_list *plist, int from, int to)
static void write_commit_callback (const struct lu_env *env, struct cl_io *io, struct cl_page *page)
static bool page_list_sanity_check (struct cl_object *obj, struct cl_page_list *plist)
int vvp_io_write_commit (const struct lu_env *env, struct cl_io *io)
static int vvp_io_write_start (const struct lu_env *env, const struct cl_io_slice *ios)
static void vvp_io_rw_end (const struct lu_env *env, const struct cl_io_slice *ios)
static int vvp_io_kernel_fault (struct vvp_fault_io *cfio)
static void mkwrite_commit_callback (const struct lu_env *env, struct cl_io *io, struct cl_page *page)
static int vvp_io_fault_start (const struct lu_env *env, const struct cl_io_slice *ios)
static void vvp_io_fault_end (const struct lu_env *env, const struct cl_io_slice *ios)
static int vvp_io_fsync_start (const struct lu_env *env, const struct cl_io_slice *ios)
static int vvp_io_read_ahead (const struct lu_env *env, const struct cl_io_slice *ios, pgoff_t start, struct cl_read_ahead *ra)
int vvp_io_init (const struct lu_env *env, struct cl_object *obj, struct cl_io *io)
Variables
static struct cl_io_operations vvp_io_ops
Define Documentation
#define DEBUG_SUBSYSTEM S_LLITE
Definition at line 42 of file vvp_io.c.
Function Documentation
static bool can_populate_pages (const struct lu_env * env, struct cl_io * io, struct inode * inode) [static]
For swapping layout.
The file's layout may have changed. To avoid populating pages to a wrong stripe, we have to verify the correctness of layout. It works because swapping layout processes have to acquire group lock.
Definition at line 78 of file vvp_io.c.
References cl_io::ci_continue, cl_io::ci_need_restart, cl_io::ci_type, CIT_FAULT, CIT_READ, CIT_WRITE, ll_i2info(), ll_layout_version_get(), OBD_FAIL_CHECK_RESET, OBD_FAIL_LLITE_LOST_LAYOUT, vvp_io::vui_layout_gen, and vvp_env_io().
Referenced by vvp_io_read_start(), and vvp_io_write_start().
static struct vvp_io* cl2vvp_io (const struct lu_env * env, const struct cl_io_slice * slice) [static, read]
Definition at line 49 of file vvp_io.c.
References LASSERT, vvp_io::vui_cl, and vvp_env_io().
Referenced by vvp_io_advance(), vvp_io_fault_iter_init(), vvp_io_fault_lock(), vvp_io_fault_start(), vvp_io_fini(), vvp_io_read_ahead(), vvp_io_read_start(), vvp_io_rw_end(), vvp_io_write_iter_fini(), vvp_io_write_iter_init(), and vvp_io_write_start().
static int cl_is_normalio (const struct lu_env * env, const struct cl_io * io) [static]
True, if io is a normal io, False for splice_{read,write}.
Definition at line 63 of file vvp_io.c.
References cl_io::ci_type, CIT_READ, CIT_WRITE, IO_NORMAL, LASSERT, vvp_io::vui_io_subtype, and vvp_env_io().
Referenced by vvp_io_advance(), vvp_io_update_iov(), and vvp_mmap_locks().
static void mkwrite_commit_callback (const struct lu_env * env, struct cl_io * io, struct cl_page * page) [static]
Definition at line 1196 of file vvp_io.c.
References cl_page::cp_vmpage.
Referenced by vvp_io_fault_start().
static bool page_list_sanity_check (struct cl_object * obj, struct cl_page_list * plist) [static]
Definition at line 944 of file vvp_io.c.
References cl_object_page_slice(), CL_PAGE_EOF, cl_page_list_for_each, and vvp_index().
Referenced by vvp_io_write_commit().
static int vvp_do_vmtruncate (struct inode * inode, size_t size) [static]
Definition at line 687 of file vvp_io.c.
References ll_inode_size_lock(), ll_inode_size_unlock(), and ll_truncate_pagecache.
Referenced by vvp_io_setattr_end().
static void vvp_io_advance (const struct lu_env * env, const struct cl_io_slice * ios, size_t nob) [static]
Definition at line 483 of file vvp_io.c.
References cl_io::ci_obj, cl_io_slice::cis_io, cl2vvp_io(), cl_is_normalio(), CLOBINVRNT, LASSERT, vvp_io::vui_iov_olen, vvp_io::vui_iter, vvp_io::vui_tot_count, vvp_io::vui_tot_nrsegs, and vvp_object_invariant().
static int vvp_io_commit_sync (const struct lu_env * env, struct cl_io * io, struct cl_page_list * plist, int from, int to) [static]
Definition at line 870 of file vvp_io.c.
References cl_2queue::c2_qin, cl_2queue::c2_qout, cl_io::ci_queue, cl_2queue_fini(), cl_2queue_init(), cl_io_submit_sync(), cl_page_clip(), cl_page_disown(), cl_page_list_del(), cl_page_list_first(), cl_page_list_last(), cl_page_list_splice(), cl_page_put(), cl_page_vmpage(), cl_page::cp_reference, CRT_WRITE, ENTRY, lu_ref_del(), cl_page_list::pl_nr, and RETURN.
Referenced by vvp_io_write_commit().
static void vvp_io_fault_end (const struct lu_env * env, const struct cl_io_slice * ios) [static]
Definition at line 1362 of file vvp_io.c.
References cl_io::ci_obj, cl_io_slice::cis_io, cl_io_slice::cis_obj, CLOBINVRNT, ll_i2info(), ll_inode_info::lli_trunc_sem, vvp_object_inode(), and vvp_object_invariant().
static void vvp_io_fault_fini (const struct lu_env * env, const struct cl_io_slice * ios) [static]
Definition at line 361 of file vvp_io.c.
References cl_io::ci_fault, cl_io::ci_obj, cl_io_slice::cis_io, cl_page_put(), CLOBINVRNT, cl_page::cp_reference, lu_ref_del(), cl_io::u, vvp_io_fini(), and vvp_object_invariant().
static int vvp_io_fault_iter_init (const struct lu_env * env, const struct cl_io_slice * ios) [static]
Definition at line 287 of file vvp_io.c.
References cl_io_slice::cis_obj, cl2vvp_io(), vvp_io::fault, ll_file_data::fd_file, LASSERT, LTIME_S, vvp_io::u, vvp_io::vui_fd, and vvp_object_inode().
static int vvp_io_fault_lock (const struct lu_env * env, const struct cl_io_slice * ios) [static]
Definition at line 612 of file vvp_io.c.
References cl_io::ci_fault, cl_io_slice::cis_io, cl2vvp_io(), vvp_io::fault, cl_io::u, vvp_io::u, vvp_io_one_lock_index(), and vvp_mode_from_vma().
static int vvp_io_fault_start (const struct lu_env * env, const struct cl_io_slice * ios) [static]
Definition at line 1202 of file vvp_io.c.
References cl_2queue::c2_qin, CDEBUG, cl_io::ci_fault, cl_io::ci_obj, cl_io::ci_queue, cl_io_slice::cis_io, cl2vvp_io(), cl_index(), cl_io_commit_async(), cl_object_page_slice(), cl_offset(), cl_page_assume(), cl_page_discard(), cl_page_disown(), cl_page_find(), cl_page_is_owned(), cl_page_list_add(), cl_page_list_fini(), cl_page_list_init(), cl_page_put(), cl_page_size(), cl_page::cp_reference, CPT_CACHEABLE, D_PAGE, ENTRY, EXIT, vvp_io::fault, GOTO, LASSERT, ll_i2info(), ll_invalidate_page(), ll_inode_info::lli_trunc_sem, lu_ref_add(), mkwrite_commit_callback(), OBD_FAIL_CHECK, OBD_FAIL_LLITE_FAULT_TRUNC_RACE, RETURN, size, vvp_io::u, cl_io::u, unlikely, vvp_index(), vvp_io_kernel_fault(), vvp_object_inode(), and vvp_prep_size().
static void vvp_io_fini (const struct lu_env * env, const struct cl_io_slice * ios) [static]
Definition at line 299 of file vvp_io.c.
References CDEBUG, cl_io::ci_ignore_layout, cl_io::ci_need_restart, cl_io::ci_obj, cl_io::ci_restore_needed, cl_io::ci_result, cl_io::ci_verify_layout, cl_io_slice::cis_io, cl2vvp_io(), CLOBINVRNT, cl_object::co_lu, D_VFSTRACE, DFID, ll_file_clear_flag(), ll_i2info(), ll_layout_refresh(), ll_layout_restore(), LLIF_FILE_RESTORING, lu_object_fid(), OBD_OBJECT_EOF, PFID, vvp_io::vui_layout_gen, vvp_object_inode(), and vvp_object_invariant().
Referenced by vvp_io_fault_fini(), and vvp_io_setattr_fini().
static int vvp_io_fsync_start (const struct lu_env * env, const struct cl_io_slice * ios) [static]
Definition at line 1373 of file vvp_io.c.
int vvp_io_init (const struct lu_env * env, struct cl_object * obj, struct cl_io * io)
Definition at line 1448 of file vvp_io.c.
References CDEBUG, CERROR, cl_io::ci_ignore_layout, cl_io::ci_lockreq, cl_io::ci_restore_needed, cl_io::ci_rw, cl_io::ci_type, cl_io::ci_verify_layout, CILR_MANDATORY, CIT_MISC, CIT_READ, CIT_SETATTR, CIT_WRITE, cl_io_is_trunc(), cl_io_slice_add(), CL_IO_SLICE_CLEAN, CLOBINVRNT, cl_object::co_lu, cl_io_rw_common::crw_count, D_VFSTRACE, DFID, ENTRY, ll_get_fsname(), ll_i2info(), ll_layout_refresh(), ll_inode_info::lli_jobid, lu_object_fid(), lustre_get_jobid(), PFID, RETURN, cl_io::u, vvp_io::vui_cl, vvp_io::vui_layout_gen, vvp_io::vui_ra_valid, vvp_io::vui_tot_count, vvp_io::vui_tot_nrsegs, vvp_env_io(), vvp_object_inode(), and vvp_object_invariant().
static int vvp_io_kernel_fault (struct vvp_fault_io * cfio) [static]
Definition at line 1158 of file vvp_io.c.
References CDEBUG, CERROR, D_PAGE, LL_CDEBUG_PAGE, unlikely, and VM_FAULT_RETRY.
Referenced by vvp_io_fault_start().
static int vvp_io_one_lock (const struct lu_env * env, struct cl_io * io, __u32 enqflags, enum cl_lock_mode mode, loff_t start, loff_t end) [static]
Definition at line 256 of file vvp_io.c.
References cl_io::ci_obj, cl_index(), and vvp_io_one_lock_index().
Referenced by vvp_io_rw_lock(), and vvp_io_setattr_lock().
static int vvp_io_one_lock_index (const struct lu_env * env, struct cl_io * io, __u32 enqflags, enum cl_lock_mode mode, pgoff_t start, pgoff_t end) [static]
Definition at line 223 of file vvp_io.c.
References CDEBUG, CEF_LOCK_MATCH, cl_io::ci_obj, cl_io_lock_add(), cl_lock_descr::cld_end, cl_lock_descr::cld_enq_flags, cl_lock_descr::cld_gid, cl_lock_descr::cld_mode, cl_lock_descr::cld_obj, cl_lock_descr::cld_start, CLM_GROUP, CLOBINVRNT, D_VFSTRACE, ENTRY, ll_file_data::fd_flags, ll_file_data::fd_grouplock, ll_grouplock::lg_gid, LL_FILE_GROUP_LOCKED, RETURN, vvp_io::vui_fd, vvp_io::vui_link, vvp_env_io(), and vvp_object_invariant().
Referenced by vvp_io_fault_lock(), and vvp_io_one_lock().
static int vvp_io_read_ahead (const struct lu_env * env, const struct cl_io_slice * ios, pgoff_t start, struct cl_read_ahead * ra) [static]
Definition at line 1382 of file vvp_io.c.
References cl_io::ci_type, cl_io_slice::cis_io, CIT_FAULT, CIT_READ, cl2vvp_io(), CL_PAGE_EOF, cl_read_ahead::cra_end, ENTRY, ll_file_data::fd_flags, LL_FILE_GROUP_LOCKED, RETURN, unlikely, and vvp_io::vui_fd.
static int vvp_io_read_lock (const struct lu_env * env, const struct cl_io_slice * ios) [static]
Definition at line 599 of file vvp_io.c.
References cl_io::ci_rd, cl_io_slice::cis_io, CLM_READ, cl_io_rw_common::crw_count, cl_io_rw_common::crw_pos, ENTRY, RETURN, cl_io::u, and vvp_io_rw_lock().
static int vvp_io_read_start (const struct lu_env * env, const struct cl_io_slice * ios) [static]
Definition at line 782 of file vvp_io.c.
References can_populate_pages(), CDEBUG, CERROR, cl_io::ci_continue, cl_io::ci_nob, cl_io::ci_obj, cl_io::ci_rd, cl_io_slice::cis_io, cl2vvp_io(), cl_index(), CLOBINVRNT, cl_object::co_lu, D_INODE, D_VFSTRACE, ll_file_data::fd_file, IO_NORMAL, IO_SPLICE, LASSERT, LBUG, ll_i2info(), ll_i2sbi(), ll_ras_enter(), ll_rw_stats_tally(), ll_inode_info::lli_trunc_sem, LU_OBJECT_HEADER, READ, vvp_io::splice, vvp_io::u, cl_io::u, vvp_io::vui_fd, vvp_io::vui_io_subtype, vvp_io::vui_iocb, vvp_io::vui_iter, vvp_io::vui_ra_count, vvp_io::vui_ra_start, vvp_io::vui_ra_valid, vvp_io::vui_tot_count, vvp_object_inode(), vvp_object_invariant(), and vvp_prep_size().
static void vvp_io_rw_end (const struct lu_env * env, const struct cl_io_slice * ios) [static]
Definition at line 1147 of file vvp_io.c.
References cl_io_slice::cis_obj, cl2vvp_io(), IO_NORMAL, ll_i2info(), ll_inode_info::lli_trunc_sem, vvp_io::vui_io_subtype, and vvp_object_inode().
static int vvp_io_rw_lock (const struct lu_env * env, struct cl_io * io, enum cl_lock_mode mode, loff_t start, loff_t end) [static]
Definition at line 577 of file vvp_io.c.
References CEF_NONBLOCK, cl_io::ci_rw, cl_io::ci_type, CIT_READ, CIT_WRITE, cl_io_rw_common::crw_nonblock, ENTRY, LASSERT, RETURN, cl_io::u, vvp_env_io(), vvp_io_one_lock(), vvp_io_update_iov(), and vvp_mmap_locks().
Referenced by vvp_io_read_lock(), and vvp_io_write_lock().
static void vvp_io_setattr_end (const struct lu_env * env, const struct cl_io_slice * ios) [static]
Definition at line 751 of file vvp_io.c.
References cl_io::ci_obj, cl_io::ci_setattr, cl_io_slice::cis_io, cl_io_is_trunc(), inode_dio_write_done, ll_i2info(), ll_inode_info::lli_trunc_sem, cl_io::u, vvp_do_vmtruncate(), and vvp_object_inode().
static void vvp_io_setattr_fini (const struct lu_env * env, const struct cl_io_slice * ios) [static]
Definition at line 768 of file vvp_io.c.
References cl_io::ci_restore_needed, cl_io_slice::cis_io, cl_io_slice::cis_obj, ll_file_set_flag(), ll_i2info(), LLIF_DATA_MODIFIED, vvp_io_fini(), and vvp_object_inode().
static int vvp_io_setattr_iter_init (const struct lu_env * env, const struct cl_io_slice * ios) [static]
Definition at line 644 of file vvp_io.c.
static int vvp_io_setattr_lock (const struct lu_env * env, const struct cl_io_slice * ios) [static]
Implementation of cl_io_operations::cio_lock() method for CIT_SETATTR io.
Handles "lockless io" mode when extent locking is done by server.
Definition at line 655 of file vvp_io.c.
References __u64, CEF_DISCARD_DATA, cl_io::ci_setattr, cl_io_slice::cis_io, cl_io_is_trunc(), CLM_WRITE, OBD_OBJECT_EOF, TIMES_SET_FLAGS, cl_io::u, and vvp_io_one_lock().
static int vvp_io_setattr_start (const struct lu_env * env, const struct cl_io_slice * ios) [static]
Definition at line 732 of file vvp_io.c.
References cl_io::ci_obj, cl_io::ci_setattr, cl_io_slice::cis_io, cl_io_is_trunc(), inode_dio_wait, ll_i2info(), ll_inode_info::lli_trunc_sem, TIMES_SET_FLAGS, cl_io::u, vvp_io_setattr_time(), and vvp_object_inode().
static int vvp_io_setattr_time (const struct lu_env * env, const struct cl_io_slice * ios) [static]
Definition at line 707 of file vvp_io.c.
References CAT_ATIME, cl_attr::cat_atime, cl_attr::cat_ctime, CAT_CTIME, CAT_MTIME, cl_attr::cat_mtime, cl_io::ci_obj, cl_io::ci_setattr, cl_io_slice::cis_io, cl_object_attr_lock(), cl_object_attr_unlock(), cl_object_attr_update(), cl_io::u, and vvp_env_thread_attr().
Referenced by vvp_io_setattr_start().
static void vvp_io_update_iov (const struct lu_env * env, struct vvp_io * vio, struct cl_io * io) [static]
Definition at line 540 of file vvp_io.c.
References cl_io::ci_rw, cl_is_normalio(), cl_io_rw_common::crw_count, LASSERTF, size, cl_io::u, vvp_io::vui_iov_olen, vvp_io::vui_iter, and vvp_io::vui_tot_nrsegs.
Referenced by vvp_io_rw_lock().
int vvp_io_write_commit (const struct lu_env * env, struct cl_io * io)
Definition at line 968 of file vvp_io.c.
References CDEBUG, cl_io::ci_obj, cl_io_commit_async(), cl_io_is_mkwrite(), cl_page_discard(), cl_page_disown(), cl_page_list_del(), cl_page_list_fini(), cl_page_list_first(), cl_page_put(), cl_page_vmpage(), cl_page::cp_reference, D_VFSTRACE, ENTRY, ergo, LASSERT, LASSERTF, ll_merge_attr(), lu_ref_del(), page_list_sanity_check(), cl_page_list::pl_nr, RETURN, vvp_io::u, vvp_env_io(), vvp_io_commit_sync(), vvp_object_inode(), vvp_io::write, and write_commit_callback().
Referenced by ll_write_begin(), ll_write_end(), and vvp_io_write_start().
static void vvp_io_write_iter_fini (const struct lu_env * env, const struct cl_io_slice * ios) [static]
Definition at line 279 of file vvp_io.c.
References cl2vvp_io(), LASSERT, vvp_io::u, and vvp_io::write.
static int vvp_io_write_iter_init (const struct lu_env * env, const struct cl_io_slice * ios) [static]
Definition at line 266 of file vvp_io.c.
References cl2vvp_io(), cl_page_list_init(), vvp_io::u, and vvp_io::write.
static int vvp_io_write_lock (const struct lu_env * env, const struct cl_io_slice * ios) [static]
Definition at line 627 of file vvp_io.c.
References cl_io::ci_wr, cl_io_slice::cis_io, CLM_WRITE, end, OBD_OBJECT_EOF, start, cl_io::u, and vvp_io_rw_lock().
static int vvp_io_write_start (const struct lu_env * env, const struct cl_io_slice * ios) [static]
Definition at line 1048 of file vvp_io.c.
References can_populate_pages(), CDEBUG, cl_io::ci_continue, cl_io::ci_nob, cl_io::ci_obj, cl_io::ci_wr, cl_io_slice::cis_io, cl2vvp_io(), cl_io_is_append(), D_INODE, D_VFSTRACE, DFID, ENTRY, IO_NORMAL, LASSERT, ll_file_maxbytes(), ll_file_set_flag(), ll_get_fsname(), ll_i2info(), ll_i2sbi(), ll_inode2fid(), ll_merge_attr(), ll_rw_stats_tally(), ll_inode_info::lli_trunc_sem, LLIF_DATA_MODIFIED, LPU64, PFID, RETURN, vvp_io::u, cl_io::u, vvp_io::vui_fd, vvp_io::vui_io_subtype, vvp_io::vui_iocb, vvp_io::vui_iter, vvp_io_write_commit(), vvp_object_inode(), WRITE, and vvp_io::write.
static int vvp_mmap_locks (const struct lu_env * env, struct vvp_io * vio, struct cl_io * io) [static]
Definition at line 389 of file vvp_io.c.
References CDEBUG, CEF_MUST, cl_io::ci_type, CIT_READ, CIT_WRITE, cl_index(), cl_io_lock_alloc_add(), cl_is_normalio(), cl_lock_descr::cld_end, cl_lock_descr::cld_enq_flags, cl_lock_descr::cld_mode, cl_lock_descr::cld_obj, cl_lock_descr::cld_start, D_VFSTRACE, ldlm_extent::end, ENTRY, ldlm_policy_data::l_extent, LASSERT, ll_file_nolock(), ll_i2info(), ll_inode_info::lli_clob, our_vma(), policy_from_vma(), RETURN, ldlm_extent::start, vvp_thread_info::vti_descr, vvp_io::vui_iter, vvp_env_info(), and vvp_mode_from_vma().
Referenced by vvp_io_rw_lock().
static enum cl_lock_mode vvp_mode_from_vma (struct vm_area_struct * vma) [static]
Definition at line 377 of file vvp_io.c.
References CLM_READ, and CLM_WRITE.
Referenced by vvp_io_fault_lock(), and vvp_mmap_locks().
static void vvp_object_size_lock (struct cl_object * obj) [static]
Definition at line 106 of file vvp_io.c.
References cl_object_attr_lock(), ll_inode_size_lock(), and vvp_object_inode().
Referenced by vvp_prep_size().
static void vvp_object_size_unlock (struct cl_object * obj) [static]
Definition at line 114 of file vvp_io.c.
References cl_object_attr_unlock(), ll_inode_size_unlock(), and vvp_object_inode().
Referenced by vvp_prep_size().
static int vvp_prep_size (const struct lu_env * env, struct cl_object * obj, struct cl_io * io, loff_t start, size_t count, int * exceed) [static]
Helper function that if necessary adjusts file size (inode->i_size), when position at the offset pos is accessed.
File size can be arbitrary stale on a Lustre client, but client at least knows KMS. If accessed area is inside [0, KMS], set file size to KMS, otherwise glimpse file size.
Locking: i_size_lock is used to serialize changes to inode size and to protect consistency between inode size and cl_object attributes. cl_object_size_lock() protects consistency between cl_attr's of top-object and sub-objects.
Definition at line 133 of file vvp_io.c.
References __u64, cl_attr::cat_kms, CDEBUG, cl_glimpse_lock(), cl_object_attr_get(), cl_object::co_lu, D_VFSTRACE, DFID, LPU64, lu_object_fid(), PFID, size, vvp_env_thread_attr(), vvp_object_inode(), vvp_object_size_lock(), and vvp_object_size_unlock().
Referenced by vvp_io_fault_start(), and vvp_io_read_start().
static void write_commit_callback (const struct lu_env * env, struct cl_io * io, struct cl_page * page) [static]
Definition at line 928 of file vvp_io.c.
References cl_io_top(), cl_page_disown(), cl_page_put(), cl_page::cp_reference, cl_page::cp_vmpage, and lu_ref_del().
Referenced by vvp_io_write_commit().
Variable Documentation
struct cl_io_operations vvp_io_ops [static]
Definition at line 1402 of file vvp_io.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.