Lustre: lustre/llite/vvp_object.c File Reference
lustre/llite/vvp_object.c File Reference
#include <linux/user_namespace.h>
#include <libcfs/libcfs.h>
#include <obd.h>
#include "llite_internal.h"
#include "vvp_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LLITE
Functions
int vvp_object_invariant (const struct cl_object *obj)
static int vvp_object_print (const struct lu_env *env, void *cookie, lu_printer_t p, const struct lu_object *o)
static int vvp_attr_get (const struct lu_env *env, struct cl_object *obj, struct cl_attr *attr)
static int vvp_attr_update (const struct lu_env *env, struct cl_object *obj, const struct cl_attr *attr, unsigned valid)
static int vvp_conf_set (const struct lu_env *env, struct cl_object *obj, const struct cl_object_conf *conf)
static int vvp_prune (const struct lu_env *env, struct cl_object *obj)
static int vvp_object_glimpse (const struct lu_env *env, const struct cl_object *obj, struct ost_lvb *lvb)
static void vvp_req_attr_set (const struct lu_env *env, struct cl_object *obj, struct cl_req_attr *attr)
static int vvp_object_init0 (const struct lu_env *env, struct vvp_object *vob, const struct cl_object_conf *conf)
static int vvp_object_init (const struct lu_env *env, struct lu_object *obj, const struct lu_object_conf *conf)
static void vvp_object_free (const struct lu_env *env, struct lu_object *obj)
struct vvp_object * cl_inode2vvp (struct inode *inode)
struct lu_object * vvp_object_alloc (const struct lu_env *env, const struct lu_object_header *unused, struct lu_device *dev)
Variables
static struct cl_object_operations vvp_ops
static struct lu_object_operations vvp_lu_obj_ops
Define Documentation
#define DEBUG_SUBSYSTEM S_LLITE
Definition at line 41 of file vvp_object.c.
Function Documentation
struct vvp_object* cl_inode2vvp (struct inode * inode) [read]
Definition at line 277 of file vvp_object.c.
References cl_object::co_lu, LASSERT, ll_i2info(), ll_inode_info::lli_clob, lu_object::lo_header, lu2vvp(), lu_object_locate(), and vvp_device_type.
Referenced by dirty_cnt(), ll_vm_close(), ll_vm_open(), and vvp_vmpage_error().
static int vvp_attr_get (const struct lu_env * env, struct cl_object * obj, struct cl_attr * attr) [static]
Definition at line 89 of file vvp_object.c.
References cl_attr::cat_atime, cl_attr::cat_blocks, cl_attr::cat_ctime, cl_attr::cat_gid, cl_attr::cat_mtime, cl_attr::cat_size, cl_attr::cat_uid, from_kgid(), from_kuid(), LTIME_S, and vvp_object_inode().
static int vvp_attr_update (const struct lu_env * env, struct cl_object * obj, const struct cl_attr * attr, unsigned valid) [static]
Definition at line 111 of file vvp_object.c.
References cl_attr::cat_atime, CAT_ATIME, cl_attr::cat_ctime, CAT_CTIME, cl_attr::cat_gid, CAT_GID, cl_attr::cat_mtime, CAT_MTIME, cl_attr::cat_size, CAT_SIZE, cl_attr::cat_uid, CAT_UID, LTIME_S, make_kgid(), make_kuid(), and vvp_object_inode().
static int vvp_conf_set (const struct lu_env * env, struct cl_object * obj, const struct cl_object_conf * conf) [static]
Definition at line 134 of file vvp_object.c.
References CDEBUG, CL_LAYOUT_GEN_NONE, cl_object_conf::coc_inode, cl_object_conf::coc_opc, D_VFSTRACE, DFID, ll_i2info(), ll_layout_version_set(), ll_inode_info::lli_fid, OBD_OBJECT_EOF, OBJECT_CONF_INVALIDATE, and PFID.
struct lu_object* vvp_object_alloc (const struct lu_env * env, const struct lu_object_header * unused, struct lu_device * dev) [read]
Definition at line 290 of file vvp_object.c.
References cfs_size_round(), cl_object_header_init(), cl_object::co_lu, cl_object::co_ops, cl_object_header::coh_lu, cl_object_header::coh_page_bufsize, lu_object::lo_ops, lu_object_add_top(), lu_object_init(), OBD_SLAB_ALLOC_PTR_GFP, vvp_object::vob_cl, vvp_object::vob_header, and vvp_object_kmem.
static void vvp_object_free (const struct lu_env * env, struct lu_object * obj) [static]
Definition at line 262 of file vvp_object.c.
References lu_object::lo_header, lu2vvp(), lu_object_fini(), lu_object_header_fini(), OBD_SLAB_FREE_PTR, and vvp_object_kmem.
static int vvp_object_glimpse (const struct lu_env * env, const struct cl_object * obj, struct ost_lvb * lvb) [static]
Definition at line 176 of file vvp_object.c.
References dirty_cnt(), ENTRY, LTIME_S, ost_lvb::lvb_atime, ost_lvb::lvb_blocks, ost_lvb::lvb_ctime, ost_lvb::lvb_mtime, ost_lvb::lvb_size, RETURN, and vvp_object_inode().
static int vvp_object_init (const struct lu_env * env, struct lu_object * obj, const struct lu_object_conf * conf) [static]
Definition at line 239 of file vvp_object.c.
References cl_device::cd_lu_dev, lu_device::ld_ops, lu_device_operations::ldo_object_alloc, lu_object::lo_dev, lu_object::lo_header, lu2cl_conf(), lu2vvp(), lu2vvp_dev(), lu_object_add(), vvp_device::vdv_next, and vvp_object_init0().
static int vvp_object_init0 (const struct lu_env * env, struct vvp_object * vob, const struct cl_object_conf * conf) [static]
Definition at line 229 of file vvp_object.c.
References cl_object_page_init(), cl_object_conf::coc_inode, vvp_object::vob_cl, vvp_object::vob_inode, and vvp_object::vob_transient_pages.
Referenced by vvp_object_init().
int vvp_object_invariant (const struct cl_object * obj)
Definition at line 59 of file vvp_object.c.
References ll_i2info(), ll_inode_info::lli_clob, and vvp_object_inode().
Referenced by vvp_io_advance(), vvp_io_fault_end(), vvp_io_fault_fini(), vvp_io_fini(), vvp_io_init(), vvp_io_one_lock_index(), vvp_io_read_start(), vvp_lock_enqueue(), vvp_lock_init(), and vvp_page_init().
static int vvp_object_print (const struct lu_env * env, void * cookie, lu_printer_t p, const struct lu_object * o) [static]
Definition at line 68 of file vvp_object.c.
References DFID, ll_i2info(), ll_inode_info::lli_clob, ll_inode_info::lli_fid, lu2vvp(), PFID, vvp_object::vob_inode, vvp_object::vob_mmap_cnt, and vvp_object::vob_transient_pages.
static int vvp_prune (const struct lu_env * env, struct cl_object * obj) [static]
Definition at line 159 of file vvp_object.c.
References CDEBUG, CL_FSYNC_LOCAL, cl_sync_file_range(), cl_object::co_lu, D_VFSTRACE, DFID, ENTRY, lu_object_fid(), OBD_OBJECT_EOF, PFID, RETURN, and vvp_object_inode().
static void vvp_req_attr_set (const struct lu_env * env, struct cl_object * obj, struct cl_req_attr * attr) [static]
Definition at line 197 of file vvp_object.c.
References cl_req_attr::cra_flags, cl_req_attr::cra_jobid, cl_req_attr::cra_oa, cl_req_attr::cra_type, CRT_WRITE, ll_i2info(), LUSTRE_JOBID_SIZE, obdo::o_parent_oid, OBD_FAIL_CHECK, OBD_FAIL_LFSCK_INVALID_PFID, OBD_MD_FLCTIME, OBD_MD_FLGID, OBD_MD_FLMTIME, OBD_MD_FLTYPE, OBD_MD_FLUID, obdo_from_inode(), obdo_set_parent_fid(), and vvp_object_inode().
Variable Documentation
struct lu_object_operations vvp_lu_obj_ops [static]
Initial value:
 {
        .loo_object_init        = vvp_object_init,
        .loo_object_free        = vvp_object_free,
        .loo_object_print       = vvp_object_print,
}
Definition at line 271 of file vvp_object.c.
struct cl_object_operations vvp_ops [static]
Initial value:
 {
        .coo_page_init    = vvp_page_init,
        .coo_lock_init    = vvp_lock_init,
        .coo_io_init      = vvp_io_init,
        .coo_attr_get     = vvp_attr_get,
        .coo_attr_update  = vvp_attr_update,
        .coo_conf_set     = vvp_conf_set,
        .coo_prune        = vvp_prune,
        .coo_glimpse      = vvp_object_glimpse,
        .coo_req_attr_set = vvp_req_attr_set
}
Definition at line 217 of file vvp_object.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.