Lustre: lustre/llite/vvp_lock.c File Reference
lustre/llite/vvp_lock.c File Reference
#include <obd_support.h>
#include "vvp_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LLITE
Functions
static void vvp_lock_fini (const struct lu_env *env, struct cl_lock_slice *slice)
static int vvp_lock_enqueue (const struct lu_env *env, const struct cl_lock_slice *slice, struct cl_io *unused, struct cl_sync_io *anchor)
int vvp_lock_init (const struct lu_env *env, struct cl_object *obj, struct cl_lock *lock, const struct cl_io *unused)
Variables
static struct cl_lock_operations vvp_lock_ops
Define Documentation
#define DEBUG_SUBSYSTEM S_LLITE
Definition at line 41 of file vvp_lock.c.
Function Documentation
static int vvp_lock_enqueue (const struct lu_env * env, const struct cl_lock_slice * slice, struct cl_io * unused, struct cl_sync_io * anchor) [static]
Definition at line 59 of file vvp_lock.c.
References CLOBINVRNT, cl_lock_slice::cls_obj, and vvp_object_invariant().
static void vvp_lock_fini (const struct lu_env * env, struct cl_lock_slice * slice) [static]
Definition at line 52 of file vvp_lock.c.
References cl2vvp_lock(), OBD_SLAB_FREE_PTR, and vvp_lock_kmem.
int vvp_lock_init (const struct lu_env * env, struct cl_object * obj, struct cl_lock * lock, const struct cl_io * unused)
Definition at line 73 of file vvp_lock.c.
References cl_lock_slice_add(), CLOBINVRNT, OBD_SLAB_ALLOC_PTR_GFP, vvp_lock::vlk_cl, vvp_lock_kmem, and vvp_object_invariant().
Variable Documentation
struct cl_lock_operations vvp_lock_ops [static]
Initial value:
 {
        .clo_fini       = vvp_lock_fini,
        .clo_enqueue    = vvp_lock_enqueue,
}
Definition at line 68 of file vvp_lock.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.