Lustre: lustre/llite/vvp_dev.c File Reference
lustre/llite/vvp_dev.c File Reference
#include <obd.h>
#include "llite_internal.h"
#include "vvp_internal.h"
Data Structures
struct vvp_pgcache_id
Defines
#define DEBUG_SUBSYSTEM S_LLITE
#define PGC_OBJ_SHIFT (32 + 4)
#define PGC_DEPTH_SHIFT (32)
#define seq_page_flag(seq, page, flag, has_flags)
Functions
static void * ll_thread_key_init (const struct lu_context *ctx, struct lu_context_key *key)
static void ll_thread_key_fini (const struct lu_context *ctx, struct lu_context_key *key, void *data)
static void * vvp_session_key_init (const struct lu_context *ctx, struct lu_context_key *key)
static void vvp_session_key_fini (const struct lu_context *ctx, struct lu_context_key *key, void *data)
static void * vvp_thread_key_init (const struct lu_context *ctx, struct lu_context_key *key)
static void vvp_thread_key_fini (const struct lu_context *ctx, struct lu_context_key *key, void *data)
LU_TYPE_INIT_FINI (vvp,&ll_thread_key,&vvp_session_key,&vvp_thread_key)
static struct lu_device * vvp_device_free (const struct lu_env *env, struct lu_device *d)
static struct lu_device * vvp_device_alloc (const struct lu_env *env, struct lu_device_type *t, struct lustre_cfg *cfg)
static int vvp_device_init (const struct lu_env *env, struct lu_device *d, const char *name, struct lu_device *next)
static struct lu_device * vvp_device_fini (const struct lu_env *env, struct lu_device *d)
int vvp_global_init (void)
A mutex serializing calls to vvp_inode_fini() under extreme memory pressure, when environments cannot be allocated.
void vvp_global_fini (void)
int cl_sb_init (struct super_block *sb)
Common IO arguments for various VFS I/O interfaces.
int cl_sb_fini (struct super_block *sb)
static void vvp_pgcache_id_unpack (loff_t pos, struct vvp_pgcache_id *id)
static loff_t vvp_pgcache_id_pack (struct vvp_pgcache_id *id)
static int vvp_pgcache_obj_get (struct cfs_hash *hs, struct cfs_hash_bd *bd, struct hlist_node *hnode, void *data)
static struct cl_object * vvp_pgcache_obj (const struct lu_env *env, struct lu_device *dev, struct vvp_pgcache_id *id)
static loff_t vvp_pgcache_find (const struct lu_env *env, struct lu_device *dev, loff_t pos)
static void vvp_pgcache_page_show (const struct lu_env *env, struct seq_file *seq, struct cl_page *page)
static int vvp_pgcache_show (struct seq_file *f, void *v)
static void * vvp_pgcache_start (struct seq_file *f, loff_t *pos)
static void * vvp_pgcache_next (struct seq_file *f, void *v, loff_t *pos)
static void vvp_pgcache_stop (struct seq_file *f, void *v)
static int vvp_dump_pgcache_seq_open (struct inode *inode, struct file *filp)
Variables
static struct kmem_cache * ll_thread_kmem
struct kmem_cache * vvp_lock_kmem
struct kmem_cache * vvp_object_kmem
static struct kmem_cache * vvp_session_kmem
static struct kmem_cache * vvp_thread_kmem
static struct lu_kmem_descr vvp_caches []
struct lu_context_key ll_thread_key
struct lu_context_key vvp_session_key
struct lu_context_key vvp_thread_key
static struct lu_device_operations vvp_lu_ops
static struct
lu_device_type_operations vvp_device_type_ops
struct lu_device_type vvp_device_type
static struct seq_operations vvp_pgcache_ops
struct file_operations vvp_dump_pgcache_file_ops
Define Documentation
#define DEBUG_SUBSYSTEM S_LLITE
Definition at line 42 of file vvp_dev.c.
#define PGC_DEPTH_SHIFT (32)
Definition at line 386 of file vvp_dev.c.
Referenced by vvp_pgcache_id_pack(), and vvp_pgcache_id_unpack().
#define PGC_OBJ_SHIFT (32 + 4)
Definition at line 385 of file vvp_dev.c.
Referenced by vvp_pgcache_id_pack(), vvp_pgcache_id_unpack(), and vvp_pgcache_start().
#define seq_page_flag (seq, page, flag, has_flags)
Value:
do {                  \
        if (test_bit(PG_##flag, &(page)->flags)) {                  \
                seq_printf(seq, "%s"#flag, has_flags ? "|" : "");       \
                has_flags = 1;                                          \
        }                                                               \
} while(0)
Definition at line 501 of file vvp_dev.c.
Referenced by vvp_pgcache_page_show().
Function Documentation
int cl_sb_fini (struct super_block * sb)
Definition at line 337 of file vvp_dev.c.
References CERROR, cl_env_get(), cl_env_put(), cl_stack_fini(), ENTRY, ll_sb_info::ll_cl, ll_s2sbi, ll_sb_info::ll_site, and RETURN.
Referenced by client_common_put_super().
int cl_sb_init (struct super_block * sb)
Common IO arguments for various VFS I/O interfaces.
Definition at line 314 of file vvp_dev.c.
References cl2lu_dev(), cl_env_get(), cl_env_put(), cl_type_setup(), obd_export::exp_obd, lu_device::ld_site, ll_sb_info::ll_cl, ll_sb_info::ll_dt_exp, ll_s2sbi, ll_sb_info::ll_site, obd_device::obd_lu_dev, RETURN, and vvp_device_type.
Referenced by client_common_fill_super().
static void ll_thread_key_fini (const struct lu_context * ctx, struct lu_context_key * key, void * data) [static]
Definition at line 108 of file vvp_dev.c.
References ll_thread_kmem, and OBD_SLAB_FREE_PTR.
static void* ll_thread_key_init (const struct lu_context * ctx, struct lu_context_key * key) [static]
Definition at line 96 of file vvp_dev.c.
References ll_thread_kmem, and OBD_SLAB_ALLOC_PTR_GFP.
LU_TYPE_INIT_FINI (vvp , & ll_thread_key, & vvp_session_key, & vvp_thread_key)
static struct lu_device* vvp_device_alloc (const struct lu_env * env, struct lu_device_type * t, struct lustre_cfg * cfg) [static, read]
Definition at line 194 of file vvp_dev.c.
References cl_device::cd_lu_dev, CERROR, cl_device_init(), cl_site_init(), cl_site::cs_lu, ENTRY, LASSERT, lu_device::ld_ops, lu_device::ld_site, lu_site_init_finish(), OBD_ALLOC_PTR, OBD_FREE_PTR, RETURN, vvp_device::vdv_cl, vvp2lu_dev(), vvp_device_free(), and vvp_lu_ops.
static struct lu_device* vvp_device_fini (const struct lu_env * env, struct lu_device * d) [static, read]
Definition at line 252 of file vvp_dev.c.
References cl2lu_dev(), and lu2vvp_dev().
static struct lu_device* vvp_device_free (const struct lu_env * env, struct lu_device * d) [static, read]
Definition at line 177 of file vvp_dev.c.
References cl2lu_dev(), cl_device_fini(), cl_site_fini(), lu_device::ld_site, lu2cl_dev(), lu2cl_site(), lu2vvp_dev(), OBD_FREE_PTR, and vvp_device::vdv_next.
Referenced by vvp_device_alloc().
static int vvp_device_init (const struct lu_env * env, struct lu_device * d, const char * name, struct lu_device * next) [static]
Definition at line 231 of file vvp_dev.c.
References ENTRY, LASSERT, lu_device::ld_reference, lu_device::ld_site, lu_device::ld_type, lu_device_type::ldt_name, lu_device_type::ldt_ops, lu_device_type_operations::ldto_device_init, lu2cl_dev(), lu2vvp_dev(), lu_device_get(), lu_ref_add(), lu_site_init(), RETURN, and vvp_device::vdv_next.
static int vvp_dump_pgcache_seq_open (struct inode * inode, struct file * filp) [static]
Definition at line 639 of file vvp_dev.c.
References vvp_pgcache_ops.
void vvp_global_fini (void)
Definition at line 302 of file vvp_dev.c.
References lu_device_type_fini(), lu_kmem_fini(), and vvp_device_type.
Referenced by lustre_exit(), and lustre_init().
int vvp_global_init (void)
A mutex serializing calls to vvp_inode_fini() under extreme memory pressure, when environments cannot be allocated.
Definition at line 282 of file vvp_dev.c.
References lu_device_type_init(), lu_kmem_fini(), lu_kmem_init(), and vvp_device_type.
Referenced by lustre_init().
static loff_t vvp_pgcache_find (const struct lu_env * env, struct lu_device * dev, loff_t pos) [static]
Definition at line 459 of file vvp_dev.c.
References CFS_HASH_NHLIST, cl_object_put(), cl_object::co_lu, lu_device::ld_site, lu_object_ref_del(), vvp_pgcache_id::vpi_bucket, vvp_object_inode(), vvp_pgcache_id_pack(), vvp_pgcache_id_unpack(), and vvp_pgcache_obj().
Referenced by vvp_pgcache_next(), and vvp_pgcache_start().
static loff_t vvp_pgcache_id_pack (struct vvp_pgcache_id * id) [static]
Definition at line 406 of file vvp_dev.c.
References __u64, PGC_DEPTH_SHIFT, PGC_OBJ_SHIFT, vvp_pgcache_id::vpi_bucket, vvp_pgcache_id::vpi_depth, and vvp_pgcache_id::vpi_index.
Referenced by vvp_pgcache_find().
static void vvp_pgcache_id_unpack (loff_t pos, struct vvp_pgcache_id * id) [static]
Definition at line 397 of file vvp_dev.c.
References __u64, CLASSERT, PGC_DEPTH_SHIFT, and PGC_OBJ_SHIFT.
Referenced by vvp_pgcache_find(), and vvp_pgcache_show().
static void* vvp_pgcache_next (struct seq_file * f, void * v, loff_t * pos) [static]
Definition at line 610 of file vvp_dev.c.
References cl_device::cd_lu_dev, cl_env_get(), cl_env_put(), ll_sb_info::ll_cl, and vvp_pgcache_find().
static struct cl_object* vvp_pgcache_obj (const struct lu_env * env, struct lu_device * dev, struct vvp_pgcache_id * id) [static, read]
Definition at line 431 of file vvp_dev.c.
References cfs_hash_hlist_for_each(), LASSERT, lu_device::ld_site, lu_device::ld_type, lu_site::ls_obj_hash, lu2cl(), lu_device_is_cl(), lu_object_locate(), lu_object_put(), lu_object_ref_add(), lu_object_top(), vvp_pgcache_id::vpi_bucket, vvp_pgcache_id::vpi_curdep, vvp_pgcache_id::vpi_obj, and vvp_pgcache_obj_get().
Referenced by vvp_pgcache_find(), and vvp_pgcache_show().
static int vvp_pgcache_obj_get (struct cfs_hash * hs, struct cfs_hash_bd * bd, struct hlist_node * hnode, void * data) [static]
Definition at line 414 of file vvp_dev.c.
References cfs_hash_get(), cfs_hash_object(), lu_object_is_dying(), and vvp_pgcache_id::vpi_curdep.
Referenced by vvp_pgcache_obj().
static void vvp_pgcache_page_show (const struct lu_env * env, struct seq_file * seq, struct cl_page * page) [static]
Definition at line 508 of file vvp_dev.c.
References cl2vvp_page(), cl_page_at(), DFID, error, ll_inode2fid(), PFID, seq_page_flag, vvp_page::vpg_defer_uptodate, vvp_page::vpg_page, and vvp_device_type.
Referenced by vvp_pgcache_show().
static int vvp_pgcache_show (struct seq_file * f, void * v) [static]
Definition at line 537 of file vvp_dev.c.
References cl_device::cd_lu_dev, cl_env_get(), cl_env_put(), cl_object_put(), cl_page_put(), cl_vmpage_page(), cl_object::co_lu, DFID, ll_sb_info::ll_cl, lu_object_fid(), lu_object_ref_del(), PFID, vvp_object_inode(), vvp_pgcache_id_unpack(), vvp_pgcache_obj(), and vvp_pgcache_page_show().
static void* vvp_pgcache_start (struct seq_file * f, loff_t * pos) [static]
Definition at line 586 of file vvp_dev.c.
References cl_device::cd_lu_dev, cl_env_get(), cl_env_put(), cfs_hash::hs_cur_bits, ll_sb_info::ll_cl, ll_sb_info::ll_site, lu_site::ls_obj_hash, PGC_OBJ_SHIFT, and vvp_pgcache_find().
static void vvp_pgcache_stop (struct seq_file * f, void * v) [static]
Definition at line 627 of file vvp_dev.c.
static void vvp_session_key_fini (const struct lu_context * ctx, struct lu_context_key * key, void * data) [static]
Definition at line 133 of file vvp_dev.c.
References OBD_SLAB_FREE_PTR, and vvp_session_kmem.
static void* vvp_session_key_init (const struct lu_context * ctx, struct lu_context_key * key) [static]
Definition at line 122 of file vvp_dev.c.
References OBD_SLAB_ALLOC_PTR_GFP, and vvp_session_kmem.
static void vvp_thread_key_fini (const struct lu_context * ctx, struct lu_context_key * key, void * data) [static]
Definition at line 157 of file vvp_dev.c.
References OBD_SLAB_FREE_PTR, and vvp_thread_kmem.
static void* vvp_thread_key_init (const struct lu_context * ctx, struct lu_context_key * key) [static]
Definition at line 146 of file vvp_dev.c.
References OBD_SLAB_ALLOC_PTR_GFP, and vvp_thread_kmem.
Variable Documentation
struct lu_context_key ll_thread_key
Initial value:
 {
        .lct_tags = LCT_CL_THREAD,
        .lct_init = ll_thread_key_init,
        .lct_fini = ll_thread_key_fini,
}
Definition at line 116 of file vvp_dev.c.
Referenced by ll_env_info().
struct kmem_cache* ll_thread_kmem [static]
Definition at line 59 of file vvp_dev.c.
Referenced by ll_thread_key_fini(), and ll_thread_key_init().
struct lu_kmem_descr vvp_caches[] [static]
Initial value:
 {
        {
                .ckd_cache = &ll_thread_kmem,
                .ckd_name  = "ll_thread_kmem",
                .ckd_size  = sizeof(struct ll_thread_info),
        },
        {
                .ckd_cache = &vvp_lock_kmem,
                .ckd_name  = "vvp_lock_kmem",
                .ckd_size  = sizeof(struct vvp_lock),
        },
        {
                .ckd_cache = &vvp_object_kmem,
                .ckd_name  = "vvp_object_kmem",
                .ckd_size  = sizeof(struct vvp_object),
        },
        {
                .ckd_cache = &vvp_session_kmem,
                .ckd_name  = "vvp_session_kmem",
                .ckd_size  = sizeof (struct vvp_session)
        },
        {
                .ckd_cache = &vvp_thread_kmem,
                .ckd_name  = "vvp_thread_kmem",
                .ckd_size  = sizeof(struct vvp_thread_info),
        },
        {
                .ckd_cache = NULL
        }
}
Definition at line 65 of file vvp_dev.c.
struct lu_device_type vvp_device_type
Initial value:
 {
        .ldt_tags     = LU_DEVICE_CL,
        .ldt_name     = LUSTRE_VVP_NAME,
        .ldt_ops      = &vvp_device_type_ops,
        .ldt_ctx_tags = LCT_CL_THREAD
}
Definition at line 271 of file vvp_dev.c.
Referenced by cl_inode2vvp(), cl_sb_init(), vvp_global_fini(), vvp_global_init(), and vvp_pgcache_page_show().
struct lu_device_type_operations vvp_device_type_ops [static]
Initial value:
 {
        .ldto_init = vvp_type_init,
        .ldto_fini = vvp_type_fini,
        .ldto_start = vvp_type_start,
        .ldto_stop  = vvp_type_stop,
        .ldto_device_alloc      = vvp_device_alloc,
        .ldto_device_free       = vvp_device_free,
        .ldto_device_init       = vvp_device_init,
        .ldto_device_fini       = vvp_device_fini,
}
Definition at line 258 of file vvp_dev.c.
struct file_operations vvp_dump_pgcache_file_ops
Initial value:
 {
        .owner   = THIS_MODULE,
        .open    = vvp_dump_pgcache_seq_open,
        .read    = seq_read,
        .llseek  = seq_lseek,
        .release = seq_release,
}
Definition at line 653 of file vvp_dev.c.
struct kmem_cache* vvp_lock_kmem
Definition at line 60 of file vvp_dev.c.
Referenced by vvp_lock_fini(), and vvp_lock_init().
struct lu_device_operations vvp_lu_ops [static]
Initial value:
 {
        .ldo_object_alloc      = vvp_object_alloc
}
Definition at line 173 of file vvp_dev.c.
Referenced by vvp_device_alloc().
struct kmem_cache* vvp_object_kmem
Definition at line 61 of file vvp_dev.c.
Referenced by vvp_object_alloc(), and vvp_object_free().
struct seq_operations vvp_pgcache_ops [static]
Initial value:
 {
        .start = vvp_pgcache_start,
        .next  = vvp_pgcache_next,
        .stop  = vvp_pgcache_stop,
        .show  = vvp_pgcache_show
}
Definition at line 632 of file vvp_dev.c.
Referenced by vvp_dump_pgcache_seq_open().
struct lu_context_key vvp_session_key
Initial value:
 {
        .lct_tags = LCT_SESSION,
        .lct_init = vvp_session_key_init,
        .lct_fini = vvp_session_key_fini
}
Definition at line 140 of file vvp_dev.c.
Referenced by vvp_env_session().
struct kmem_cache* vvp_session_kmem [static]
Definition at line 62 of file vvp_dev.c.
Referenced by vvp_session_key_fini(), and vvp_session_key_init().
struct lu_context_key vvp_thread_key
Initial value:
 {
        .lct_tags = LCT_CL_THREAD,
        .lct_init = vvp_thread_key_init,
        .lct_fini = vvp_thread_key_fini,
}
Definition at line 164 of file vvp_dev.c.
Referenced by vvp_env_info().
struct kmem_cache* vvp_thread_kmem [static]
Definition at line 63 of file vvp_dev.c.
Referenced by vvp_thread_key_fini(), and vvp_thread_key_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.