Lustre: lustre/llite/vvp_page.c File Reference
lustre/llite/vvp_page.c File Reference
#include <linux/atomic.h>
#include <linux/bitops.h>
#include <linux/mm.h>
#include <linux/mutex.h>
#include <linux/page-flags.h>
#include <linux/pagemap.h>
#include <libcfs/libcfs.h>
#include "llite_internal.h"
#include "vvp_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LLITE
Functions
static void vvp_page_fini_common (struct vvp_page *vpg)
static void vvp_page_fini (const struct lu_env *env, struct cl_page_slice *slice)
static int vvp_page_own (const struct lu_env *env, const struct cl_page_slice *slice, struct cl_io *io, int nonblock)
static void vvp_page_assume (const struct lu_env *env, const struct cl_page_slice *slice, struct cl_io *unused)
static void vvp_page_unassume (const struct lu_env *env, const struct cl_page_slice *slice, struct cl_io *unused)
static void vvp_page_disown (const struct lu_env *env, const struct cl_page_slice *slice, struct cl_io *io)
static void vvp_page_discard (const struct lu_env *env, const struct cl_page_slice *slice, struct cl_io *unused)
static void vvp_page_delete (const struct lu_env *env, const struct cl_page_slice *slice)
static void vvp_page_export (const struct lu_env *env, const struct cl_page_slice *slice, int uptodate)
static int vvp_page_is_vmlocked (const struct lu_env *env, const struct cl_page_slice *slice)
static int vvp_page_prep_read (const struct lu_env *env, const struct cl_page_slice *slice, struct cl_io *unused)
static int vvp_page_prep_write (const struct lu_env *env, const struct cl_page_slice *slice, struct cl_io *unused)
static void vvp_vmpage_error (struct inode *inode, struct page *vmpage, int ioret)
Handles page transfer errors at VM level.
static void vvp_page_completion_read (const struct lu_env *env, const struct cl_page_slice *slice, int ioret)
static void vvp_page_completion_write (const struct lu_env *env, const struct cl_page_slice *slice, int ioret)
static int vvp_page_make_ready (const struct lu_env *env, const struct cl_page_slice *slice)
Implements cl_page_operations::cpo_make_ready() method.
static int vvp_page_print (const struct lu_env *env, const struct cl_page_slice *slice, void *cookie, lu_printer_t printer)
static int vvp_page_fail (const struct lu_env *env, const struct cl_page_slice *slice)
static int vvp_transient_page_prep (const struct lu_env *env, const struct cl_page_slice *slice, struct cl_io *unused)
static void vvp_transient_page_verify (const struct cl_page *page)
static int vvp_transient_page_own (const struct lu_env *env, const struct cl_page_slice *slice, struct cl_io *unused, int nonblock)
static void vvp_transient_page_assume (const struct lu_env *env, const struct cl_page_slice *slice, struct cl_io *unused)
static void vvp_transient_page_unassume (const struct lu_env *env, const struct cl_page_slice *slice, struct cl_io *unused)
static void vvp_transient_page_disown (const struct lu_env *env, const struct cl_page_slice *slice, struct cl_io *unused)
static void vvp_transient_page_discard (const struct lu_env *env, const struct cl_page_slice *slice, struct cl_io *unused)
static int vvp_transient_page_is_vmlocked (const struct lu_env *env, const struct cl_page_slice *slice)
static void vvp_transient_page_completion (const struct lu_env *env, const struct cl_page_slice *slice, int ioret)
static void vvp_transient_page_fini (const struct lu_env *env, struct cl_page_slice *slice)
int vvp_page_init (const struct lu_env *env, struct cl_object *obj, struct cl_page *page, pgoff_t index)
Variables
static struct cl_page_operations vvp_page_ops
static struct cl_page_operations vvp_transient_page_ops
Define Documentation
#define DEBUG_SUBSYSTEM S_LLITE
Definition at line 42 of file vvp_page.c.
Function Documentation
static void vvp_page_assume (const struct lu_env * env, const struct cl_page_slice * slice, struct cl_io * unused) [static]
Definition at line 109 of file vvp_page.c.
References cl2vm_page(), and LASSERT.
static void vvp_page_completion_read (const struct lu_env * env, const struct cl_page_slice * slice, int ioret) [static]
Definition at line 254 of file vvp_page.c.
References cl2vvp_page(), cl_page_export(), CL_PAGE_HEADER, cl_page::cp_obj, cl_page::cp_sync_io, cl_page_slice::cpl_page, D_PAGE, ENTRY, EXIT, LASSERT, ll_i2sbi(), ll_ra_count_put(), vvp_page::vpg_defer_uptodate, vvp_page::vpg_page, and vvp_object_inode().
static void vvp_page_completion_write (const struct lu_env * env, const struct cl_page_slice * slice, int ioret) [static]
Definition at line 283 of file vvp_page.c.
References cl2vvp_page(), CL_PAGE_HEADER, cl_page::cp_obj, cl_page::cp_sync_io, cl_page_slice::cpl_page, D_PAGE, ENTRY, ergo, EXIT, LASSERT, vvp_page::vpg_page, vvp_object_inode(), and vvp_vmpage_error().
static void vvp_page_delete (const struct lu_env * env, const struct cl_page_slice * slice) [static]
Definition at line 157 of file vvp_page.c.
References cl2vm_page(), cl_page::cp_ref, cl_page_slice::cpl_obj, cl_page_slice::cpl_page, LASSERT, LASSERTF, and vvp_object_inode().
static void vvp_page_discard (const struct lu_env * env, const struct cl_page_slice * slice, struct cl_io * unused) [static]
Definition at line 141 of file vvp_page.c.
References cl2vm_page(), cl2vvp_page(), LASSERT, ll_invalidate_page(), ll_ra_stats_inc(), RA_STAT_DISCARDED, vvp_page::vpg_defer_uptodate, and vvp_page::vpg_ra_used.
static void vvp_page_disown (const struct lu_env * env, const struct cl_page_slice * slice, struct cl_io * io) [static]
Definition at line 130 of file vvp_page.c.
References cl2vm_page(), and LASSERT.
static void vvp_page_export (const struct lu_env * env, const struct cl_page_slice * slice, int uptodate) [static]
Definition at line 183 of file vvp_page.c.
References cl2vm_page(), and LASSERT.
static int vvp_page_fail (const struct lu_env * env, const struct cl_page_slice * slice) [static]
Definition at line 373 of file vvp_page.c.
References LBUG.
static void vvp_page_fini (const struct lu_env * env, struct cl_page_slice * slice) [static]
Definition at line 69 of file vvp_page.c.
References cl2vvp_page(), cl_page_slice::cpl_page, LASSERT, vvp_page::vpg_page, and vvp_page_fini_common().
static void vvp_page_fini_common (struct vvp_page * vpg) [static]
Definition at line 61 of file vvp_page.c.
References LASSERT, and vvp_page::vpg_page.
Referenced by vvp_page_fini(), and vvp_transient_page_fini().
int vvp_page_init (const struct lu_env * env, struct cl_object * obj, struct cl_page * page, pgoff_t index)
Definition at line 517 of file vvp_page.c.
References cl2vvp(), cl_object_page_slice(), cl_page_slice_add(), CLOBINVRNT, cl_page::cp_ref, cl_page::cp_type, cl_page::cp_vmpage, CPT_CACHEABLE, vvp_object::vob_transient_pages, vvp_page::vpg_cl, vvp_page::vpg_page, and vvp_object_invariant().
static int vvp_page_is_vmlocked (const struct lu_env * env, const struct cl_page_slice * slice) [static]
Definition at line 197 of file vvp_page.c.
References cl2vm_page().
static int vvp_page_make_ready (const struct lu_env * env, const struct cl_page_slice * slice) [static]
Implements cl_page_operations::cpo_make_ready() method.
This is called to yank a page from the transfer cache and to send it out as a part of transfer. This function try-locks the page. If try-lock failed, page is owned by some concurrent IO, and should be skipped (this is bad, but hopefully rare situation, as it usually results in transfer being shorter than possible).
Return values:
0 success, page can be placed into transfer
-EAGAIN page is either used by concurrent IO has been truncated. Skip it.
Definition at line 322 of file vvp_page.c.
References cl2vm_page(), CL_PAGE_DEBUG, CL_PAGE_HEADER, cl_page::cp_state, cl_page_slice::cpl_page, CPS_CACHED, CPS_PAGEOUT, D_ERROR, D_PAGE, LASSERT, LBUG, and RETURN.
static int vvp_page_own (const struct lu_env * env, const struct cl_page_slice * slice, struct cl_io * io, int nonblock) [static]
Definition at line 83 of file vvp_page.c.
References cl2vvp_page(), LASSERT, unlikely, and vvp_page::vpg_page.
static int vvp_page_prep_read (const struct lu_env * env, const struct cl_page_slice * slice, struct cl_io * unused) [static]
Definition at line 203 of file vvp_page.c.
References cl2vm_page(), ENTRY, and RETURN.
static int vvp_page_prep_write (const struct lu_env * env, const struct cl_page_slice * slice, struct cl_io * unused) [static]
Definition at line 212 of file vvp_page.c.
References cl2vm_page(), and LASSERT.
static int vvp_page_print (const struct lu_env * env, const struct cl_page_slice * slice, void * cookie, lu_printer_t printer) [static]
Definition at line 349 of file vvp_page.c.
References cl2vvp_page(), list_empty(), LUSTRE_VVP_NAME, vvp_page::vpg_defer_uptodate, and vvp_page::vpg_page.
static void vvp_page_unassume (const struct lu_env * env, const struct cl_page_slice * slice, struct cl_io * unused) [static]
Definition at line 120 of file vvp_page.c.
References cl2vm_page(), and LASSERT.
static void vvp_transient_page_assume (const struct lu_env * env, const struct cl_page_slice * slice, struct cl_io * unused) [static]
Definition at line 430 of file vvp_page.c.
References cl_page_slice::cpl_page, and vvp_transient_page_verify().
static void vvp_transient_page_completion (const struct lu_env * env, const struct cl_page_slice * slice, int ioret) [static]
Definition at line 478 of file vvp_page.c.
References cl_page_slice::cpl_page, and vvp_transient_page_verify().
static void vvp_transient_page_discard (const struct lu_env * env, const struct cl_page_slice * slice, struct cl_io * unused) [static]
Definition at line 451 of file vvp_page.c.
References cl_page_delete(), cl_page_slice::cpl_page, and vvp_transient_page_verify().
static void vvp_transient_page_disown (const struct lu_env * env, const struct cl_page_slice * slice, struct cl_io * unused) [static]
Definition at line 444 of file vvp_page.c.
References cl_page_slice::cpl_page, and vvp_transient_page_verify().
static void vvp_transient_page_fini (const struct lu_env * env, struct cl_page_slice * slice) [static]
Definition at line 485 of file vvp_page.c.
References cl2vvp(), cl2vvp_page(), cl_page::cp_obj, cl_page_slice::cpl_page, vvp_object::vob_transient_pages, and vvp_page_fini_common().
static int vvp_transient_page_is_vmlocked (const struct lu_env * env, const struct cl_page_slice * slice) [static]
Definition at line 465 of file vvp_page.c.
References cl_page_slice::cpl_obj, and vvp_object_inode().
static int vvp_transient_page_own (const struct lu_env * env, const struct cl_page_slice * slice, struct cl_io * unused, int nonblock) [static]
Definition at line 422 of file vvp_page.c.
References cl_page_slice::cpl_page, and vvp_transient_page_verify().
static int vvp_transient_page_prep (const struct lu_env * env, const struct cl_page_slice * slice, struct cl_io * unused) [static]
Definition at line 409 of file vvp_page.c.
References ENTRY, and RETURN.
static void vvp_transient_page_unassume (const struct lu_env * env, const struct cl_page_slice * slice, struct cl_io * unused) [static]
Definition at line 437 of file vvp_page.c.
References cl_page_slice::cpl_page, and vvp_transient_page_verify().
static void vvp_transient_page_verify (const struct cl_page * page) [static]
Definition at line 418 of file vvp_page.c.
Referenced by vvp_transient_page_assume(), vvp_transient_page_completion(), vvp_transient_page_discard(), vvp_transient_page_disown(), vvp_transient_page_own(), and vvp_transient_page_unassume().
static void vvp_vmpage_error (struct inode * inode, struct page * vmpage, int ioret) [static]
Handles page transfer errors at VM level.
This takes inode as a separate argument, because inode on which error is to be set can be different from vmpage inode in case of direct-io.
Definition at line 232 of file vvp_page.c.
References cl_inode2vvp(), ll_dirty_page_discard_warn(), and vvp_object::vob_discard_page_warned.
Referenced by vvp_page_completion_write().
Variable Documentation
struct cl_page_operations vvp_page_ops [static]
Initial value:
 {
        .cpo_own           = vvp_page_own,
        .cpo_assume        = vvp_page_assume,
        .cpo_unassume      = vvp_page_unassume,
        .cpo_disown        = vvp_page_disown,
        .cpo_discard       = vvp_page_discard,
        .cpo_delete        = vvp_page_delete,
        .cpo_export        = vvp_page_export,
        .cpo_is_vmlocked   = vvp_page_is_vmlocked,
        .cpo_fini          = vvp_page_fini,
        .cpo_print         = vvp_page_print,
        .io = {
                [CRT_READ] = {
                        .cpo_prep       = vvp_page_prep_read,
                        .cpo_completion = vvp_page_completion_read,
                        .cpo_make_ready = vvp_page_fail,
                },
                [CRT_WRITE] = {
                        .cpo_prep       = vvp_page_prep_write,
                        .cpo_completion = vvp_page_completion_write,
                        .cpo_make_ready = vvp_page_make_ready,
                },
        },
}
Definition at line 384 of file vvp_page.c.
struct cl_page_operations vvp_transient_page_ops [static]
Initial value:
 {
        .cpo_own                = vvp_transient_page_own,
        .cpo_assume             = vvp_transient_page_assume,
        .cpo_unassume           = vvp_transient_page_unassume,
        .cpo_disown             = vvp_transient_page_disown,
        .cpo_discard            = vvp_transient_page_discard,
        .cpo_fini               = vvp_transient_page_fini,
        .cpo_is_vmlocked        = vvp_transient_page_is_vmlocked,
        .cpo_print              = vvp_page_print,
        .io = {
                [CRT_READ] = {
                        .cpo_prep       = vvp_transient_page_prep,
                        .cpo_completion = vvp_transient_page_completion,
                },
                [CRT_WRITE] = {
                        .cpo_prep       = vvp_transient_page_prep,
                        .cpo_completion = vvp_transient_page_completion,
                }
        }
}
Definition at line 496 of file vvp_page.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.