Lustre: libcfs/libcfs/watchdog.c File Reference
libcfs/libcfs/watchdog.c File Reference
#include <linux/kthread.h>
#include <libcfs/libcfs.h>
#include "tracefile.h"
Data Structures
struct lc_watchdog
Defines
#define DEBUG_SUBSYSTEM S_LNET
Functions
struct lc_watchdog * lc_watchdog_add (int timeout, void(*callback)(pid_t pid, void *), void *data)
void lc_watchdog_touch (struct lc_watchdog *lcw, int timeout)
void lc_watchdog_disable (struct lc_watchdog *lcw)
void lc_watchdog_delete (struct lc_watchdog *lcw)
Define Documentation
#define DEBUG_SUBSYSTEM S_LNET
Definition at line 41 of file watchdog.c.
Function Documentation
struct lc_watchdog* lc_watchdog_add (int timeout, void(*)(pid_t pid, void *) callback, void * data) [read]
Definition at line 492 of file watchdog.c.
Referenced by ptlrpc_main().
void lc_watchdog_delete (struct lc_watchdog * lcw)
Definition at line 511 of file watchdog.c.
Referenced by ptlrpc_main().
void lc_watchdog_disable (struct lc_watchdog * lcw)
Definition at line 506 of file watchdog.c.
Referenced by __attribute__().
void lc_watchdog_touch (struct lc_watchdog * lcw, int timeout)
Definition at line 501 of file watchdog.c.
Referenced by __attribute__().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.