Lustre: lustre/utils/gss/write_bytes.h File Reference
lustre/utils/gss/write_bytes.h File Reference
#include <stdlib.h>
#include <sys/types.h>
#include <netinet/in.h>
Defines
#define WRITE_BYTES(p, end, arg) write_bytes(p, end, &arg, sizeof(arg))
Functions
static int write_bytes (char **ptr, const char *end, const void *arg, int arg_len)
static int write_buffer (char **p, char *end, gss_buffer_desc *arg)
static int write_oid (char **p, char *end, gss_OID_desc *arg)
static int get_bytes (char **ptr, const char *end, void *res, int len)
static int get_buffer (char **ptr, const char *end, gss_buffer_desc *res)
static int xdr_get_u32 (u_int32_t **ptr, const u_int32_t *end, u_int32_t *res)
static int xdr_get_buffer (u_int32_t **ptr, const u_int32_t *end, gss_buffer_desc *res)
static int xdr_write_u32 (u_int32_t **ptr, const u_int32_t *end, u_int32_t arg)
static int xdr_write_buffer (u_int32_t **ptr, const u_int32_t *end, gss_buffer_desc *arg)
Define Documentation
#define WRITE_BYTES (p, end, arg) write_bytes(p, end, &arg, sizeof(arg))
Definition at line 51 of file write_bytes.h.
Referenced by do_downcall(), do_error_downcall(), error_kernel_key(), update_kernel_key(), write_buffer(), write_oid(), and xdr_write_u32().
Function Documentation
static int get_buffer (char ** ptr, const char * end, gss_buffer_desc * res) [inline, static]
Definition at line 93 of file write_bytes.h.
References get_bytes().
static int get_bytes (char ** ptr, const char * end, void * res, int len) [inline, static]
Definition at line 80 of file write_bytes.h.
Referenced by get_buffer(), and xdr_get_u32().
static int write_buffer (char ** p, char * end, gss_buffer_desc * arg) [inline, static]
Definition at line 54 of file write_bytes.h.
References WRITE_BYTES.
Referenced by do_downcall(), and update_kernel_key().
static int write_bytes (char ** ptr, const char * end, const void * arg, int arg_len) [inline, static]
Definition at line 39 of file write_bytes.h.
Referenced by xdr_write_buffer().
static int write_oid (char ** p, char * end, gss_OID_desc * arg) [inline, static]
Definition at line 67 of file write_bytes.h.
References WRITE_BYTES.
static int xdr_get_buffer (u_int32_t ** ptr, const u_int32_t * end, gss_buffer_desc * res) [inline, static]
Definition at line 121 of file write_bytes.h.
References xdr_get_u32().
static int xdr_get_u32 (u_int32_t ** ptr, const u_int32_t * end, u_int32_t * res) [inline, static]
Definition at line 112 of file write_bytes.h.
References get_bytes().
Referenced by xdr_get_buffer().
static int xdr_write_buffer (u_int32_t ** ptr, const u_int32_t * end, gss_buffer_desc * arg) [inline, static]
Definition at line 149 of file write_bytes.h.
References write_bytes(), and xdr_write_u32().
static int xdr_write_u32 (u_int32_t ** ptr, const u_int32_t * end, u_int32_t arg) [inline, static]
Definition at line 140 of file write_bytes.h.
References WRITE_BYTES.
Referenced by xdr_write_buffer().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.