Lustre: lustre/llite/xattr_cache.c File Reference
lustre/llite/xattr_cache.c File Reference
#include <linux/fs.h>
#include <linux/sched.h>
#include <linux/mm.h>
#include <obd_support.h>
#include <lustre_dlm.h>
#include <lustre_ver.h>
#include "llite_internal.h"
Data Structures
struct ll_xattr_entry
Defines
#define DEBUG_SUBSYSTEM S_LLITE
Functions
int ll_xattr_init (void)
void ll_xattr_fini (void)
static void ll_xattr_cache_init (struct ll_inode_info *lli)
Initializes xattr cache for an inode.
static int ll_xattr_cache_find (struct list_head *cache, const char *xattr_name, struct ll_xattr_entry **xattr)
This looks for a specific extended attribute.
static int ll_xattr_cache_add (struct list_head *cache, const char *xattr_name, const char *xattr_val, unsigned xattr_val_len)
This adds an xattr.
static int ll_xattr_cache_del (struct list_head *cache, const char *xattr_name)
This removes an extended attribute from cache.
static int ll_xattr_cache_list (struct list_head *cache, char *xld_buffer, int xld_size)
This iterates cached extended attributes.
static int ll_xattr_cache_valid (struct ll_inode_info *lli)
Check if the xattr cache is initialized (filled).
static int ll_xattr_cache_destroy_locked (struct ll_inode_info *lli)
This finalizes the xattr cache.
int ll_xattr_cache_destroy (struct inode *inode)
static int ll_xattr_find_get_lock (struct inode *inode, struct lookup_intent *oit, struct ptlrpc_request **req)
Match or enqueue a PR lock.
static int ll_xattr_cache_refill (struct inode *inode, struct lookup_intent *oit)
Refill the xattr cache.
or
Get an xattr value or list xattrs using the write-through cache.
Get the xattr value (has OBD_MD_FLXATTR set) of list xattr names (has OBD_MD_FLXATTRLS set) for . The resulting value/list is stored in if the former is not larger than .
Return values:
0 no error occured
-EPROTO network protocol error
-ENOMEM not enough memory for the cache
-ERANGE the buffer is not large enough
-ENODATA no such attr or the list is empty
int ll_xattr_cache_get (struct inode *inode, const char *name, char *buffer, size_t size, __u64 valid)
Variables
static struct kmem_cache * xattr_kmem
static struct lu_kmem_descr xattr_caches []
Define Documentation
#define DEBUG_SUBSYSTEM S_LLITE
Definition at line 33 of file xattr_cache.c.
Function Documentation
static int ll_xattr_cache_add (struct list_head * cache, const char * xattr_name, const char * xattr_val, unsigned xattr_val_len) [static]
This adds an xattr.
Add attr with value and length,
Return values:
0 success
-ENOMEM if no memory could be allocated for the cached attr
-EPROTO if duplicate xattr is being added
Definition at line 133 of file xattr_cache.c.
References CDEBUG, D_CACHE, ENTRY, list_add(), ll_xattr_cache_find(), OBD_ALLOC, OBD_FREE, OBD_SLAB_ALLOC_PTR_GFP, OBD_SLAB_FREE_PTR, RETURN, xattr_kmem, ll_xattr_entry::xe_list, ll_xattr_entry::xe_name, ll_xattr_entry::xe_namelen, ll_xattr_entry::xe_vallen, and ll_xattr_entry::xe_value.
Referenced by ll_xattr_cache_refill().
static int ll_xattr_cache_del (struct list_head * cache, const char * xattr_name) [static]
This removes an extended attribute from cache.
Remove attribute from .
Return values:
0 success
-ENODATA if is not cached
Definition at line 193 of file xattr_cache.c.
References CDEBUG, D_CACHE, ENTRY, list_del(), ll_xattr_cache_find(), OBD_FREE, OBD_SLAB_FREE_PTR, RETURN, xattr_kmem, ll_xattr_entry::xe_list, ll_xattr_entry::xe_name, ll_xattr_entry::xe_namelen, ll_xattr_entry::xe_vallen, and ll_xattr_entry::xe_value.
Referenced by ll_xattr_cache_destroy_locked().
int ll_xattr_cache_destroy (struct inode * inode)
Definition at line 286 of file xattr_cache.c.
References ENTRY, ll_i2info(), ll_xattr_cache_destroy_locked(), ll_inode_info::lli_xattrs_list_rwsem, and RETURN.
Referenced by ll_clear_inode(), and ll_md_blocking_ast().
static int ll_xattr_cache_destroy_locked (struct ll_inode_info * lli) [static]
This finalizes the xattr cache.
Free all xattr memory. is the inode info pointer.
Return values:
0 no error occured
Definition at line 271 of file xattr_cache.c.
References ENTRY, ll_file_clear_flag(), ll_xattr_cache_del(), ll_xattr_cache_valid(), ll_inode_info::lli_xattrs, LLIF_XATTR_CACHE, and RETURN.
Referenced by ll_xattr_cache_destroy(), and ll_xattr_cache_refill().
static int ll_xattr_cache_find (struct list_head * cache, const char * xattr_name, struct ll_xattr_entry ** xattr) [static]
This looks for a specific extended attribute.
Find in and return attribute in , for the NULL return the first cached .
Return values:
0 success
-ENODATA if not found
Definition at line 101 of file xattr_cache.c.
References CDEBUG, D_CACHE, ENTRY, list_for_each_entry, RETURN, ll_xattr_entry::xe_list, ll_xattr_entry::xe_name, ll_xattr_entry::xe_vallen, and ll_xattr_entry::xe_value.
Referenced by ll_xattr_cache_add(), ll_xattr_cache_del(), and ll_xattr_cache_get().
int ll_xattr_cache_get (struct inode * inode, const char * name, char * buffer, size_t size, __u64 valid)
Definition at line 522 of file xattr_cache.c.
References ENTRY, GOTO, IT_GETXATTR, lookup_intent::it_op, LASSERT, ll_i2info(), ll_i2sbi(), ll_stats_ops_tally(), ll_xattr_cache_find(), ll_xattr_cache_list(), ll_xattr_cache_refill(), ll_xattr_cache_valid(), ll_inode_info::lli_xattrs, ll_inode_info::lli_xattrs_list_rwsem, LPROC_LL_GETXATTR_HITS, OBD_MD_FLXATTR, OBD_MD_FLXATTRLS, RETURN, ll_xattr_entry::xe_vallen, and ll_xattr_entry::xe_value.
Referenced by ll_getxattr_common().
static void ll_xattr_cache_init (struct ll_inode_info * lli) [static]
Initializes xattr cache for an inode.
This initializes the xattr list and marks cache presence.
Definition at line 82 of file xattr_cache.c.
References ENTRY, INIT_LIST_HEAD, LASSERT, ll_file_set_flag(), ll_inode_info::lli_xattrs, and LLIF_XATTR_CACHE.
Referenced by ll_xattr_cache_refill().
static int ll_xattr_cache_list (struct list_head * cache, char * xld_buffer, int xld_size) [static]
This iterates cached extended attributes.
Walk over cached attributes in and fill in or only calculate buffer size if is NULL.
Return values:
>= 0 buffer list size
-ENODATA if the list cannot fit buffer
Definition at line 224 of file xattr_cache.c.
References CDEBUG, D_CACHE, ENTRY, list_for_each_entry_safe, RETURN, ll_xattr_entry::xe_list, ll_xattr_entry::xe_name, and ll_xattr_entry::xe_namelen.
Referenced by ll_xattr_cache_get().
static int ll_xattr_cache_refill (struct inode * inode, struct lookup_intent * oit) [static]
Refill the xattr cache.
Fetch and cache the whole of xattrs for , acquiring a read or a write xattr lock depending on operation in . Intent is dropped on exit unless the operation is setxattr.
Return values:
0 no error occured
-EPROTO network protocol error
-ENOMEM not enough memory for the cache
Definition at line 385 of file xattr_cache.c.
References CDEBUG, CERROR, D_CACHE, DFID, ENTRY, GOTO, lookup_intent::it_lock_handle, lookup_intent::it_lock_mode, lookup_intent::it_status, ldlm_lock_decref_and_cancel(), ll_i2info(), ll_i2sbi(), ll_inode2fid(), ll_intent_drop_lock(), ll_sb_info::ll_md_exp, ll_set_lock_data(), ll_stats_ops_tally(), ll_xattr_cache_add(), ll_xattr_cache_destroy_locked(), ll_xattr_cache_init(), ll_xattr_cache_valid(), ll_xattr_find_get_lock(), ll_inode_info::lli_xattrs, ll_inode_info::lli_xattrs_list_rwsem, LPROC_LL_GETXATTR_HITS, mdt_body::mbo_aclsize, mdt_body::mbo_eadatasize, mdt_body::mbo_max_mdsize, OBD_FAIL_CHECK, OBD_FAIL_LLITE_XATTR_ENOMEM, out_destroy(), PFID, ptlrpc_req_finished(), req_capsule_server_get(), req_capsule_server_sized_get(), RMF_EADATA, RMF_EAVALS, RMF_EAVALS_LENS, RMF_MDT_BODY, ptlrpc_request::rq_pill, unlikely, and XATTR_NAME_ACL_ACCESS.
Referenced by ll_xattr_cache_get().
static int ll_xattr_cache_valid (struct ll_inode_info * lli) [static]
Check if the xattr cache is initialized (filled).
Return values:
0 is not initialized
1 is initialized
Definition at line 259 of file xattr_cache.c.
References ll_file_test_flag(), and LLIF_XATTR_CACHE.
Referenced by ll_xattr_cache_destroy_locked(), ll_xattr_cache_get(), ll_xattr_cache_refill(), and ll_xattr_find_get_lock().
static int ll_xattr_find_get_lock (struct inode * inode, struct lookup_intent * oit, struct ptlrpc_request ** req) [static]
Match or enqueue a PR lock.
Find or request an LDLM lock with xattr data. Since LDLM does not provide API for atomic match_or_enqueue, the function handles it with a separate enq lock. If successful, the function exits with the list lock held.
Return values:
0 no error occured
-ENOMEM not enough memory
Definition at line 311 of file xattr_cache.c.
References CDEBUG, lustre_handle::cookie, D_CACHE, DFID, ldlm_enqueue_info::ei_type, ENTRY, lookup_intent::it_lock_handle, lookup_intent::it_lock_mode, lookup_intent::it_request, it_to_lock_mode(), LCK_PR, ldlm_completion_ast(), LDLM_IBITS, ll_finish_md_op_data(), ll_i2info(), ll_i2sbi(), ll_inode2fid(), ll_md_blocking_ast(), ll_sb_info::ll_md_exp, ll_prep_md_op_data(), ll_take_md_lock(), ll_xattr_cache_valid(), ll_inode_info::lli_xattrs_enq_lock, ll_inode_info::lli_xattrs_list_rwsem, LUSTRE_OPC_ANY, md_enqueue(), MDS_INODELOCK_XATTR, mode, OBD_MD_FLXATTR, OBD_MD_FLXATTRLS, md_op_data::op_data, md_op_data::op_valid, PFID, and RETURN.
Referenced by ll_xattr_cache_refill().
void ll_xattr_fini (void)
Definition at line 72 of file xattr_cache.c.
References lu_kmem_fini().
Referenced by lustre_exit().
int ll_xattr_init (void)
Definition at line 67 of file xattr_cache.c.
References lu_kmem_init().
Referenced by lustre_init().
Variable Documentation
struct lu_kmem_descr xattr_caches[] [static]
Initial value:
 {
        {
                .ckd_cache = &xattr_kmem,
                .ckd_name  = "xattr_kmem",
                .ckd_size  = sizeof(struct ll_xattr_entry)
        },
        {
                .ckd_cache = NULL
        }
}
Definition at line 56 of file xattr_cache.c.
struct kmem_cache* xattr_kmem [static]
Definition at line 55 of file xattr_cache.c.
Referenced by ll_xattr_cache_add(), and ll_xattr_cache_del().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.