Lustre: lustre/llite/xattr.c File Reference
lustre/llite/xattr.c File Reference
#include <linux/fs.h>
#include <linux/sched.h>
#include <linux/mm.h>
#include <linux/xattr.h>
#include <linux/selinux.h>
#include <obd_support.h>
#include <lustre_dlm.h>
#include <lustre_ver.h>
#include <lustre_eacl.h>
#include "llite_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LLITE
#define XATTR_NAME_IMA "security.ima"
#define XATTR_NAME_EVM "security.evm"
#define XATTR_USER_T (1)
#define XATTR_TRUSTED_T (2)
#define XATTR_SECURITY_T (3)
#define XATTR_ACL_ACCESS_T (4)
#define XATTR_ACL_DEFAULT_T (5)
#define XATTR_LUSTRE_T (6)
#define XATTR_OTHER_T (7)
Functions
static int get_xattr_type (const char *name)
static int xattr_type_filter (struct ll_sb_info *sbi, int xattr_type)
static int ll_setxattr_common (struct inode *inode, const char *name, const void *value, size_t size, int flags, __u64 valid)
static int get_hsm_state (struct inode *inode, __u32 *hus_states)
int ll_setxattr (struct dentry *dentry, const char *name, const void *value, size_t size, int flags)
int ll_removexattr (struct dentry *dentry, const char *name)
int ll_getxattr_common (struct inode *inode, const char *name, void *buffer, size_t size, __u64 valid)
static ssize_t ll_getxattr_lov (struct inode *inode, void *buf, size_t buf_size)
ssize_t ll_getxattr (struct dentry *dentry, const char *name, void *buf, size_t buf_size)
ssize_t ll_listxattr (struct dentry *dentry, char *buf, size_t buf_size)
Define Documentation
#define DEBUG_SUBSYSTEM S_LLITE
Definition at line 43 of file xattr.c.
#define XATTR_ACL_ACCESS_T (4)
Definition at line 63 of file xattr.c.
Referenced by get_xattr_type(), ll_getxattr_common(), ll_setxattr_common(), and xattr_type_filter().
#define XATTR_ACL_DEFAULT_T (5)
Definition at line 64 of file xattr.c.
Referenced by get_xattr_type(), ll_getxattr_common(), ll_setxattr_common(), and xattr_type_filter().
#define XATTR_LUSTRE_T (6)
Definition at line 65 of file xattr.c.
Referenced by get_xattr_type(), and ll_setxattr_common().
#define XATTR_NAME_EVM "security.evm"
Definition at line 57 of file xattr.c.
Referenced by ll_setxattr_common().
#define XATTR_NAME_IMA "security.ima"
Definition at line 54 of file xattr.c.
Referenced by ll_setxattr_common().
#define XATTR_OTHER_T (7)
Definition at line 66 of file xattr.c.
Referenced by get_xattr_type(), ll_getxattr_common(), and xattr_type_filter().
#define XATTR_SECURITY_T (3)
Definition at line 62 of file xattr.c.
Referenced by get_xattr_type(), ll_getxattr_common(), and ll_setxattr_common().
#define XATTR_TRUSTED_T (2)
Definition at line 61 of file xattr.c.
Referenced by get_xattr_type(), ll_setxattr_common(), and xattr_type_filter().
#define XATTR_USER_T (1)
Definition at line 60 of file xattr.c.
Referenced by get_xattr_type(), ll_getxattr_common(), ll_setxattr_common(), and xattr_type_filter().
Function Documentation
static int get_hsm_state (struct inode * inode, __u32 * hus_states) [static]
Definition at line 234 of file xattr.c.
References CDEBUG, D_VFSTRACE, hsm_user_state::hus_states, ll_finish_md_op_data(), ll_i2mdexp(), LL_IOC_HSM_STATE_GET, ll_prep_md_op_data(), LUSTRE_OPC_ANY, OBD_ALLOC_PTR, OBD_FREE_PTR, obd_iocontrol(), and md_op_data::op_data.
Referenced by ll_setxattr().
static int get_xattr_type (const char * name) [static]
Definition at line 69 of file xattr.c.
References XATTR_ACL_ACCESS_T, XATTR_ACL_DEFAULT_T, XATTR_LUSTRE_PREFIX, XATTR_LUSTRE_T, XATTR_OTHER_T, XATTR_SECURITY_PREFIX, XATTR_SECURITY_T, XATTR_TRUSTED_PREFIX, XATTR_TRUSTED_T, XATTR_USER_PREFIX, and XATTR_USER_T.
Referenced by ll_getxattr_common(), ll_listxattr(), and ll_setxattr_common().
ssize_t ll_getxattr (struct dentry * dentry, const char * name, void * buf, size_t buf_size)
Definition at line 592 of file xattr.c.
References CDEBUG, D_VFSTRACE, DFID, LASSERT, ll_getxattr_common(), ll_getxattr_lov(), ll_i2sbi(), ll_inode2fid(), ll_stats_ops_tally(), LPROC_LL_GETXATTR, OBD_MD_FLXATTR, PFID, XATTR_LUSTRE_LOV, and XATTR_NAME_LOV.
Referenced by ll_getparent().
int ll_getxattr_common (struct inode * inode, const char * name, void * buffer, size_t size, __u64 valid)
Definition at line 357 of file xattr.c.
References CDEBUG, CERROR, current_pid, D_VFSTRACE, DFID, ENTRY, EXIT, get_xattr_type(), GOTO, LASSERT, LCONSOLE_INFO, ll_sb_info::ll_et, ll_sb_info::ll_flags, ll_get_fsname(), ll_i2info(), ll_i2sbi(), ll_inode2fid(), ll_sb_info::ll_md_exp, ll_sb_info::ll_rct, LL_SBI_RMT_CLIENT, LL_SBI_USER_XATTR, ll_sb_info::ll_xattr_cache_enabled, ll_xattr_cache_get(), ll_inode_info::lli_lock, ll_inode_info::lli_posix_acl, mdt_body::mbo_eadatasize, md_getxattr(), OBD_MD_FLXATTRLS, PFID, posix_acl_to_xattr, ptlrpc_req_finished(), rmtacl_ctl_entry::rce_ops, req_capsule_server_get(), req_capsule_server_sized_get(), RETURN, RMF_EADATA, RMF_MDT_BODY, RMT_LGETFACL, RMT_LSETFACL, RMT_RGETFACL, RMT_RSETFACL, ptlrpc_request::rq_pill, unlikely, XATTR_ACL_ACCESS_T, XATTR_ACL_DEFAULT_T, XATTR_NAME_ACL_ACCESS, XATTR_OTHER_T, XATTR_SECURITY_T, xattr_type_filter(), and XATTR_USER_T.
Referenced by ll_getxattr(), and ll_listxattr().
static ssize_t ll_getxattr_lov (struct inode * inode, void * buf, size_t buf_size) [static]
Definition at line 521 of file xattr.c.
References cl_layout::cl_buf, cl_env_get(), cl_env_put(), cl_object_layout_get(), cl_layout::cl_size, GOTO, LASSERT, lu_buf::lb_buf, ll_dir_getstripe(), ll_i2info(), ll_inode_info::lli_clob, lov_mds_md, ptlrpc_req_finished(), and RETURN.
Referenced by ll_getxattr(), and ll_listxattr().
ssize_t ll_listxattr (struct dentry * dentry, char * buf, size_t buf_size)
Definition at line 613 of file xattr.c.
References CDEBUG, D_VFSTRACE, DFID, get_xattr_type(), ll_getxattr_common(), ll_getxattr_lov(), ll_i2sbi(), ll_inode2fid(), ll_stats_ops_tally(), LPROC_LL_LISTXATTR, OBD_MD_FLXATTRLS, PFID, RETURN, strnlen, XATTR_LUSTRE_LOV, and xattr_type_filter().
int ll_removexattr (struct dentry * dentry, const char * name)
Definition at line 342 of file xattr.c.
References CDEBUG, D_VFSTRACE, DFID, LASSERT, ll_i2sbi(), ll_inode2fid(), ll_setxattr_common(), ll_stats_ops_tally(), LPROC_LL_REMOVEXATTR, OBD_MD_FLXATTRRM, and PFID.
int ll_setxattr (struct dentry * dentry, const char * name, const void * value, size_t size, int flags)
Definition at line 265 of file xattr.c.
References __u64, CDEBUG, D_VFSTRACE, DFID, FMODE_WRITE, get_hsm_state(), HS_ARCHIVED, HS_NONE, LASSERT, ll_dir_setstripe(), ll_i2sbi(), ll_inode2fid(), ll_lov_setstripe_ea_info(), ll_lov_user_md_size(), ll_setxattr_common(), ll_stats_ops_tally(), LOV_PATTERN_F_RELEASED, lov_user_md, LPROC_LL_SETXATTR, OBD_MD_FLXATTR, PFID, RETURN, state, XATTR_LUSTRE_PREFIX, XATTR_NAME_LINK, XATTR_NAME_LMA, and XATTR_TRUSTED_PREFIX.
Referenced by ll_init_security().
static int ll_setxattr_common (struct inode * inode, const char * name, const void * value, size_t size, int flags, __u64 valid) [static]
Definition at line 115 of file xattr.c.
References current_pid, eacl_entry::ee_acl, ENTRY, get_xattr_type(), LASSERT, LCONSOLE_INFO, le32_to_cpu, ll_sb_info::ll_et, ll_sb_info::ll_flags, ll_i2sbi(), ll_i2suppgid(), ll_inode2fid(), ll_sb_info::ll_md_exp, ll_sb_info::ll_rct, LL_SBI_RMT_CLIENT, LL_SBI_USER_XATTR, md_setxattr(), OBD_MD_FLXATTR, ptlrpc_req_finished(), rmtacl_ctl_entry::rce_ops, RETURN, RMT_LSETFACL, RMT_RSETFACL, unlikely, XATTR_ACL_ACCESS_T, XATTR_ACL_DEFAULT_T, XATTR_LUSTRE_T, XATTR_NAME_EVM, XATTR_NAME_HSM, XATTR_NAME_IMA, XATTR_NAME_LOV, XATTR_SECURITY_T, XATTR_TRUSTED_T, xattr_type_filter(), and XATTR_USER_T.
Referenced by ll_removexattr(), and ll_setxattr().
static int xattr_type_filter (struct ll_sb_info * sbi, int xattr_type) [static]
Definition at line 97 of file xattr.c.
References CFS_CAP_SYS_ADMIN, cfs_capable(), ll_sb_info::ll_flags, LL_SBI_ACL, LL_SBI_USER_XATTR, XATTR_ACL_ACCESS_T, XATTR_ACL_DEFAULT_T, XATTR_OTHER_T, XATTR_TRUSTED_T, and XATTR_USER_T.
Referenced by ll_getxattr_common(), ll_listxattr(), and ll_setxattr_common().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.