Lustre: lustre/llite/xattr_security.c File Reference
lustre/llite/xattr_security.c File Reference
#include <linux/security.h>
#include <linux/selinux.h>
#include <linux/xattr.h>
#include "llite_internal.h"
Functions
int ll_init_security (struct dentry *dentry, struct inode *inode, struct inode *dir)
Function Documentation
int ll_init_security (struct dentry * dentry, struct inode * inode, struct inode * dir)
Definition at line 112 of file xattr_security.c.
References GOTO, ll_security_inode_init_security, ll_setxattr(), name, OBD_ALLOC, OBD_FREE, strlcat(), strlcpy(), and XATTR_SECURITY_PREFIX.
Referenced by ll_create_it(), ll_dir_setdirstripe(), and ll_new_node().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.