Lustre: API to operate on locks from actual LDLM users.
API to operate on locks from actual LDLM users.
[Lustre Distributed Lock Manager]
These are typically used by client and server (*_local versions) to obtain and release locks.
Functions
int ldlm_cli_enqueue (struct obd_export *exp, struct ptlrpc_request **reqp, struct ldlm_enqueue_info *einfo, const struct ldlm_res_id *res_id, union ldlm_policy_data const *policy, __u64 *flags, void *lvb, __u32 lvb_len, enum lvb_type lvb_type, struct lustre_handle *lockh, int async)
Client-side lock enqueue.
int ldlm_prep_enqueue_req (struct obd_export *exp, struct ptlrpc_request *req, struct list_head *cancels, int count)
int ldlm_prep_elc_req (struct obd_export *exp, struct ptlrpc_request *req, int version, int opc, int canceloff, struct list_head *cancels, int count)
Cancel LRU locks and pack them into the enqueue request.
struct ptlrpc_request * ldlm_enqueue_pack (struct obd_export *exp, int lvb_len)
int ldlm_handle_enqueue0 (struct ldlm_namespace *ns, struct ptlrpc_request *req, const struct ldlm_request *dlm_req, const struct ldlm_callback_suite *cbs)
int ldlm_cli_enqueue_fini (struct obd_export *exp, struct ptlrpc_request *req, enum ldlm_type type, __u8 with_policy, enum ldlm_mode mode, __u64 *flags, void *lvb, __u32 lvb_len, const struct lustre_handle *lockh, int rc)
Finishing portion of client lock enqueue code.
int ldlm_cli_enqueue_local (struct ldlm_namespace *ns, const struct ldlm_res_id *res_id, enum ldlm_type type, union ldlm_policy_data *policy, enum ldlm_mode mode, __u64 *flags, ldlm_blocking_callback blocking, ldlm_completion_callback completion, ldlm_glimpse_callback glimpse, void *data, __u32 lvb_len, enum lvb_type lvb_type, const __u64 *client_cookie, struct lustre_handle *lockh)
Enqueue a local lock (typically on a server).
int ldlm_cli_convert (const struct lustre_handle *lockh, int new_mode, __u32 *flags)
int ldlm_cli_update_pool (struct ptlrpc_request *req)
Update client's OBD pool related fields with new SLV and Limit from req.
int ldlm_cli_cancel (const struct lustre_handle *lockh, enum ldlm_cancel_flags cancel_flags)
Client side lock cancel.
int ldlm_cli_cancel_unused (struct ldlm_namespace *, const struct ldlm_res_id *, enum ldlm_cancel_flags flags, void *opaque)
Cancel all locks on a namespace (or a specific resource, if given) that have 0 readers/writers.
int ldlm_cli_cancel_unused_resource (struct ldlm_namespace *ns, const struct ldlm_res_id *res_id, union ldlm_policy_data *policy, enum ldlm_mode mode, enum ldlm_cancel_flags flags, void *opaque)
Cancel all locks on a resource that have 0 readers/writers.
int ldlm_cli_cancel_req (struct obd_export *exp, struct list_head *head, int count, enum ldlm_cancel_flags flags)
Prepare and send a batched cancel RPC.
int ldlm_cancel_resource_local (struct ldlm_resource *res, struct list_head *cancels, union ldlm_policy_data *policy, enum ldlm_mode mode, __u64 lock_flags, enum ldlm_cancel_flags cancel_flags, void *opaque)
Find and cancel locally unused locks found on resource, matched to the given policy, mode.
int ldlm_cli_cancel_list_local (struct list_head *cancels, int count, enum ldlm_cancel_flags flags)
Locally cancel up to count locks in list cancels.
int ldlm_cli_cancel_list (struct list_head *head, int count, struct ptlrpc_request *req, enum ldlm_cancel_flags flags)
Cancel client-side locks from a list and send/prepare cancel RPCs to the server.
Detailed Description
These are typically used by client and server (*_local versions) to obtain and release locks.
Function Documentation
int ldlm_cancel_resource_local (struct ldlm_resource * res, struct list_head * cancels, union ldlm_policy_data * policy, enum ldlm_mode mode, __u64 lock_flags, enum ldlm_cancel_flags cancel_flags, void * opaque)
Find and cancel locally unused locks found on resource, matched to the given policy, mode.
GET the found locks and add them into the cancels list.
Definition at line 1854 of file ldlm_request.c.
References ldlm_lock::l_ast_data, ldlm_lock::l_bl_ast, ldlm_lock::l_flags, ldlm_lock::l_granted_mode, ldlm_lock::l_policy_data, ldlm_lock::l_readers, ldlm_lock::l_res_link, ldlm_lock::l_resource, ldlm_cli_cancel_list_local(), LDLM_FL_CANCELING, LDLM_FL_CBPENDING, ldlm_resource::lr_granted, and ldlm_resource::lr_type.
Referenced by ldlm_cli_cancel_unused_resource().
{
        struct ldlm_lock *lock;
        int count = 0;
        ENTRY;
        lock_res(res);
        list_for_each_entry(lock, &res->lr_granted, l_res_link) {
                if (opaque != NULL && lock->l_ast_data != opaque) {
                        LDLM_ERROR(lock, "data %p doesn't match opaque %p",
                                   lock->l_ast_data, opaque);
                        //LBUG();
                        continue;
                }
                if (lock->l_readers || lock->l_writers)
                        continue;
                /* If somebody is already doing CANCEL, or blocking AST came,
                 * skip this lock. */
                if (ldlm_is_bl_ast(lock) || ldlm_is_canceling(lock))
                        continue;
                if (lockmode_compat(lock->l_granted_mode, mode))
                        continue;
                /* If policy is given and this is IBITS lock, add to list only
                 * those locks that match by policy. */
                if (policy && (lock->l_resource->lr_type == LDLM_IBITS) &&
                    !(lock->l_policy_data.l_inodebits.bits &
                      policy->l_inodebits.bits))
                        continue;
                /* See CBPENDING comment in ldlm_cancel_lru */
                lock->l_flags |= LDLM_FL_CBPENDING | LDLM_FL_CANCELING |
                                 lock_flags;
                LASSERT(list_empty(&lock->l_bl_ast));
                list_add(&lock->l_bl_ast, cancels);
                LDLM_LOCK_GET(lock);
                count++;
        }
        unlock_res(res);
        RETURN(ldlm_cli_cancel_list_local(cancels, count, cancel_flags));
}
int ldlm_cli_cancel (const struct lustre_handle * lockh, enum ldlm_cancel_flags cancel_flags)
Client side lock cancel.
Lock must not have any readers or writers by this time.
Definition at line 1345 of file ldlm_request.c.
References ldlm_lock::l_bl_ast, ldlm_lock::l_conn_export, ldlm_cli_cancel_list(), LDLM_DEBUG_NOLOCK, LDLM_FL_LOCAL_ONLY, LDLM_LOCK_RELEASE, lock_res_and_lock(), and unlock_res_and_lock().
Referenced by ldlm_blocking_ast_nocheck().
{
        struct obd_export *exp;
        enum ldlm_lru_flags lru_flags;
        int avail, count = 1;
        __u64 rc = 0;
        struct ldlm_namespace *ns;
        struct ldlm_lock *lock;
        struct list_head cancels = LIST_HEAD_INIT(cancels);
        ENTRY;
        lock = ldlm_handle2lock_long(lockh, 0);
        if (lock == NULL) {
                LDLM_DEBUG_NOLOCK("lock is already being destroyed");
                RETURN(0);
        }
        lock_res_and_lock(lock);
        /* Lock is being canceled and the caller doesn't want to wait */
        if (ldlm_is_canceling(lock) && (cancel_flags & LCF_ASYNC)) {
                unlock_res_and_lock(lock);
                LDLM_LOCK_RELEASE(lock);
                RETURN(0);
        }
        ldlm_set_canceling(lock);
        unlock_res_and_lock(lock);
        rc = ldlm_cli_cancel_local(lock);
        if (rc == LDLM_FL_LOCAL_ONLY || cancel_flags & LCF_LOCAL) {
                LDLM_LOCK_RELEASE(lock);
                RETURN(0);
        }
        /* Even if the lock is marked as LDLM_FL_BL_AST, this is a LDLM_CANCEL
         * RPC which goes to canceld portal, so we can cancel other LRU locks
         * here and send them all as one LDLM_CANCEL RPC. */
        LASSERT(list_empty(&lock->l_bl_ast));
        list_add(&lock->l_bl_ast, &cancels);
        exp = lock->l_conn_export;
        if (exp_connect_cancelset(exp)) {
                avail = ldlm_format_handles_avail(class_exp2cliimp(exp),
                                                  &RQF_LDLM_CANCEL,
                                                  RCL_CLIENT, 0);
                LASSERT(avail > 0);
                ns = ldlm_lock_to_ns(lock);
                lru_flags = ns_connect_lru_resize(ns) ?
                        LDLM_LRU_FLAG_LRUR : LDLM_LRU_FLAG_AGED;
                count += ldlm_cancel_lru_local(ns, &cancels, 0, avail - 1,
                                               LCF_BL_AST, lru_flags);
        }
        ldlm_cli_cancel_list(&cancels, count, NULL, cancel_flags);
        RETURN(0);
}
int ldlm_cli_cancel_list (struct list_head * cancels, int count, struct ptlrpc_request * req, enum ldlm_cancel_flags flags)
Cancel client-side locks from a list and send/prepare cancel RPCs to the server.
If req is NULL, send CANCEL request to server with handles of locks in the cancels. If EARLY_CANCEL is not supported, send CANCEL requests separately per lock. If req is not NULL, put handles of locks in cancels into the request buffer at the offset off. Destroy cancels at the end.
Definition at line 1917 of file ldlm_request.c.
References ldlm_lock::l_bl_ast, ldlm_lock::l_conn_export, and ldlm_cli_cancel_req().
Referenced by ldlm_cli_cancel(), ldlm_cli_cancel_list_local(), ldlm_cli_cancel_unused_resource(), and ldlm_prep_elc_req().
{
        struct ldlm_lock *lock;
        int res = 0;
        ENTRY;
        if (list_empty(cancels) || count == 0)
                RETURN(0);
        /* XXX: requests (both batched and not) could be sent in parallel.
         * Usually it is enough to have just 1 RPC, but it is possible that
         * there are too many locks to be cancelled in LRU or on a resource.
         * It would also speed up the case when the server does not support
         * the feature. */
        while (count > 0) {
                LASSERT(!list_empty(cancels));
                lock = list_entry(cancels->next, struct ldlm_lock,
                                      l_bl_ast);
                LASSERT(lock->l_conn_export);
                if (exp_connect_cancelset(lock->l_conn_export)) {
                        res = count;
                        if (req)
                                ldlm_cancel_pack(req, cancels, count);
                        else
                                res = ldlm_cli_cancel_req(lock->l_conn_export,
                                                          cancels, count,
                                                          flags);
                } else {
                        res = ldlm_cli_cancel_req(lock->l_conn_export,
                                                  cancels, 1, flags);
                }
                if (res < 0) {
                        CDEBUG_LIMIT(res == -ESHUTDOWN ? D_DLMTRACE : D_ERROR,
                                     "ldlm_cli_cancel_list: %d\n", res);
                        res = count;
                }
                count -= res;
                ldlm_lock_list_put(cancels, l_bl_ast, res);
        }
        LASSERT(count == 0);
        RETURN(0);
}
int ldlm_cli_cancel_list_local (struct list_head * cancels, int count, enum ldlm_cancel_flags cancel_flags)
Locally cancel up to count locks in list cancels.
Return the number of cancelled locks.
Definition at line 1407 of file ldlm_request.c.
References ldlm_lock::l_bl_ast, ldlm_cli_cancel_list(), LDLM_FL_BL_AST, LDLM_FL_LOCAL_ONLY, ldlm_lock_cancel(), and LDLM_LOCK_RELEASE.
Referenced by ldlm_cancel_resource_local().
{
        struct list_head head = LIST_HEAD_INIT(head);
        struct ldlm_lock *lock, *next;
        int left = 0, bl_ast = 0;
        __u64 rc;
        left = count;
        list_for_each_entry_safe(lock, next, cancels, l_bl_ast) {
                if (left-- == 0)
                        break;
                if (cancel_flags & LCF_LOCAL) {
                        rc = LDLM_FL_LOCAL_ONLY;
                        ldlm_lock_cancel(lock);
                } else {
                        rc = ldlm_cli_cancel_local(lock);
                }
                /* Until we have compound requests and can send LDLM_CANCEL
                 * requests batched with generic RPCs, we need to send cancels
                 * with the LDLM_FL_BL_AST flag in a separate RPC from
                 * the one being generated now. */
                if (!(cancel_flags & LCF_BL_AST) && (rc == LDLM_FL_BL_AST)) {
                        LDLM_DEBUG(lock, "Cancel lock separately");
                        list_del_init(&lock->l_bl_ast);
                        list_add(&lock->l_bl_ast, &head);
                        bl_ast++;
                        continue;
                }
                if (rc == LDLM_FL_LOCAL_ONLY) {
                        /* CANCEL RPC should not be sent to server. */
                        list_del_init(&lock->l_bl_ast);
                        LDLM_LOCK_RELEASE(lock);
                        count--;
                }
        }
        if (bl_ast > 0) {
                count -= bl_ast;
                ldlm_cli_cancel_list(&head, bl_ast, NULL, 0);
        }
        RETURN(count);
}
int ldlm_cli_cancel_req (struct obd_export * exp, struct list_head * cancels, int count, enum ldlm_cancel_flags flags)
Prepare and send a batched cancel RPC.
It will include count lock handles of locks given in cancels list.
Definition at line 1185 of file ldlm_request.c.
References obd_export::exp_obd, obd_import::imp_generation, lu_device::ld_obd, lu_device::ld_site, lu_site::ls_top_dev, ptlrpc_at_set_req_timeout(), ptlrpc_queue_wait(), ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpcd_add_req(), req_capsule_filled_sizes(), req_capsule_set_size(), ptlrpc_request::rq_import, and ptlrpc_request::rq_pill.
Referenced by ldlm_cli_cancel_list().
{
        struct ptlrpc_request *req = NULL;
        struct obd_import *imp;
        int free, sent = 0;
        int rc = 0;
        ENTRY;
        LASSERT(exp != NULL);
        LASSERT(count > 0);
        CFS_FAIL_TIMEOUT(OBD_FAIL_LDLM_PAUSE_CANCEL, cfs_fail_val);
        if (CFS_FAIL_CHECK(OBD_FAIL_LDLM_CANCEL_RACE))
                RETURN(count);
        free = ldlm_format_handles_avail(class_exp2cliimp(exp),
                                         &RQF_LDLM_CANCEL, RCL_CLIENT, 0);
        if (count > free)
                count = free;
        while (1) {
                imp = class_exp2cliimp(exp);
                if (imp == NULL || imp->imp_invalid) {
                        CDEBUG(D_DLMTRACE,
                               "skipping cancel on invalid import %p\n", imp);
                        RETURN(count);
                }
                req = ptlrpc_request_alloc(imp, &RQF_LDLM_CANCEL);
                if (req == NULL)
                        GOTO(out, rc = -ENOMEM);
                req_capsule_filled_sizes(&req->rq_pill, RCL_CLIENT);
                req_capsule_set_size(&req->rq_pill, &RMF_DLM_REQ, RCL_CLIENT,
                                     ldlm_request_bufsize(count, LDLM_CANCEL));
                rc = ptlrpc_request_pack(req, LUSTRE_DLM_VERSION, LDLM_CANCEL);
                if (rc) {
                        ptlrpc_request_free(req);
                        GOTO(out, rc);
                }
                /* If OSP want cancel cross-MDT lock, let's not block it in
                 * in recovery, otherwise the lock will not released, if
                 * the remote target is also in recovery, and it also need
                 * this lock, it might cause deadlock. */
                if (exp_connect_flags(exp) & OBD_CONNECT_MDS_MDS &&
                    exp->exp_obd->obd_lu_dev != NULL &&
                    exp->exp_obd->obd_lu_dev->ld_site != NULL) {
                        struct lu_device *top_dev;
                        top_dev = exp->exp_obd->obd_lu_dev->ld_site->ls_top_dev;
                        if (top_dev != NULL &&
                            top_dev->ld_obd->obd_recovering)
                                req->rq_allow_replay = 1;
                }
                req->rq_request_portal = LDLM_CANCEL_REQUEST_PORTAL;
                req->rq_reply_portal = LDLM_CANCEL_REPLY_PORTAL;
                ptlrpc_at_set_req_timeout(req);
                ldlm_cancel_pack(req, cancels, count);
                ptlrpc_request_set_replen(req);
                if (flags & LCF_ASYNC) {
                        ptlrpcd_add_req(req);
                        sent = count;
                        GOTO(out, 0);
                }
                rc = ptlrpc_queue_wait(req);
                if (rc == LUSTRE_ESTALE) {
                        CDEBUG(D_DLMTRACE, "client/server (nid %s) "
                               "out of sync -- not fatal\n",
                               libcfs_nid2str(req->rq_import->
                                              imp_connection->c_peer.nid));
                        rc = 0;
                } else if (rc == -ETIMEDOUT && /* check there was no reconnect*/
                           req->rq_import_generation == imp->imp_generation) {
                        ptlrpc_req_finished(req);
                        continue;
                } else if (rc != ELDLM_OK) {
                        /* -ESHUTDOWN is common on umount */
                        CDEBUG_LIMIT(rc == -ESHUTDOWN ? D_DLMTRACE : D_ERROR,
                                     "Got rc %d from cancel RPC: "
                                     "canceling anyway\n", rc);
                        break;
                }
                sent = count;
                break;
        }
        ptlrpc_req_finished(req);
        EXIT;
out:
        return sent ? sent : rc;
}
int ldlm_cli_cancel_unused (struct ldlm_namespace * ns, const struct ldlm_res_id * res_id, enum ldlm_cancel_flags flags, void * opaque)
Cancel all locks on a namespace (or a specific resource, if given) that have 0 readers/writers.
If flags & LCF_LOCAL, throw the locks away without trying to notify the server.
Definition at line 2029 of file ldlm_request.c.
References ldlm_cli_cancel_unused_resource(), and ldlm_namespace::ns_rs_hash.
{
        struct ldlm_cli_cancel_arg arg = {
                .lc_flags       = flags,
                .lc_opaque      = opaque,
        };
        ENTRY;
        if (ns == NULL)
                RETURN(ELDLM_OK);
        if (res_id != NULL) {
                RETURN(ldlm_cli_cancel_unused_resource(ns, res_id, NULL,
                                                       LCK_MINMODE, flags,
                                                       opaque));
        } else {
                cfs_hash_for_each_nolock(ns->ns_rs_hash,
                                         ldlm_cli_hash_cancel_unused, &arg, 0);
                RETURN(ELDLM_OK);
        }
}
int ldlm_cli_cancel_unused_resource (struct ldlm_namespace * ns, const struct ldlm_res_id * res_id, union ldlm_policy_data * policy, enum ldlm_mode mode, enum ldlm_cancel_flags flags, void * opaque)
Cancel all locks on a resource that have 0 readers/writers.
If flags & LDLM_FL_LOCAL_ONLY, throw the locks away without trying to notify the server.
Definition at line 1971 of file ldlm_request.c.
References ldlm_cancel_resource_local(), ldlm_cli_cancel_list(), and ldlm_resource_get().
Referenced by ldlm_cli_cancel_unused().
{
        struct ldlm_resource *res;
        struct list_head cancels = LIST_HEAD_INIT(cancels);
        int count;
        int rc;
        ENTRY;
        res = ldlm_resource_get(ns, NULL, res_id, 0, 0);
        if (IS_ERR(res)) {
                /* This is not a problem. */
                CDEBUG(D_INFO, "No resource "LPU64"\n", res_id->name[0]);
                RETURN(0);
        }
        LDLM_RESOURCE_ADDREF(res);
        count = ldlm_cancel_resource_local(res, &cancels, policy, mode,
                                           0, flags | LCF_BL_AST, opaque);
        rc = ldlm_cli_cancel_list(&cancels, count, NULL, flags);
        if (rc != ELDLM_OK)
                CERROR("canceling unused lock "DLDLMRES": rc = %d\n",
                       PLDLMRES(res), rc);
        LDLM_RESOURCE_DELREF(res);
        ldlm_resource_putref(res);
        RETURN(0);
}
int ldlm_cli_enqueue (struct obd_export * exp, struct ptlrpc_request ** reqp, struct ldlm_enqueue_info * einfo, const struct ldlm_res_id * res_id, union ldlm_policy_data const * policy, __u64 * flags, void * lvb, __u32 lvb_len, enum lvb_type lvb_type , struct lustre_handle * lockh, int async)
Client-side lock enqueue.
If a request has some specific initialisation it is passed in reqp, otherwise it is created in ldlm_cli_enqueue.
Supports sync and async requests, pass async flag accordingly. If a request was created in ldlm_cli_enqueue and it is the async request, pass it to the caller in reqp.
Definition at line 869 of file ldlm_request.c.
References ldlm_enqueue_info::ei_cb_bl, ldlm_enqueue_info::ei_cb_cp, ldlm_enqueue_info::ei_cb_gl, ldlm_enqueue_info::ei_cbdata, ldlm_enqueue_info::ei_mode, obd_export::exp_obd, ldlm_lock::l_blocking_ast, ldlm_lock::l_conn_export, ldlm_lock::l_export, ldlm_lock::l_flags, ldlm_lock::l_last_activity, ldlm_lock::l_policy_data, ldlm_lock::l_req_extent, ldlm_cli_enqueue_fini(), LDLM_FL_EXCL, LDLM_FL_NO_LRU, LDLM_FL_REPLAY, ldlm_lock2desc(), ldlm_lock2handle(), LDLM_LOCK_RELEASE, ptlrpc_queue_wait(), ptlrpc_req_finished(), ptlrpc_request_alloc_pack(), req_capsule_client_get(), req_capsule_extend(), req_capsule_get_size(), req_capsule_set_size(), and ptlrpc_request::rq_pill.
{
        struct ldlm_namespace *ns;
        struct ldlm_lock      *lock;
        struct ldlm_request   *body;
        int                    is_replay = *flags & LDLM_FL_REPLAY;
        int                    req_passed_in = 1;
        int                    rc, err;
        struct ptlrpc_request *req;
        ENTRY;
        LASSERT(exp != NULL);
        ns = exp->exp_obd->obd_namespace;
        /* If we're replaying this lock, just check some invariants.
         * If we're creating a new lock, get everything all setup nice. */
        if (is_replay) {
                lock = ldlm_handle2lock_long(lockh, 0);
                LASSERT(lock != NULL);
                LDLM_DEBUG(lock, "client-side enqueue START");
                LASSERT(exp == lock->l_conn_export);
        } else {
                const struct ldlm_callback_suite cbs = {
                        .lcs_completion = einfo->ei_cb_cp,
                        .lcs_blocking   = einfo->ei_cb_bl,
                        .lcs_glimpse    = einfo->ei_cb_gl
                };
                lock = ldlm_lock_create(ns, res_id, einfo->ei_type,
                                        einfo->ei_mode, &cbs, einfo->ei_cbdata,
                                        lvb_len, lvb_type);
                if (IS_ERR(lock))
                        RETURN(PTR_ERR(lock));
                /* for the local lock, add the reference */
                ldlm_lock_addref_internal(lock, einfo->ei_mode);
                ldlm_lock2handle(lock, lockh);
                if (policy != NULL)
                        lock->l_policy_data = *policy;
                if (einfo->ei_type == LDLM_EXTENT) {
                        /* extent lock without policy is a bug */
                        if (policy == NULL)
                                LBUG();
                        lock->l_req_extent = policy->l_extent;
                }
                LDLM_DEBUG(lock, "client-side enqueue START, flags "LPX64,
                           *flags);
        }
        lock->l_conn_export = exp;
        lock->l_export = NULL;
        lock->l_blocking_ast = einfo->ei_cb_bl;
        lock->l_flags |= (*flags & (LDLM_FL_NO_LRU | LDLM_FL_EXCL));
        lock->l_last_activity = cfs_time_current_sec();
        /* lock not sent to server yet */
        if (reqp == NULL || *reqp == NULL) {
                req = ptlrpc_request_alloc_pack(class_exp2cliimp(exp),
                                                &RQF_LDLM_ENQUEUE,
                                                LUSTRE_DLM_VERSION,
                                                LDLM_ENQUEUE);
                if (req == NULL) {
                        failed_lock_cleanup(ns, lock, einfo->ei_mode);
                        LDLM_LOCK_RELEASE(lock);
                        RETURN(-ENOMEM);
                }
                req_passed_in = 0;
                if (reqp)
                        *reqp = req;
        } else {
                int len;
                req = *reqp;
                len = req_capsule_get_size(&req->rq_pill, &RMF_DLM_REQ,
                                           RCL_CLIENT);
                LASSERTF(len >= sizeof(*body), "buflen[%d] = %d, not %d\n",
                         DLM_LOCKREQ_OFF, len, (int)sizeof(*body));
        }
        /* Dump lock data into the request buffer */
        body = req_capsule_client_get(&req->rq_pill, &RMF_DLM_REQ);
        ldlm_lock2desc(lock, &body->lock_desc);
        body->lock_flags = ldlm_flags_to_wire(*flags);
        body->lock_handle[0] = *lockh;
        /* Continue as normal. */
        if (!req_passed_in) {
                if (lvb_len > 0)
                        req_capsule_extend(&req->rq_pill,
                                           &RQF_LDLM_ENQUEUE_LVB);
                req_capsule_set_size(&req->rq_pill, &RMF_DLM_LVB, RCL_SERVER,
                                     lvb_len);
                ptlrpc_request_set_replen(req);
        }
        if (async) {
                LASSERT(reqp != NULL);
                RETURN(0);
        }
        LDLM_DEBUG(lock, "sending request");
        rc = ptlrpc_queue_wait(req);
        err = ldlm_cli_enqueue_fini(exp, req, einfo->ei_type, policy ? 1 : 0,
                                    einfo->ei_mode, flags, lvb, lvb_len,
                                    lockh, rc);
        /* If ldlm_cli_enqueue_fini did not find the lock, we need to free
         * one reference that we took */
        if (err == -ENOLCK)
                LDLM_LOCK_RELEASE(lock);
        else
                rc = err;
        if (!req_passed_in && req != NULL) {
                ptlrpc_req_finished(req);
                if (reqp)
                        *reqp = NULL;
        }
        RETURN(rc);
}
int ldlm_cli_enqueue_fini (struct obd_export * exp, struct ptlrpc_request * req, enum ldlm_type type, __u8 with_policy, enum ldlm_mode mode, __u64 * flags, void * lvb, __u32 lvb_len, const struct lustre_handle * lockh, int rc)
Finishing portion of client lock enqueue code.
Called after receiving reply from server.
Definition at line 541 of file ldlm_request.c.
References obd_export::exp_lock_hash, obd_export::exp_obd, ldlm_lock::l_completion_ast, ldlm_lock::l_exp_hash, ldlm_lock::l_flags, ldlm_lock::l_granted_mode, ldlm_lock::l_lvb_len, ldlm_lock::l_policy_data, ldlm_lock::l_remote_handle, ldlm_lock::l_req_mode, ldlm_lock::l_resource, ldlm_convert_policy_to_local(), LDLM_FL_AST_SENT, LDLM_FL_BL_AST, LDLM_FL_CBPENDING, LDLM_FL_INHERIT_MASK, LDLM_FL_LOCK_CHANGED, LDLM_FL_REPLAY, ldlm_lock_change_resource(), LDLM_LOCK_PUT, LDLM_LOCK_RELEASE, lock_res_and_lock(), ldlm_resource::lr_name, ldlm_resource::lr_type, req_capsule_get_size(), req_capsule_server_get(), ptlrpc_request::rq_pill, and unlock_res_and_lock().
Referenced by ldlm_cli_enqueue().
{
        struct ldlm_namespace *ns = exp->exp_obd->obd_namespace;
        int is_replay = *flags & LDLM_FL_REPLAY;
        struct ldlm_lock *lock;
        struct ldlm_reply *reply;
        int cleanup_phase = 1;
        ENTRY;
        lock = ldlm_handle2lock(lockh);
        /* ldlm_cli_enqueue is holding a reference on this lock. */
        if (!lock) {
                LASSERT(type == LDLM_FLOCK);
                RETURN(-ENOLCK);
        }
        LASSERTF(ergo(lvb_len != 0, lvb_len == lock->l_lvb_len),
                 "lvb_len = %d, l_lvb_len = %d\n", lvb_len, lock->l_lvb_len);
        if (rc != ELDLM_OK) {
                LASSERT(!is_replay);
                LDLM_DEBUG(lock, "client-side enqueue END (%s)",
                           rc == ELDLM_LOCK_ABORTED ? "ABORTED" : "FAILED");
                if (rc != ELDLM_LOCK_ABORTED)
                        GOTO(cleanup, rc);
        }
        /* Before we return, swab the reply */
        reply = req_capsule_server_get(&req->rq_pill, &RMF_DLM_REP);
        if (reply == NULL)
                GOTO(cleanup, rc = -EPROTO);
        if (lvb_len > 0) {
                int size = 0;
                size = req_capsule_get_size(&req->rq_pill, &RMF_DLM_LVB,
                                            RCL_SERVER);
                if (size < 0) {
                        LDLM_ERROR(lock, "Fail to get lvb_len, rc = %d", size);
                        GOTO(cleanup, rc = size);
                } else if (unlikely(size > lvb_len)) {
                        LDLM_ERROR(lock, "Replied LVB is larger than "
                                   "expectation, expected = %d, replied = %d",
                                   lvb_len, size);
                        GOTO(cleanup, rc = -EINVAL);
                }
                lvb_len = size;
        }
        if (rc == ELDLM_LOCK_ABORTED) {
                if (lvb_len > 0 && lvb != NULL)
                        rc = ldlm_fill_lvb(lock, &req->rq_pill, RCL_SERVER,
                                           lvb, lvb_len);
                GOTO(cleanup, rc = rc ? : ELDLM_LOCK_ABORTED);
        }
        /* lock enqueued on the server */
        cleanup_phase = 0;
        lock_res_and_lock(lock);
        /* Key change rehash lock in per-export hash with new key */
        if (exp->exp_lock_hash) {
                /* In the function below, .hs_keycmp resolves to
                 * ldlm_export_lock_keycmp() */
                /* coverity[overrun-buffer-val] */
                cfs_hash_rehash_key(exp->exp_lock_hash,
                                    &lock->l_remote_handle,
                                    &reply->lock_handle,
                                    &lock->l_exp_hash);
        } else {
                lock->l_remote_handle = reply->lock_handle;
        }
        *flags = ldlm_flags_from_wire(reply->lock_flags);
        lock->l_flags |= ldlm_flags_from_wire(reply->lock_flags &
                                              LDLM_FL_INHERIT_MASK);
        unlock_res_and_lock(lock);
        CDEBUG(D_INFO, "local: %p, remote cookie: "LPX64", flags: "LPX64"\n",
               lock, reply->lock_handle.cookie, *flags);
        /* If enqueue returned a blocked lock but the completion handler has
         * already run, then it fixed up the resource and we don't need to do it
         * again. */
        if ((*flags) & LDLM_FL_LOCK_CHANGED) {
                int newmode = reply->lock_desc.l_req_mode;
                LASSERT(!is_replay);
                if (newmode && newmode != lock->l_req_mode) {
                        LDLM_DEBUG(lock, "server returned different mode %s",
                                   ldlm_lockname[newmode]);
                        lock->l_req_mode = newmode;
                }
                if (!ldlm_res_eq(&reply->lock_desc.l_resource.lr_name,
                                 &lock->l_resource->lr_name)) {
                        CDEBUG(D_INFO, "remote intent success, locking "DLDLMRES
                                       " instead of "DLDLMRES"\n",
                               PLDLMRES(&reply->lock_desc.l_resource),
                               PLDLMRES(lock->l_resource));
                        rc = ldlm_lock_change_resource(ns, lock,
                                        &reply->lock_desc.l_resource.lr_name);
                        if (rc || lock->l_resource == NULL)
                                GOTO(cleanup, rc = -ENOMEM);
                        LDLM_DEBUG(lock, "client-side enqueue, new resource");
                }
                if (with_policy)
                        if (!(type == LDLM_IBITS &&
                              !(exp_connect_flags(exp) & OBD_CONNECT_IBITS)))
                                /* We assume lock type cannot change on server*/
                                ldlm_convert_policy_to_local(exp,
                                                lock->l_resource->lr_type,
                                                &reply->lock_desc.l_policy_data,
                                                &lock->l_policy_data);
                if (type != LDLM_PLAIN)
                        LDLM_DEBUG(lock,"client-side enqueue, new policy data");
        }
        if ((*flags) & LDLM_FL_AST_SENT) {
                lock_res_and_lock(lock);
                lock->l_flags |= LDLM_FL_CBPENDING | LDLM_FL_BL_AST;
                unlock_res_and_lock(lock);
                LDLM_DEBUG(lock, "enqueue reply includes blocking AST");
        }
        /* If the lock has already been granted by a completion AST, don't
         * clobber the LVB with an older one. */
        if (lvb_len > 0) {
                /* We must lock or a racing completion might update lvb without
                 * letting us know and we'll clobber the correct value.
                 * Cannot unlock after the check either, a that still leaves
                 * a tiny window for completion to get in */
                lock_res_and_lock(lock);
                if (lock->l_req_mode != lock->l_granted_mode)
                        rc = ldlm_fill_lvb(lock, &req->rq_pill, RCL_SERVER,
                                           lock->l_lvb_data, lvb_len);
                unlock_res_and_lock(lock);
                if (rc < 0) {
                        cleanup_phase = 1;
                        GOTO(cleanup, rc);
                }
        }
        if (!is_replay) {
                rc = ldlm_lock_enqueue(ns, &lock, NULL, flags);
                if (lock->l_completion_ast != NULL) {
                        int err = lock->l_completion_ast(lock, *flags, NULL);
                        if (!rc)
                                rc = err;
                        if (rc)
                                cleanup_phase = 1;
                }
        }
        if (lvb_len > 0 && lvb != NULL) {
                /* Copy the LVB here, and not earlier, because the completion
                 * AST (if any) can override what we got in the reply */
                memcpy(lvb, lock->l_lvb_data, lvb_len);
        }
        LDLM_DEBUG(lock, "client-side enqueue END");
        EXIT;
cleanup:
        if (cleanup_phase == 1 && rc)
                failed_lock_cleanup(ns, lock, mode);
        /* Put lock 2 times, the second reference is held by ldlm_cli_enqueue */
        LDLM_LOCK_PUT(lock);
        LDLM_LOCK_RELEASE(lock);
        return rc;
}
int ldlm_prep_elc_req (struct obd_export * exp, struct ptlrpc_request * req, int version, int opc, int canceloff, struct list_head * cancels, int count)
Cancel LRU locks and pack them into the enqueue request.
Pack there the given count locks in cancels.
This is to be called by functions preparing their own requests that might contain lists of locks to cancel in addition to actual operation that needs to be performed.
Definition at line 762 of file ldlm_request.c.
References obd_export::exp_obd, ldlm_cli_cancel_list(), ptlrpc_request_pack(), req_capsule_client_get(), req_capsule_filled_sizes(), req_capsule_set_size(), and ptlrpc_request::rq_pill.
        {
        struct ldlm_namespace   *ns = exp->exp_obd->obd_namespace;
        struct req_capsule      *pill = &req->rq_pill;
        struct ldlm_request     *dlm = NULL;
        struct list_head        head = LIST_HEAD_INIT(head);
        enum ldlm_lru_flags lru_flags;
        int avail, to_free, pack = 0;
        int rc;
        ENTRY;
        if (cancels == NULL)
                cancels = &head;
        if (ns_connect_cancelset(ns)) {
                /* Estimate the amount of available space in the request. */
                req_capsule_filled_sizes(pill, RCL_CLIENT);
                avail = ldlm_capsule_handles_avail(pill, RCL_CLIENT, canceloff);
                lru_flags = ns_connect_lru_resize(ns) ?
                        LDLM_LRU_FLAG_LRUR_NO_WAIT : LDLM_LRU_FLAG_AGED;
                to_free = !ns_connect_lru_resize(ns) &&
                        opc == LDLM_ENQUEUE ? 1 : 0;
                /* Cancel LRU locks here _only_ if the server supports
                 * EARLY_CANCEL. Otherwise we have to send extra CANCEL
                 * RPC, which will make us slower. */
                if (avail > count)
                        count += ldlm_cancel_lru_local(ns, cancels, to_free,
                                                       avail - count, 0,
                                                       lru_flags);
                if (avail > count)
                        pack = count;
                else
                        pack = avail;
                req_capsule_set_size(pill, &RMF_DLM_REQ, RCL_CLIENT,
                                     ldlm_request_bufsize(pack, opc));
        }
        rc = ptlrpc_request_pack(req, version, opc);
        if (rc) {
                ldlm_lock_list_put(cancels, l_bl_ast, count);
                RETURN(rc);
        }
        if (ns_connect_cancelset(ns)) {
                if (canceloff) {
                        dlm = req_capsule_client_get(pill, &RMF_DLM_REQ);
                        LASSERT(dlm);
                        /* Skip first lock handler in ldlm_request_pack(),
                         * this method will increment @lock_count according
                         * to the lock handle amount actually written to
                         * the buffer. */
                        dlm->lock_count = canceloff;
                }
                /* Pack into the request @pack lock handles. */
                ldlm_cli_cancel_list(cancels, pack, req, 0);
                /* Prepare and send separate cancel RPC for others. */
                ldlm_cli_cancel_list(cancels, count - pack, NULL, 0);
        } else {
                ldlm_lock_list_put(cancels, l_bl_ast, count);
        }
        RETURN(0);
}
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.