Lustre: llapi
llapi
Data Structures
struct llapi_stripe_param
struct find_param
Defines
#define ARRAY_SIZE(a) ((sizeof(a)) / (sizeof((a)[0])))
#define LLAPI_MSG_MASK 0x00000007
#define LLAPI_MSG_NO_ERRNO 0x00000010
#define llapi_err_noerrno(level, fmt, a...) llapi_error((level) | LLAPI_MSG_NO_ERRNO, 0, fmt, ## a)
#define HAVE_LLAPI_FILE_LOOKUP
#define VERBOSE_COUNT 0x1
#define VERBOSE_SIZE 0x2
#define VERBOSE_OFFSET 0x4
#define VERBOSE_POOL 0x8
#define VERBOSE_DETAIL 0x10
#define VERBOSE_OBJID 0x20
#define VERBOSE_GENERATION 0x40
#define VERBOSE_MDTINDEX 0x80
#define VERBOSE_LAYOUT 0x100
#define VERBOSE_ALL
#define HAVE_LLAPI_IS_LUSTRE_MNT
#define HAVE_CHANGELOG_EXTEND_REC 1
Typedefs
typedef void(* llapi_cb_t)(char *obd_type_name, char *obd_name, char *obd_uuid, void *args)
typedef void(* llapi_log_callback_t)(enum llapi_message_level level, int err, const char *fmt, va_list ap)
Enumerations
enum llapi_message_level {
LLAPI_MSG_OFF = 0, LLAPI_MSG_FATAL = 1, LLAPI_MSG_ERROR = 2, LLAPI_MSG_WARN = 3,
LLAPI_MSG_NORMAL = 4, LLAPI_MSG_INFO = 5, LLAPI_MSG_DEBUG = 6, LLAPI_MSG_MAX
}
Functions
void llapi_msg_set_level (int level)
int llapi_msg_get_level (void)
llapi_log_callback_t llapi_error_callback_set (llapi_log_callback_t cb)
Set a custom error logging function.
llapi_log_callback_t llapi_info_callback_set (llapi_log_callback_t cb)
Set a custom info logging function.
void llapi_error (enum llapi_message_level level, int err, const char *fmt,...) __attribute__((__format__(__printf__
void llapi_printf (enum llapi_message_level level, const char *fmt,...) __attribute__((__format__(__printf__
int llapi_file_open_param (const char *name, int flags, mode_t mode, const struct llapi_stripe_param *param)
Open a Lustre file.
int llapi_file_create (const char *name, unsigned long long stripe_size, int stripe_offset, int stripe_count, int stripe_pattern)
int llapi_file_open (const char *name, int flags, int mode, unsigned long long stripe_size, int stripe_offset, int stripe_count, int stripe_pattern)
int llapi_file_create_pool (const char *name, unsigned long long stripe_size, int stripe_offset, int stripe_count, int stripe_pattern, char *pool_name)
int llapi_file_open_pool (const char *name, int flags, int mode, unsigned long long stripe_size, int stripe_offset, int stripe_count, int stripe_pattern, char *pool_name)
int llapi_poollist (const char *name)
int llapi_get_poollist (const char *name, char **poollist, int list_size, char *buffer, int buffer_size)
Get the list of pools in a filesystem.
int llapi_get_poolmembers (const char *poolname, char **members, int list_size, char *buffer, int buffer_size)
Get the list of pool members.
int llapi_file_get_stripe (const char *path, struct lov_user_md *lum)
int llapi_file_lookup (int dirfd, const char *name)
int llapi_ostlist (char *path, struct find_param *param)
int llapi_uuid_match (char *real_uuid, char *search_uuid)
int llapi_getstripe (char *path, struct find_param *param)
int llapi_find (char *path, struct find_param *param)
int llapi_file_fget_mdtidx (int fd, int *mdtidx)
int llapi_dir_set_default_lmv_stripe (const char *name, int stripe_offset, int stripe_count, int stripe_pattern, const char *pool_name)
int llapi_dir_create_pool (const char *name, int flags, int stripe_offset, int stripe_count, int stripe_pattern, const char *poolname)
int llapi_direntry_remove (char *dname)
int llapi_obd_statfs (char *path, __u32 type, __u32 index, struct obd_statfs *stat_buf, struct obd_uuid *uuid_buf)
int llapi_ping (char *obd_type, char *obd_name)
int llapi_target_check (int num_types, char **obd_types, char *dir)
int llapi_file_get_lov_uuid (const char *path, struct obd_uuid *lov_uuid)
int llapi_file_get_lmv_uuid (const char *path, struct obd_uuid *lmv_uuid)
int llapi_file_fget_lov_uuid (int fd, struct obd_uuid *lov_uuid)
int llapi_lov_get_uuids (int fd, struct obd_uuid *uuidp, int *ost_count)
int llapi_lmv_get_uuids (int fd, struct obd_uuid *uuidp, int *mdt_count)
int llapi_is_lustre_mnttype (const char *type)
int llapi_search_ost (char *fsname, char *poolname, char *ostname)
int llapi_get_obd_count (char *mnt, int *count, int is_mdt)
int llapi_parse_size (const char *optarg, unsigned long long *size, unsigned long long *size_units, int bytes_spec)
size_units is to be initialized (or zeroed) by caller.
int llapi_search_mounts (const char *pathname, int index, char *mntdir, char *fsname)
int llapi_search_fsname (const char *pathname, char *fsname)
int llapi_getname (const char *path, char *buf, size_t size)
int llapi_search_fileset (const char *pathname, char *fileset)
int llapi_search_rootpath (char *pathname, const char *fsname)
int llapi_nodemap_exists (const char *name)
int llapi_migrate_mdt (char *path, struct find_param *param)
int llapi_mv (char *path, struct find_param *param)
int llapi_is_lustre_mnt (struct mntent *mnt)
int llapi_quotactl (char *mnt, struct if_quotactl *qctl)
int llapi_target_iterate (int type_num, char **obd_type, void *args, llapi_cb_t cb)
int llapi_get_connect_flags (const char *mnt, __u64 *flags)
int llapi_lsetfacl (int argc, char *argv[])
int llapi_lgetfacl (int argc, char *argv[])
int llapi_rsetfacl (int argc, char *argv[])
int llapi_rgetfacl (int argc, char *argv[])
int llapi_cp (int argc, char *argv[])
int llapi_ls (int argc, char *argv[])
int llapi_fid2path (const char *device, const char *fidstr, char *path, int pathlen, long long *recno, int *linkno)
int llapi_path2fid (const char *path, lustre_fid *fid)
int llapi_get_mdt_index_by_fid (int fd, const lustre_fid *fid, int *mdt_index)
int llapi_fd2fid (const int fd, lustre_fid *fid)
int llapi_path2parent (const char *path, unsigned int linkno, lustre_fid *parent_fid, char *name, size_t name_size)
int llapi_fd2parent (int fd, unsigned int linkno, lustre_fid *parent_fid, char *name, size_t name_size)
int llapi_chomp_string (char *buf)
int llapi_open_by_fid (const char *dir, const lustre_fid *fid, int open_flags)
Attempt to open a file with Lustre file identifier fid and return an open file descriptor.
int llapi_get_version (char *buffer, int buffer_size, char **version)
int llapi_get_data_version (int fd, __u64 *data_version, __u64 flags)
Get a 64-bit value representing the version of file data pointed by fd.
int llapi_hsm_state_get_fd (int fd, struct hsm_user_state *hus)
Return the current HSM states and HSM requests related to file pointed by path.
int llapi_hsm_state_get (const char *path, struct hsm_user_state *hus)
Return the current HSM states and HSM requests related to file pointed by path.
int llapi_hsm_state_set_fd (int fd, __u64 setmask, __u64 clearmask, __u32 archive_id)
Set HSM states of file pointed by fd.
int llapi_hsm_state_set (const char *path, __u64 setmask, __u64 clearmask, __u32 archive_id)
Set HSM states of file pointed by path.
int llapi_hsm_register_event_fifo (const char *path)
Given a path to a FIFO, create a filehandle for nonblocking writes to it.
int llapi_hsm_unregister_event_fifo (const char *path)
Given a path to a FIFO, close its filehandle and delete the FIFO.
void llapi_hsm_log_error (enum llapi_message_level level, int _rc, const char *fmt, va_list args)
Custom logging callback to be used when a monitoring FIFO has been registered.
int llapi_get_agent_uuid (char *path, char *buf, size_t bufsize)
int llapi_create_volatile_idx (char *directory, int idx, int mode)
int llapi_fswap_layouts_grouplock (int fd1, int fd2, __u64 dv1, __u64 dv2, int gid, __u64 flags)
Swap the layouts between 2 file descriptors the 2 files must be open for writing first fd received the ioctl, second fd is passed as arg this is assymetric but avoid use of root path for ioctl.
int llapi_fswap_layouts (int fd1, int fd2, __u64 dv1, __u64 dv2, __u64 flags)
int llapi_swap_layouts (const char *path1, const char *path2, __u64 dv1, __u64 dv2, __u64 flags)
Swap the layouts between 2 files the 2 files are open in write.
int llapi_changelog_start (void **priv, enum changelog_send_flag flags, const char *mdtname, long long startrec)
Start reading from a changelog.
int llapi_changelog_fini (void **priv)
Finish reading from a changelog.
int llapi_changelog_recv (void *priv, struct changelog_rec **rech)
int llapi_changelog_free (struct changelog_rec **rech)
Release the changelog record when done with it.
int llapi_changelog_clear (const char *mdtname, const char *idstr, long long endrec)
int llapi_hsm_copytool_register (struct hsm_copytool_private **priv, const char *mnt, int archive_count, int *archives, int rfd_flags)
Register a copytool.
int llapi_hsm_copytool_unregister (struct hsm_copytool_private **priv)
Deregister a copytool Note: under Linux, until llapi_hsm_copytool_unregister is called (or the program is killed), the libcfs module will be referenced and unremovable, even after Lustre services stop.
int llapi_hsm_copytool_get_fd (struct hsm_copytool_private *ct)
Returns a file descriptor to poll/select on.
int llapi_hsm_copytool_recv (struct hsm_copytool_private *priv, struct hsm_action_list **hal, int *msgsize)
Wait for the next hsm_action_list.
int llapi_hsm_action_begin (struct hsm_copyaction_private **phcp, const struct hsm_copytool_private *ct, const struct hsm_action_item *hai, int restore_mdt_index, int restore_open_flags, bool is_error)
Start processing an HSM action.
int llapi_hsm_action_end (struct hsm_copyaction_private **phcp, const struct hsm_extent *he, int hp_flags, int errval)
Terminate an HSM action processing.
int llapi_hsm_action_progress (struct hsm_copyaction_private *hcp, const struct hsm_extent *he, __u64 total, int hp_flags)
Notify a progress in processing an HSM action.
int llapi_hsm_action_get_dfid (const struct hsm_copyaction_private *hcp, lustre_fid *fid)
Get the fid of object to be used for copying data.
int llapi_hsm_action_get_fd (const struct hsm_copyaction_private *hcp)
Get a file descriptor to be used for copying data.
int llapi_hsm_import (const char *dst, int archive, const struct stat *st, unsigned long long stripe_size, int stripe_offset, int stripe_count, int stripe_pattern, char *pool_name, lustre_fid *newfid)
Import an existing hsm-archived file into Lustre.
struct hsm_user_request * llapi_hsm_user_request_alloc (int itemcount, int data_len)
Allocate a hsm_user_request with the specified carateristics.
int llapi_hsm_request (const char *path, const struct hsm_user_request *request)
Send a HSM request to Lustre, described in.
int llapi_hsm_current_action (const char *path, struct hsm_current_action *hca)
Return the current HSM request related to file pointed by path.
int llapi_json_init_list (struct llapi_json_item_list **item_list)
Create a list to hold JSON items.
int llapi_json_destroy_list (struct llapi_json_item_list **item_list)
Deallocate a list of JSON items.
int llapi_json_add_item (struct llapi_json_item_list **item_list, char *key, __u32 type, void *val)
Add an item to a list of JSON items.
int llapi_json_write_list (struct llapi_json_item_list **item_list, FILE *fp)
Write a list of JSON items to a filehandle.
int llapi_lease_get (int fd, int mode)
Get a lease on an open file.
int llapi_lease_check (int fd)
Check if a lease is still set on a file.
int llapi_lease_put (int fd)
Remove a lease.
int llapi_group_lock (int fd, int gid)
Take group lock.
int llapi_group_unlock (int fd, int gid)
Put group lock.
int llapi_ladvise (int fd, unsigned long long flags, int num_advise, struct lu_ladvise *ladvise)
Variables
bool liblustreapi_initialized
Define Documentation
#define VERBOSE_ALL
Value:
(VERBOSE_COUNT | VERBOSE_SIZE | \
                                 VERBOSE_OFFSET | VERBOSE_POOL | \
                                 VERBOSE_OBJID | VERBOSE_GENERATION |\
                                 VERBOSE_LAYOUT)
Definition at line 145 of file lustreapi.h.
Function Documentation
int llapi_changelog_free (struct changelog_rec ** rech)
Release the changelog record when done with it.
Definition at line 4077 of file liblustreapi.c.
{
        if (*rech) {
                /* We allocated memory starting at the kuc_hdr, but passed
                 * the consumer a pointer to the payload.
                 * Use pointer math to get back to the header.
                 */
                struct kuc_hdr *kuch = (struct kuc_hdr *)*rech - 1;
                free(kuch);
        }
        *rech = NULL;
        return 0;
}
int llapi_changelog_start (void ** priv, enum changelog_send_flag flags, const char * device, long long startrec)
Start reading from a changelog.
Parameters:
priv Opaque private control structure
flags Start flags (e.g. CHANGELOG_FLAG_BLOCK)
device Report changes recorded on this MDT
startrec Report changes beginning with this record number (just call llapi_changelog_fini when done; don't need an endrec)
Definition at line 3938 of file liblustreapi.c.
References llapi_changelog_fini().
{
        struct changelog_private        *cp;
        static bool                      warned;
        int                              rc;
        /* Set up the receiver control struct */
        cp = calloc(1, sizeof(*cp));
        if (cp == NULL)
                return -ENOMEM;
        cp->magic = CHANGELOG_PRIV_MAGIC;
        cp->flags = flags;
        /* Set up the receiver */
        rc = libcfs_ukuc_start(&cp->kuc, 0 /* no group registration */, 0);
        if (rc < 0)
                goto out_free;
        *priv = cp;
        /* CHANGELOG_FLAG_JOBID will eventually become mandatory. Display a
         * warning if it's missing. */
        if (!(flags & CHANGELOG_FLAG_JOBID) && !warned) {
                llapi_err_noerrno(LLAPI_MSG_WARN, "warning: %s() called "
                                  "w/o CHANGELOG_FLAG_JOBID", __func__);
                warned = true;
        }
        /* Tell the kernel to start sending */
        rc = changelog_ioctl(device, OBD_IOC_CHANGELOG_SEND, cp->kuc.lk_wfd,
                             startrec, flags);
        /* Only the kernel reference keeps the write side open */
        close(cp->kuc.lk_wfd);
        cp->kuc.lk_wfd = LK_NOFD;
        if (rc < 0) {
                /* frees and clears priv */
                llapi_changelog_fini(priv);
                return rc;
        }
        return 0;
out_free:
        free(cp);
        return rc;
}
llapi_log_callback_t llapi_error_callback_set (llapi_log_callback_t cb)
Set a custom error logging function.
Passing in NULL will reset the logging callback to its default value.
This function returns the value of the old callback.
Definition at line 156 of file liblustreapi.c.
{
        llapi_log_callback_t    old = llapi_error_callback;
        if (cb != NULL)
                llapi_error_callback = cb;
        else
                llapi_error_callback = error_callback_default;
        return old;
}
int llapi_file_open_param (const char * name, int flags, mode_t mode, const struct llapi_stripe_param * param)
Open a Lustre file.
Parameters:
name the name of the file to be opened
flags access mode, see flags in open(2)
mode permission of the file if it is created, see mode in open(2)
param stripe pattern of the newly created file
Return values:
file descriptor of opened file
negative errno on failure
Definition at line 466 of file liblustreapi.c.
{
        char fsname[MAX_OBD_NAME + 1] = { 0 };
        char *pool_name = param->lsp_pool;
        struct lov_user_md *lum = NULL;
        size_t lum_size = sizeof(*lum);
        int fd, rc;
        /* Make sure we are on a Lustre file system */
        rc = llapi_search_fsname(name, fsname);
        if (rc) {
                llapi_error(LLAPI_MSG_ERROR, rc,
                            "'%s' is not on a Lustre filesystem",
                            name);
                return rc;
        }
        /* Check if the stripe pattern is sane. */
        rc = llapi_stripe_limit_check(param->lsp_stripe_size,
                                      param->lsp_stripe_offset,
                                      param->lsp_stripe_count,
                                      param->lsp_stripe_pattern);
        if (rc != 0)
                return rc;
        /* Make sure we have a good pool */
        if (pool_name != NULL) {
                /* in case user gives the full pool name <fsname>.<poolname>,
                 * strip the fsname */
                char *ptr = strchr(pool_name, '.');
                if (ptr != NULL) {
                        *ptr = '\0';
                        if (strcmp(pool_name, fsname) != 0) {
                                *ptr = '.';
                                llapi_err_noerrno(LLAPI_MSG_ERROR,
                                        "Pool '%s' is not on filesystem '%s'",
                                        pool_name, fsname);
                                return -EINVAL;
                        }
                        pool_name = ptr + 1;
                }
                /* Make sure the pool exists and is non-empty */
                rc = llapi_search_ost(fsname, pool_name, NULL);
                if (rc < 1) {
                        char *err = rc == 0 ? "has no OSTs" : "does not exist";
                        llapi_err_noerrno(LLAPI_MSG_ERROR, "pool '%s.%s' %s",
                                          fsname, pool_name, err);
                        return -EINVAL;
                }
                lum_size = sizeof(struct lov_user_md_v3);
        }
        /* sanity check of target list */
        if (param->lsp_is_specific) {
                char ostname[MAX_OBD_NAME + 1];
                bool found = false;
                int i;
                for (i = 0; i < param->lsp_stripe_count; i++) {
                        snprintf(ostname, sizeof(ostname), "%s-OST%04x_UUID",
                                 fsname, param->lsp_osts[i]);
                        rc = llapi_search_ost(fsname, pool_name, ostname);
                        if (rc <= 0) {
                                if (rc == 0)
                                        rc = -ENODEV;
                                llapi_error(LLAPI_MSG_ERROR, rc,
                                            "%s: cannot find OST %s in %s",
                                            __func__, ostname,
                                            pool_name != NULL ?
                                            "pool" : "system");
                                return rc;
                        }
                        /* Make sure stripe offset is in OST list. */
                        if (param->lsp_osts[i] == param->lsp_stripe_offset)
                                found = true;
                }
                if (!found) {
                        llapi_error(LLAPI_MSG_ERROR, -EINVAL,
                                    "%s: stripe offset '%d' is not in the "
                                    "target list",
                                    __func__, param->lsp_stripe_offset);
                        return -EINVAL;
                }
                lum_size = lov_user_md_size(param->lsp_stripe_count,
                                            LOV_USER_MAGIC_SPECIFIC);
        }
        lum = calloc(1, lum_size);
        if (lum == NULL)
                return -ENOMEM;
retry_open:
        fd = open(name, flags | O_LOV_DELAY_CREATE, mode);
        if (fd < 0) {
                if (errno == EISDIR && !(flags & O_DIRECTORY)) {
                        flags = O_DIRECTORY | O_RDONLY;
                        goto retry_open;
                }
        }
        if (fd < 0) {
                rc = -errno;
                llapi_error(LLAPI_MSG_ERROR, rc, "unable to open '%s'", name);
                free(lum);
                return rc;
        }
        /*  Initialize IOCTL striping pattern structure */
        lum->lmm_magic = LOV_USER_MAGIC_V1;
        lum->lmm_pattern = param->lsp_stripe_pattern;
        lum->lmm_stripe_size = param->lsp_stripe_size;
        lum->lmm_stripe_count = param->lsp_stripe_count;
        lum->lmm_stripe_offset = param->lsp_stripe_offset;
        if (pool_name != NULL) {
                struct lov_user_md_v3 *lumv3 = (void *)lum;
                lumv3->lmm_magic = LOV_USER_MAGIC_V3;
                strncpy(lumv3->lmm_pool_name, pool_name, LOV_MAXPOOLNAME);
        }
        if (param->lsp_is_specific) {
                struct lov_user_md_v3 *lumv3 = (void *)lum;
                int i;
                lumv3->lmm_magic = LOV_USER_MAGIC_SPECIFIC;
                if (pool_name == NULL) {
                        /* LOV_USER_MAGIC_SPECIFIC uses v3 format plus specified
                         * OST list, therefore if pool is not specified we have
                         * to pack a null pool name for placeholder. */
                        memset(lumv3->lmm_pool_name, 0, LOV_MAXPOOLNAME);
                }
                for (i = 0; i < param->lsp_stripe_count; i++)
                        lumv3->lmm_objects[i].l_ost_idx = param->lsp_osts[i];
        }
        if (ioctl(fd, LL_IOC_LOV_SETSTRIPE, lum) != 0) {
                char *errmsg = "stripe already set";
                rc = -errno;
                if (errno != EEXIST && errno != EALREADY)
                        errmsg = strerror(errno);
                llapi_err_noerrno(LLAPI_MSG_ERROR,
                                  "error on ioctl %#jx for '%s' (%d): %s",
                                  (uintmax_t)LL_IOC_LOV_SETSTRIPE, name, fd,
                                  errmsg);
                close(fd);
                fd = rc;
        }
        free(lum);
        return fd;
}
int llapi_get_data_version (int fd, __u64 * data_version, __u64 flags)
Get a 64-bit value representing the version of file data pointed by fd.
Each write or truncate, flushed on OST, will change this value. You can use this value to verify if file data was modified. This only checks the file data, not metadata.
Parameters:
flags 0: no flush pages, usually used it the process has already taken locks; LL_DV_RD_FLUSH: OSTs will take LCK_PR to flush dirty pages from clients; LL_DV_WR_FLUSH: OSTs will take LCK_PW to flush all caching pages from clients.
Return values:
0 on success.
-errno on error.
Definition at line 4336 of file liblustreapi.c.
{
        int rc;
        struct ioc_data_version idv;
        idv.idv_flags = flags;
        rc = ioctl(fd, LL_IOC_DATA_VERSION, &idv);
        if (rc)
                rc = -errno;
        else
                *data_version = idv.idv_version;
        return rc;
}
int llapi_get_poollist (const char * name, char ** poollist, int list_size, char * buffer, int buffer_size)
Get the list of pools in a filesystem.
Parameters:
name filesystem name or path
poollist caller-allocated array of char*
list_size size of the poollist array
buffer caller-allocated buffer for storing pool names
buffer_size size of the buffer
Returns:
number of pools retrieved for this filesystem
Return values:
-error failure
Definition at line 1138 of file liblustreapi.c.
{
        char rname[PATH_MAX];
        glob_t pathname;
        char *fsname;
        char *ptr;
        DIR *dir;
        struct dirent pool;
        struct dirent *cookie = NULL;
        int rc = 0;
        unsigned int nb_entries = 0;
        unsigned int used = 0;
        unsigned int i;
        /* initialize output array */
        for (i = 0; i < list_size; i++)
                poollist[i] = NULL;
        /* is name a pathname ? */
        ptr = strchr(name, '/');
        if (ptr != NULL) {
                /* only absolute pathname is supported */
                if (*name != '/')
                        return -EINVAL;
                if (!realpath(name, rname)) {
                        rc = -errno;
                        llapi_error(LLAPI_MSG_ERROR, rc, "invalid path '%s'",
                                    name);
                        return rc;
                }
                fsname = strdup(rname);
                if (!fsname)
                        return -ENOMEM;
                rc = poolpath(&pathname, NULL, rname);
        } else {
                /* name is FSNAME */
                fsname = strdup(name);
                if (!fsname)
                        return -ENOMEM;
                rc = poolpath(&pathname, fsname, NULL);
        }
        if (rc != 0) {
                llapi_error(LLAPI_MSG_ERROR, rc,
                            "Lustre filesystem '%s' not found", name);
                goto free_path;
        }
        llapi_printf(LLAPI_MSG_NORMAL, "Pools from %s:\n", fsname);
        dir = opendir(pathname.gl_pathv[0]);
        if (dir == NULL) {
                rc = -errno;
                llapi_error(LLAPI_MSG_ERROR, rc,
                            "Could not open pool list for '%s'",
                            name);
                goto free_path;
        }
        while(1) {
                rc = readdir_r(dir, &pool, &cookie);
                if (rc != 0) {
                        rc = -errno;
                        llapi_error(LLAPI_MSG_ERROR, rc,
                                    "Error reading pool list for '%s'", name);
                        goto free_path;
                } else if ((rc == 0) && (cookie == NULL)) {
                        /* end of directory */
                        break;
                }
                /* ignore . and .. */
                if (!strcmp(pool.d_name, ".") || !strcmp(pool.d_name, ".."))
                        continue;
                /* check output bounds */
                if (nb_entries >= list_size) {
                        rc = -EOVERFLOW;
                        goto free_dir;
                }
                /* +2 for '.' and final '\0' */
                if (used + strlen(pool.d_name) + strlen(fsname) + 2
                    > buffer_size) {
                        rc = -EOVERFLOW;
                        goto free_dir;
                }
                sprintf(buffer + used, "%s.%s", fsname, pool.d_name);
                poollist[nb_entries] = buffer + used;
                used += strlen(pool.d_name) + strlen(fsname) + 2;
                nb_entries++;
        }
free_dir:
        closedir(dir);
free_path:
        cfs_free_param_data(&pathname);
        if (fsname)
                free(fsname);
        return rc != 0 ? rc : nb_entries;
}
int llapi_get_poolmembers (const char * poolname, char ** members, int list_size, char * buffer, int buffer_size)
Get the list of pool members.
Parameters:
poolname string of format <fsname>.<poolname>
members caller-allocated array of char*
list_size size of the members array
buffer caller-allocated buffer for storing OST names
buffer_size size of the buffer
Returns:
number of members retrieved for this pool
Return values:
-error failure
Definition at line 1057 of file liblustreapi.c.
{
        char fsname[PATH_MAX];
        char *pool, *tmp;
        glob_t pathname;
        char buf[PATH_MAX];
        FILE *fd;
        int rc = 0;
        int nb_entries = 0;
        int used = 0;
        /* name is FSNAME.POOLNAME */
        if (strlen(poolname) >= sizeof(fsname))
                return -EOVERFLOW;
        strlcpy(fsname, poolname, sizeof(fsname));
        pool = strchr(fsname, '.');
        if (pool == NULL)
                return -EINVAL;
        *pool = '\0';
        pool++;
        rc = poolpath(&pathname, fsname, NULL);
        if (rc != 0) {
                llapi_error(LLAPI_MSG_ERROR, rc,
                            "Lustre filesystem '%s' not found",
                            fsname);
                return rc;
        }
        llapi_printf(LLAPI_MSG_NORMAL, "Pool: %s.%s\n", fsname, pool);
        rc = snprintf(buf, sizeof(buf), "%s/%s", pathname.gl_pathv[0], pool);
        cfs_free_param_data(&pathname);
        if (rc >= sizeof(buf))
                return -EOVERFLOW;
        fd = fopen(buf, "r");
        if (fd == NULL) {
                rc = -errno;
                llapi_error(LLAPI_MSG_ERROR, rc, "cannot open %s", buf);
                return rc;
        }
        rc = 0;
        while (fgets(buf, sizeof(buf), fd) != NULL) {
                if (nb_entries >= list_size) {
                        rc = -EOVERFLOW;
                        break;
                }
                buf[sizeof(buf) - 1] = '\0';
                /* remove '\n' */
                tmp = strchr(buf, '\n');
                if (tmp != NULL)
                        *tmp='\0';
                if (used + strlen(buf) + 1 > buffer_size) {
                        rc = -EOVERFLOW;
                        break;
                }
                strcpy(buffer + used, buf);
                members[nb_entries] = buffer + used;
                used += strlen(buf) + 1;
                nb_entries++;
                rc = nb_entries;
        }
        fclose(fd);
        return rc;
}
int llapi_group_lock (int fd, int gid)
Take group lock.
Parameters:
fd File to lock.
gid Group Identifier.
Return values:
0 on success.
-errno on failure.
Definition at line 4577 of file liblustreapi.c.
{
        int rc;
        rc = ioctl(fd, LL_IOC_GROUP_LOCK, gid);
        if (rc < 0) {
                rc = -errno;
                llapi_error(LLAPI_MSG_ERROR, rc, "cannot get group lock");
        }
        return rc;
}
int llapi_group_unlock (int fd, int gid)
Put group lock.
Parameters:
fd File to unlock.
gid Group Identifier.
Return values:
0 on success.
-errno on failure.
Definition at line 4598 of file liblustreapi.c.
{
        int rc;
        rc = ioctl(fd, LL_IOC_GROUP_UNLOCK, gid);
        if (rc < 0) {
                rc = -errno;
                llapi_error(LLAPI_MSG_ERROR, rc, "cannot put group lock");
        }
        return rc;
}
int llapi_hsm_action_begin (struct hsm_copyaction_private ** phcp, const struct hsm_copytool_private * ct, const struct hsm_action_item * hai, int restore_mdt_index, int restore_open_flags, bool is_error)
Start processing an HSM action.
Should be called by copytools just before starting handling a request. It could be skipped if copytool only want to directly report an error,
See also:
llapi_hsm_action_end().
Parameters:
hcp Opaque action handle to be passed to llapi_hsm_action_progress and llapi_hsm_action_end.
ct Copytool handle acquired at registration.
hai The hsm_action_item describing the request.
restore_mdt_index On restore: MDT index where to create the volatile file. Use -1 for default.
restore_open_flags On restore: volatile file creation mode. Use O_LOV_DELAY_CREATE to manually set the LOVEA afterwards.
is_error Whether this call is just to report an error.
Returns:
0 on success.
Definition at line 1096 of file liblustreapi_hsm.c.
{
        struct hsm_copyaction_private   *hcp;
        int                              rc;
        hcp = calloc(1, sizeof(*hcp));
        if (hcp == NULL)
                return -ENOMEM;
        hcp->data_fd = -1;
        hcp->ct_priv = ct;
        hcp->copy.hc_hai = *hai;
        hcp->copy.hc_hai.hai_len = sizeof(*hai);
        if (is_error)
                goto ok_out;
        if (hai->hai_action == HSMA_RESTORE) {
                rc = ct_md_getattr(hcp->ct_priv, &hai->hai_fid, &hcp->stat);
                if (rc < 0)
                        goto err_out;
                rc = create_restore_volatile(hcp, restore_mdt_index,
                                             restore_open_flags);
                if (rc < 0)
                        goto err_out;
        }
        rc = ioctl(ct->mnt_fd, LL_IOC_HSM_COPY_START, &hcp->copy);
        if (rc < 0) {
                rc = -errno;
                goto err_out;
        }
        llapi_hsm_log_ct_progress(&hcp, hai, CT_START, 0, 0);
ok_out:
        hcp->magic = CP_PRIV_MAGIC;
        *phcp = hcp;
        return 0;
err_out:
        if (!(hcp->data_fd < 0))
                close(hcp->data_fd);
        free(hcp);
        return rc;
}
int llapi_hsm_action_end (struct hsm_copyaction_private ** phcp, const struct hsm_extent * he, int hp_flags, int errval)
Terminate an HSM action processing.
Should be called by copytools just having finished handling the request.
Parameters:
hdl[in,out] Handle returned by llapi_hsm_action_start.
he[in] The final range of copied data (for copy actions).
errval[in] The status code of the operation.
flags[in] The flags about the termination status (HP_FLAG_RETRY if the error is retryable).
Returns:
0 on success.
Definition at line 1160 of file liblustreapi_hsm.c.
{
        struct hsm_copyaction_private   *hcp;
        struct hsm_action_item          *hai;
        int                              rc;
        if (phcp == NULL || *phcp == NULL || he == NULL)
                return -EINVAL;
        hcp = *phcp;
        if (hcp->magic != CP_PRIV_MAGIC)
                return -EINVAL;
        hai = &hcp->copy.hc_hai;
        if (hai->hai_action == HSMA_RESTORE && errval == 0) {
                struct ll_futimes_3 lfu = {
                        .lfu_atime_sec = hcp->stat.st_atim.tv_sec,
                        .lfu_atime_nsec = hcp->stat.st_atim.tv_nsec,
                        .lfu_mtime_sec = hcp->stat.st_mtim.tv_sec,
                        .lfu_mtime_nsec = hcp->stat.st_mtim.tv_nsec,
                        .lfu_ctime_sec = hcp->stat.st_ctim.tv_sec,
                        .lfu_ctime_nsec = hcp->stat.st_ctim.tv_nsec,
                };
                rc = fsync(hcp->data_fd);
                if (rc < 0) {
                        errval = -errno;
                        goto end;
                }
                /* Set {a,m,c}time of volatile file to that of original. */
                rc = ioctl(hcp->data_fd, LL_IOC_FUTIMES_3, &lfu);
                if (rc < 0) {
                        errval = -errno;
                        goto end;
                }
        }
end:
        /* In some cases, like restore, 2 FIDs are used.
         * Set the right FID to use here. */
        if (hai->hai_action == HSMA_ARCHIVE || hai->hai_action == HSMA_RESTORE)
                hai->hai_fid = hai->hai_dfid;
        /* Fill the last missing data that will be needed by
         * kernel to send a hsm_progress. */
        hcp->copy.hc_flags  = hp_flags;
        hcp->copy.hc_errval = abs(errval);
        hcp->copy.hc_hai.hai_extent = *he;
        rc = ioctl(hcp->ct_priv->mnt_fd, LL_IOC_HSM_COPY_END, &hcp->copy);
        if (rc) {
                rc = -errno;
                goto err_cleanup;
        }
        llapi_hsm_log_ct_progress(&hcp, hai, CT_FINISH, 0, 0);
err_cleanup:
        if (!(hcp->data_fd < 0))
                close(hcp->data_fd);
        free(hcp);
        *phcp = NULL;
        return rc;
}
int llapi_hsm_action_get_dfid (const struct hsm_copyaction_private * hcp, lustre_fid * fid)
Get the fid of object to be used for copying data.
Returns:
error code if the action is not a copy operation.
Definition at line 1276 of file liblustreapi_hsm.c.
{
        const struct hsm_action_item    *hai = &hcp->copy.hc_hai;
        if (hcp->magic != CP_PRIV_MAGIC)
                return -EINVAL;
        if (hai->hai_action != HSMA_RESTORE && hai->hai_action != HSMA_ARCHIVE)
                return -EINVAL;
        *fid = hai->hai_dfid;
        return 0;
}
int llapi_hsm_action_get_fd (const struct hsm_copyaction_private * hcp)
Get a file descriptor to be used for copying data.
It's up to the caller to close the FDs obtained from this function.
Return values:
a file descriptor on success.
a negative error code on failure.
Definition at line 1299 of file liblustreapi_hsm.c.
{
        const struct hsm_action_item    *hai = &hcp->copy.hc_hai;
        int fd;
        if (hcp->magic != CP_PRIV_MAGIC)
                return -EINVAL;
        if (hai->hai_action == HSMA_ARCHIVE) {
                return ct_open_by_fid(hcp->ct_priv, &hai->hai_dfid,
                                O_RDONLY | O_NOATIME | O_NOFOLLOW | O_NONBLOCK);
        } else if (hai->hai_action == HSMA_RESTORE) {
                fd = dup(hcp->data_fd);
                return fd < 0 ? -errno : fd;
        } else {
                return -EINVAL;
        }
}
int llapi_hsm_action_progress (struct hsm_copyaction_private * hcp, const struct hsm_extent * he, __u64 total, int hp_flags)
Notify a progress in processing an HSM action.
Parameters:
hdl[in,out] handle returned by llapi_hsm_action_start.
he[in] the range of copied data (for copy actions).
total[in] the expected total of copied data (for copy actions).
hp_flags[in] HSM progress flags.
Returns:
0 on success.
Definition at line 1239 of file liblustreapi_hsm.c.
{
        int                      rc;
        struct hsm_progress      hp;
        struct hsm_action_item  *hai;
        if (hcp == NULL || he == NULL)
                return -EINVAL;
        if (hcp->magic != CP_PRIV_MAGIC)
                return -EINVAL;
        hai = &hcp->copy.hc_hai;
        memset(&hp, 0, sizeof(hp));
        hp.hp_cookie = hai->hai_cookie;
        hp.hp_flags  = hp_flags;
        /* Progress is made on the data fid */
        hp.hp_fid = hai->hai_dfid;
        hp.hp_extent = *he;
        rc = ioctl(hcp->ct_priv->mnt_fd, LL_IOC_HSM_PROGRESS, &hp);
        if (rc < 0)
                rc = -errno;
        llapi_hsm_log_ct_progress(&hcp, hai, CT_RUNNING, total, he->length);
        return rc;
}
int llapi_hsm_copytool_get_fd (struct hsm_copytool_private * ct)
Returns a file descriptor to poll/select on.
Parameters:
ct Opaque private control structure
Return values:
-EINVAL on error
the file descriptor for reading HSM events from the kernel
Definition at line 838 of file liblustreapi_hsm.c.
{
        if (ct == NULL || ct->magic != CT_PRIV_MAGIC)
                return -EINVAL;
        return libcfs_ukuc_get_rfd(&ct->kuc);
}
int llapi_hsm_copytool_recv (struct hsm_copytool_private * ct, struct hsm_action_list ** halh, int * msgsize)
Wait for the next hsm_action_list.
Parameters:
ct Opaque private control structure
halh Action list handle, will be allocated here
msgsize Number of bytes in the message, will be set here
Returns:
0 valid message received; halh and msgsize are set <0 error code Note: The application must not call llapi_hsm_copytool_recv until it has cleared the data in ct->kuch from the previous call.
Definition at line 855 of file liblustreapi_hsm.c.
{
        struct kuc_hdr          *kuch;
        struct hsm_action_list  *hal;
        int                      rc = 0;
        if (ct == NULL || ct->magic != CT_PRIV_MAGIC)
                return -EINVAL;
        if (halh == NULL || msgsize == NULL)
                return -EINVAL;
        kuch = ct->kuch;
repeat:
        rc = libcfs_ukuc_msg_get(&ct->kuc, (char *)kuch,
                                 HAL_MAXSIZE + sizeof(*kuch),
                                 KUC_TRANSPORT_HSM);
        if (rc < 0)
                goto out_err;
        /* Handle generic messages */
        if (kuch->kuc_transport == KUC_TRANSPORT_GENERIC &&
            kuch->kuc_msgtype == KUC_MSG_SHUTDOWN) {
                rc = -ESHUTDOWN;
                goto out_err;
        }
        if (kuch->kuc_transport != KUC_TRANSPORT_HSM ||
            kuch->kuc_msgtype != HMT_ACTION_LIST) {
                llapi_err_noerrno(LLAPI_MSG_ERROR,
                                  "Unknown HSM message type %d:%d\n",
                                  kuch->kuc_transport, kuch->kuc_msgtype);
                rc = -EPROTO;
                goto out_err;
        }
        if (kuch->kuc_msglen < sizeof(*kuch) + sizeof(*hal)) {
                llapi_err_noerrno(LLAPI_MSG_ERROR, "Short HSM message %d",
                                  kuch->kuc_msglen);
                rc = -EPROTO;
                goto out_err;
        }
        /* Our message is a hsm_action_list. Use pointer math to skip
        * kuch_hdr and point directly to the message payload.
        */
        hal = (struct hsm_action_list *)(kuch + 1);
        /* Check that we have registered for this archive #
         * if 0 registered, we serve any archive */
        if (ct->archives &&
            ((1 << (hal->hal_archive_id - 1)) & ct->archives) == 0) {
                llapi_err_noerrno(LLAPI_MSG_INFO,
                                  "This copytool does not service archive #%d,"
                                  " ignoring this request."
                                  " Mask of served archive is 0x%.8X",
                                  hal->hal_archive_id, ct->archives);
                goto repeat;
        }
        *halh = hal;
        *msgsize = kuch->kuc_msglen - sizeof(*kuch);
        return 0;
out_err:
        *halh = NULL;
        *msgsize = 0;
        return rc;
}
int llapi_hsm_copytool_register (struct hsm_copytool_private ** priv, const char * mnt, int archive_count, int * archives, int rfd_flags)
Register a copytool.
Parameters:
[out] priv Opaque private control structure
mnt Lustre filesystem mount point
archive_count Number of valid archive IDs in archives
archives Which archive numbers this copytool is responsible for
rfd_flags flags applied to read fd of pipe (e.g. O_NONBLOCK)
Return values:
0 on success.
-errno on error.
Definition at line 676 of file liblustreapi_hsm.c.
{
        struct hsm_copytool_private     *ct;
        int                              rc;
        if (archive_count > 0 && archives == NULL) {
                llapi_err_noerrno(LLAPI_MSG_ERROR,
                                  "NULL archive numbers");
                return -EINVAL;
        }
        if (archive_count > LL_HSM_MAX_ARCHIVE) {
                llapi_err_noerrno(LLAPI_MSG_ERROR, "%d requested when maximum "
                                  "of %zu archives supported", archive_count,
                                  LL_HSM_MAX_ARCHIVE);
                return -EINVAL;
        }
        ct = calloc(1, sizeof(*ct));
        if (ct == NULL)
                return -ENOMEM;
        ct->magic = CT_PRIV_MAGIC;
        ct->mnt_fd = -1;
        ct->open_by_fid_fd = -1;
        ct->kuc.lk_rfd = LK_NOFD;
        ct->kuc.lk_wfd = LK_NOFD;
        ct->mnt = strdup(mnt);
        if (ct->mnt == NULL) {
                rc = -ENOMEM;
                goto out_err;
        }
        ct->kuch = malloc(HAL_MAXSIZE + sizeof(*ct->kuch));
        if (ct->kuch == NULL) {
                rc = -ENOMEM;
                goto out_err;
        }
        ct->mnt_fd = open(ct->mnt, O_RDONLY);
        if (ct->mnt_fd < 0) {
                rc = -errno;
                goto out_err;
        }
        ct->open_by_fid_fd = openat(ct->mnt_fd, OPEN_BY_FID_PATH, O_RDONLY);
        if (ct->open_by_fid_fd < 0) {
                rc = -errno;
                goto out_err;
        }
        /* no archives specified means "match all". */
        ct->archives = 0;
        for (rc = 0; rc < archive_count; rc++) {
                if ((archives[rc] > LL_HSM_MAX_ARCHIVE) || (archives[rc] < 0)) {
                        llapi_err_noerrno(LLAPI_MSG_ERROR, "%d requested when "
                                          "archive id [0 - %zu] is supported",
                                          archives[rc], LL_HSM_MAX_ARCHIVE);
                        rc = -EINVAL;
                        goto out_err;
                }
                /* in the list we have an all archive wildcard
                 * so move to all archives mode
                 */
                if (archives[rc] == 0) {
                        ct->archives = 0;
                        archive_count = 0;
                        break;
                }
                ct->archives |= (1 << (archives[rc] - 1));
        }
        rc = libcfs_ukuc_start(&ct->kuc, KUC_GRP_HSM, rfd_flags);
        if (rc < 0)
                goto out_err;
        /* Storing archive(s) in lk_data; see mdc_ioc_hsm_ct_start */
        ct->kuc.lk_data = ct->archives;
        rc = ioctl(ct->mnt_fd, LL_IOC_HSM_CT_START, &ct->kuc);
        if (rc < 0) {
                rc = -errno;
                llapi_error(LLAPI_MSG_ERROR, rc,
                            "cannot start copytool on '%s'", mnt);
                goto out_kuc;
        }
        llapi_hsm_log_ct_registration(&ct, CT_REGISTER);
        /* Only the kernel reference keeps the write side open */
        close(ct->kuc.lk_wfd);
        ct->kuc.lk_wfd = LK_NOFD;
        *priv = ct;
        return 0;
out_kuc:
        /* cleanup the kuc channel */
        libcfs_ukuc_stop(&ct->kuc);
out_err:
        if (!(ct->mnt_fd < 0))
                close(ct->mnt_fd);
        if (!(ct->open_by_fid_fd < 0))
                close(ct->open_by_fid_fd);
        free(ct->mnt);
        free(ct->kuch);
        free(ct);
        return rc;
}
int llapi_hsm_current_action (const char * path, struct hsm_current_action * hca)
Return the current HSM request related to file pointed by path.
Parameters:
hca Should be allocated by caller. Will be filled with current file actions.
Return values:
0 on success.
-errno on error.
Definition at line 1495 of file liblustreapi_hsm.c.
{
        int fd;
        int rc;
        fd = open(path, O_RDONLY | O_NONBLOCK);
        if (fd < 0)
                return -errno;
        rc = ioctl(fd, LL_IOC_HSM_ACTION, hca);
        /* If error, save errno value */
        rc = rc ? -errno : 0;
        close(fd);
        return rc;
}
int llapi_hsm_import (const char * dst, int archive, const struct stat * st, unsigned long long stripe_size, int stripe_offset, int stripe_count, int stripe_pattern, char * pool_name, lustre_fid * newfid)
Import an existing hsm-archived file into Lustre.
Caller must access file by (returned) newfid value from now on.
Parameters:
dst path to Lustre destination (e.g. /mnt/lustre/my/file).
archive archive number.
st struct stat buffer containing file ownership, perm, etc.
stripe_* Striping options. Currently ignored, since the restore operation will set the striping. In V2, this striping might be used.
newfid[out] Filled with new Lustre fid.
Definition at line 1331 of file liblustreapi_hsm.c.
{
        struct hsm_user_import   hui;
        int                      fd;
        int                      rc = 0;
        if (stripe_pattern == 0)
                stripe_pattern = LOV_PATTERN_RAID0;
        /* Create a non-striped file */
        fd = llapi_file_open_pool(dst, O_CREAT | O_WRONLY, st->st_mode,
                                  stripe_size, stripe_offset, stripe_count,
                                  stripe_pattern | LOV_PATTERN_F_RELEASED,
                                  pool_name);
        if (fd < 0) {
                llapi_error(LLAPI_MSG_ERROR, fd,
                            "cannot create '%s' for import", dst);
                return fd;
        }
        /* Get the new fid in Lustre. Caller needs to use this fid
           from now on. */
        rc = llapi_fd2fid(fd, newfid);
        if (rc != 0) {
                llapi_error(LLAPI_MSG_ERROR, rc,
                            "cannot get fid of '%s' for import", dst);
                goto out_unlink;
        }
        hui.hui_uid = st->st_uid;
        hui.hui_gid = st->st_gid;
        hui.hui_mode = st->st_mode;
        hui.hui_size = st->st_size;
        hui.hui_archive_id = archive;
        hui.hui_atime = st->st_atime;
        hui.hui_atime_ns = st->st_atim.tv_nsec;
        hui.hui_mtime = st->st_mtime;
        hui.hui_mtime_ns = st->st_mtim.tv_nsec;
        rc = ioctl(fd, LL_IOC_HSM_IMPORT, &hui);
        if (rc != 0) {
                rc = -errno;
                llapi_error(LLAPI_MSG_ERROR, rc, "cannot import '%s'", dst);
                goto out_unlink;
        }
out_unlink:
        if (fd >= 0)
                close(fd);
        if (rc)
                unlink(dst);
        return rc;
}
void llapi_hsm_log_error (enum llapi_message_level level, int _rc, const char * fmt, va_list args)
Custom logging callback to be used when a monitoring FIFO has been registered.
Formats log entries as JSON events suitable for consumption by a copytool monitoring process.
Parameters:
level The message loglevel.
_rc The returncode associated with the message.
fmt The message format string.
args Arguments to be formatted by the format string.
Return values:
None.
Definition at line 574 of file liblustreapi_hsm.c.
References llapi_json_add_item(), llapi_json_destroy_list(), and llapi_json_init_list().
{
        int                             rc;
        int                             msg_len;
        int                             real_level;
        char                            *msg = NULL;
        va_list                         args2;
        struct llapi_json_item_list     *json_items;
        /* Noop unless the event fd was initialized */
        if (llapi_hsm_event_fd < 0)
                return;
        rc = llapi_json_init_list(&json_items);
        if (rc < 0)
                goto err;
        if ((level & LLAPI_MSG_NO_ERRNO) == 0) {
                rc = llapi_json_add_item(&json_items, "errno",
                                         LLAPI_JSON_INTEGER,
                                         &_rc);
                if (rc < 0)
                        goto err;
                rc = llapi_json_add_item(&json_items, "error",
                                         LLAPI_JSON_STRING,
                                         strerror(abs(_rc)));
                if (rc < 0)
                        goto err;
        }
        va_copy(args2, args);
        msg_len = vsnprintf(NULL, 0, fmt, args2) + 1;
        va_end(args2);
        if (msg_len >= 0) {
                msg = (char *) alloca(msg_len);
                if (msg == NULL) {
                        rc = -ENOMEM;
                        goto err;
                }
                rc = vsnprintf(msg, msg_len, fmt, args);
                if (rc < 0)
                        goto err;
                rc = llapi_json_add_item(&json_items, "message",
                                         LLAPI_JSON_STRING,
                                         msg);
                if (rc < 0)
                        goto err;
        } else {
                rc = llapi_json_add_item(&json_items, "message",
                                         LLAPI_JSON_STRING,
                                         "INTERNAL ERROR: message failed");
                if (rc < 0)
                        goto err;
        }
        real_level = level & LLAPI_MSG_NO_ERRNO;
        real_level = real_level > 0 ? level - LLAPI_MSG_NO_ERRNO : level;
        rc = llapi_json_add_item(&json_items, "level", LLAPI_JSON_STRING,
                                 (void *)llapi_msg_level2str(real_level));
        if (rc < 0)
                goto err;
        rc = llapi_json_add_item(&json_items, "event_type", LLAPI_JSON_STRING,
                                 "LOGGED_MESSAGE");
        if (rc < 0)
                goto err;
        rc = llapi_hsm_write_json_event(&json_items);
        if (rc < 0)
                goto err;
        goto out_free;
err:
        /* Write directly to stderr to avoid llapi_error, which now
         * emits JSON event messages. */
        fprintf(stderr, "\nFATAL ERROR IN llapi_hsm_log_error(): rc %d,", rc);
out_free:
        if (json_items != NULL)
                llapi_json_destroy_list(&json_items);
        return;
}
int llapi_hsm_register_event_fifo (const char * path)
Given a path to a FIFO, create a filehandle for nonblocking writes to it.
Intended to be used for copytool monitoring processes that read an event stream from the FIFO. Events written in the absence of a reader are lost.
Parameters:
path Path to monitor FIFO.
Return values:
0 on success.
-errno on error.
Definition at line 473 of file liblustreapi_hsm.c.
{
        int read_fd;
        struct stat statbuf;
        struct sigaction ignore_action;
        int rc;
        /* Create the FIFO if necessary. */
        if ((mkfifo(path, 0644) < 0) && (errno != EEXIST)) {
                llapi_error(LLAPI_MSG_ERROR, errno, "mkfifo(%s) failed", path);
                return -errno;
        }
        if (errno == EEXIST) {
                if (stat(path, &statbuf) < 0) {
                        llapi_error(LLAPI_MSG_ERROR, errno, "mkfifo(%s) failed",
                                    path);
                        return -errno;
                }
                if (!S_ISFIFO(statbuf.st_mode) ||
                    ((statbuf.st_mode & 0777) != 0644)) {
                        llapi_error(LLAPI_MSG_ERROR, errno, "%s exists but is "
                                    "not a pipe or has a wrong mode", path);
                        return -errno;
                }
        } else {
                created_hsm_event_fifo = true;
        }
        /* Open the FIFO for read so that the subsequent open for write
         * doesn't immediately fail. */
        read_fd = open(path, O_RDONLY | O_NONBLOCK);
        if (read_fd < 0) {
                llapi_error(LLAPI_MSG_ERROR, errno,
                            "cannot open(%s) for read", path);
                return -errno;
        }
        /* Open the FIFO for writes, but don't block on waiting
         * for a reader. */
        llapi_hsm_event_fd = open(path, O_WRONLY | O_NONBLOCK);
        rc = -errno;
        /* Now close the reader. An external monitoring process can
         * now open the FIFO for reads. If no reader comes along the
         * events are lost. NOTE: Only one reader at a time! */
        close(read_fd);
        if (llapi_hsm_event_fd < 0) {
                llapi_error(LLAPI_MSG_ERROR, -rc,
                            "cannot open(%s) for write", path);
                return rc;
        }
        /* Ignore SIGPIPEs -- can occur if the reader goes away. */
        memset(&ignore_action, 0, sizeof(ignore_action));
        ignore_action.sa_handler = SIG_IGN;
        sigemptyset(&ignore_action.sa_mask);
        sigaction(SIGPIPE, &ignore_action, NULL);
        return 0;
}
int llapi_hsm_request (const char * path, const struct hsm_user_request * request)
Send a HSM request to Lustre, described in.
Parameters:
request.
path Fullpath to the file to operate on.
request The request, allocated with llapi_hsm_user_request_alloc().
Returns:
0 on success, an error code otherwise.
Definition at line 1538 of file liblustreapi_hsm.c.
{
        int rc;
        int fd;
        rc = get_root_path(WANT_FD, NULL, &fd, (char *)path, -1);
        if (rc)
                return rc;
        rc = ioctl(fd, LL_IOC_HSM_REQUEST, request);
        /* If error, save errno value */
        rc = rc ? -errno : 0;
        close(fd);
        return rc;
}
int llapi_hsm_state_get (const char * path, struct hsm_user_state * hus)
Return the current HSM states and HSM requests related to file pointed by path.
see llapi_hsm_state_get_fd() for args use and return
Definition at line 1414 of file liblustreapi_hsm.c.
References llapi_hsm_state_get_fd().
{
        int fd;
        int rc;
        fd = open(path, O_RDONLY | O_NONBLOCK);
        if (fd < 0)
                return -errno;
        rc = llapi_hsm_state_get_fd(fd, hus);
        close(fd);
        return rc;
}
int llapi_hsm_state_get_fd (int fd, struct hsm_user_state * hus)
Return the current HSM states and HSM requests related to file pointed by path.
Parameters:
hus Should be allocated by caller. Will be filled with current file states.
Return values:
0 on success.
-errno on error.
Definition at line 1397 of file liblustreapi_hsm.c.
Referenced by llapi_hsm_state_get().
{
        int rc;
        rc = ioctl(fd, LL_IOC_HSM_STATE_GET, hus);
        /* If error, save errno value */
        rc = rc ? -errno : 0;
        return rc;
}
int llapi_hsm_state_set (const char * path, __u64 setmask, __u64 clearmask, __u32 archive_id)
Set HSM states of file pointed by path.
see llapi_hsm_state_set_fd() for args use and return
Definition at line 1470 of file liblustreapi_hsm.c.
References llapi_hsm_state_set_fd().
{
        int fd;
        int rc;
        fd = open(path, O_WRONLY | O_LOV_DELAY_CREATE | O_NONBLOCK);
        if (fd < 0)
                return -errno;
        rc = llapi_hsm_state_set_fd(fd, setmask, clearmask, archive_id);
        close(fd);
        return rc;
}
int llapi_hsm_state_set_fd (int fd, __u64 setmask, __u64 clearmask, __u32 archive_id)
Set HSM states of file pointed by fd.
Using the provided bitmasks, the current HSM states for this file will be changed. archive_id could be used to change the archive number also. Set it to 0 if you do not want to change it.
Parameters:
setmask Bitmask for flag to be set.
clearmask Bitmask for flag to be cleared.
archive_id Archive number identifier to use. 0 means no change.
Return values:
0 on success.
-errno on error.
Definition at line 1443 of file liblustreapi_hsm.c.
Referenced by llapi_hsm_state_set().
{
        struct hsm_state_set     hss;
        int                      rc;
        hss.hss_valid = HSS_SETMASK|HSS_CLEARMASK;
        hss.hss_setmask = setmask;
        hss.hss_clearmask = clearmask;
        /* Change archive_id if provided. We can only change
         * to set something different than 0. */
        if (archive_id > 0) {
                hss.hss_valid |= HSS_ARCHIVE_ID;
                hss.hss_archive_id = archive_id;
        }
        rc = ioctl(fd, LL_IOC_HSM_STATE_SET, &hss);
        /* If error, save errno value */
        rc = rc ? -errno : 0;
        return rc;
}
int llapi_hsm_unregister_event_fifo (const char * path)
Given a path to a FIFO, close its filehandle and delete the FIFO.
Parameters:
path Path to monitor FIFO.
Return values:
0 on success.
-errno on error.
Definition at line 543 of file liblustreapi_hsm.c.
{
        /* Noop unless the event fd was initialized */
        if (llapi_hsm_event_fd < 0)
                return 0;
        if (close(llapi_hsm_event_fd) < 0)
                return -errno;
        if (created_hsm_event_fifo) {
                unlink(path);
                created_hsm_event_fifo = false;
        }
        llapi_hsm_event_fd = -1;
        return 0;
}
struct hsm_user_request* llapi_hsm_user_request_alloc (int itemcount, int data_len) [read]
Allocate a hsm_user_request with the specified carateristics.
This structure should be freed with free().
Returns:
an allocated structure on success, NULL otherwise.
Definition at line 1518 of file liblustreapi_hsm.c.
{
        int len = 0;
        len += sizeof(struct hsm_user_request);
        len += sizeof(struct hsm_user_item) * itemcount;
        len += data_len;
        return (struct hsm_user_request *)malloc(len);
}
llapi_log_callback_t llapi_info_callback_set (llapi_log_callback_t cb)
Set a custom info logging function.
Passing in NULL will reset the logging callback to its default value.
This function returns the value of the old callback.
Definition at line 174 of file liblustreapi.c.
{
        llapi_log_callback_t    old = llapi_info_callback;
        if (cb != NULL)
                llapi_info_callback = cb;
        else
                llapi_info_callback = info_callback_default;
        return old;
}
int llapi_json_add_item (struct llapi_json_item_list ** json_items, char * key, __u32 type, void * val)
Add an item to a list of JSON items.
Parameters:
json_items Item list handle
key Item key name
type Item key type
val Item key value
Return values:
0 on success.
-errno on error.
Definition at line 255 of file liblustreapi_json.c.
Referenced by llapi_hsm_log_error().
{
        struct llapi_json_item_list     *list;
        struct llapi_json_item          *new_item;
        size_t len;
        if (json_items == NULL || *json_items == NULL)
                return -EINVAL;
        if (val == NULL)
                return -EINVAL;
        list = *json_items;
        new_item = calloc(1, sizeof(*new_item));
        if (new_item == NULL)
                return -ENOMEM;
        len = strlen(key) + 1;
        new_item->lji_key = calloc(len, sizeof(char));
        if (new_item->lji_key == NULL)
                return -ENOMEM;
        strlcpy(new_item->lji_key, key, len);
        new_item->lji_type = type;
        new_item->lji_next = NULL;
        switch (new_item->lji_type) {
        case LLAPI_JSON_INTEGER:
                new_item->lji_integer = *(int *)val;
                break;
        case LLAPI_JSON_BIGNUM:
                new_item->lji_u64 = *(__u64 *)val;
                break;
        case LLAPI_JSON_REAL:
                new_item->lji_real = *(double *)val;
                break;
        case LLAPI_JSON_STRING:
                len = strlen((char *)val) + 1;
                new_item->lji_string = calloc(len, sizeof(char));
                if (new_item->lji_string == NULL)
                        return -ENOMEM;
                strlcpy(new_item->lji_string, (char *)val, len);
                break;
        default:
                llapi_err_noerrno(LLAPI_MSG_ERROR, "Unknown JSON type: %d",
                                  new_item->lji_type);
                return -EINVAL;
        }
        if (list->ljil_item_count == 0) {
                list->ljil_items = new_item;
        } else {
                new_item->lji_next = list->ljil_items;
                list->ljil_items = new_item;
        }
        list->ljil_item_count++;
        return 0;
}
int llapi_json_destroy_list (struct llapi_json_item_list ** json_items)
Deallocate a list of JSON items.
Parameters:
json_items Item list handle, deallocated here
Return values:
0 on success.
-errno on error.
Definition at line 207 of file liblustreapi_json.c.
Referenced by llapi_hsm_log_error().
{
        int                             i;
        struct llapi_json_item_list     *list;
        struct llapi_json_item          *cur_item;
        struct llapi_json_item          *last_item;
        if (json_items == NULL || *json_items == NULL)
                return -EINVAL;
        list = *json_items;
        cur_item = list->ljil_items;
        for (i = 0; i < list->ljil_item_count; i++) {
                if (cur_item == NULL) {
                        llapi_err_noerrno(LLAPI_MSG_ERROR,
                                          "%d json items but %d is NULL!",
                                          list->ljil_item_count, i);
                        return -EINVAL;
                }
                if (cur_item->lji_key != NULL)
                        free(cur_item->lji_key);
                if (cur_item->lji_type == LLAPI_JSON_STRING
                    && cur_item->lji_string != NULL)
                        free(cur_item->lji_string);
                last_item = cur_item;
                cur_item = last_item->lji_next;
                free(last_item);
        }
        free(list);
        *json_items = NULL;
        return 0;
}
int llapi_json_init_list (struct llapi_json_item_list ** json_items)
Create a list to hold JSON items.
Parameters:
[out] json_items Item list handle, allocated here
Return values:
0 on success.
-errno on error.
Definition at line 186 of file liblustreapi_json.c.
Referenced by llapi_hsm_log_error().
{
        struct llapi_json_item_list     *new_list;
        new_list = calloc(1, sizeof(*new_list));
        if (new_list == NULL)
                return -ENOMEM;
        new_list->ljil_item_count = 0;
        *json_items = new_list;
        return 0;
}
int llapi_json_write_list (struct llapi_json_item_list ** json_items, FILE * fp)
Write a list of JSON items to a filehandle.
Parameters:
json_items list of JSON items to be written
fp open filehandle to use for write
Return values:
0 on success.
-errno on error.
Definition at line 114 of file liblustreapi_json.c.
{
        int                             i;
        char                            *escaped_string = NULL;
        struct llapi_json_item_list     *list;
        struct llapi_json_item          *item;
        if (json_items == NULL || *json_items == NULL)
                return -EINVAL;
        list = *json_items;
        item = list->ljil_items;
        fprintf(fp, "{");
        for (i = 0; i < list->ljil_item_count; i++) {
                if (item == NULL) {
                        llapi_err_noerrno(LLAPI_MSG_ERROR,
                                          "%d json items but %d is NULL!",
                                          list->ljil_item_count, i);
                        /* Don't bomb out here so that we still emit
                         * valid JSON. */
                        break;
                }
                fprintf(fp, "\"%s\": ", item->lji_key);
                switch (item->lji_type) {
                case LLAPI_JSON_INTEGER:
                        fprintf(fp, "%d", item->lji_integer);
                        break;
                case LLAPI_JSON_BIGNUM:
                        fprintf(fp, "%llu", (unsigned long long)item->lji_u64);
                        break;
                case LLAPI_JSON_REAL:
                        fprintf(fp, "%f", item->lji_real);
                        break;
                case LLAPI_JSON_STRING:
                        if (llapi_json_escape_string(&escaped_string,
                                                     item->lji_string) < 0) {
                                if (escaped_string != NULL)
                                        free(escaped_string);
                                return -errno;
                        }
                        fprintf(fp, "\"%s\"", escaped_string);
                        if (escaped_string != NULL)
                                free(escaped_string);
                        break;
                default:
                        llapi_err_noerrno(LLAPI_MSG_ERROR,
                                    "Invalid item type: %d", item->lji_type);
                        /* Ensure valid JSON */
                        fprintf(fp, "\"\"");
                        break;
                }
                if (i < list->ljil_item_count - 1)
                        fprintf(fp, ", ");
                item = item->lji_next;
        }
        fprintf(fp, "}\n");
        return 0;
}
int llapi_lease_check (int fd)
Check if a lease is still set on a file.
Parameters:
fd File to check the lease on.
Return values:
lease type if present (LL_LEASE_READ or LL_LEASE_WRITE).
0 if no lease is present.
-errno on error.
Definition at line 82 of file liblustreapi_lease.c.
{
        int rc;
        rc = ioctl(fd, LL_IOC_GET_LEASE);
        if (rc < 0) {
                rc = -errno;
                llapi_error(LLAPI_MSG_ERROR, rc, "cannot check lease");
        }
        return rc;
}
int llapi_lease_get (int fd, int mode)
Get a lease on an open file.
Parameters:
fd File to get the lease on.
mode Lease mode, either LL_LEASE_RDLCK or LL_LEASE_WRLCK.
Return values:
0 on success.
-errno on error.
Definition at line 57 of file liblustreapi_lease.c.
{
        int rc;
        if (mode != LL_LEASE_RDLCK && mode != LL_LEASE_WRLCK)
                return -EINVAL;
        rc = ioctl(fd, LL_IOC_SET_LEASE, mode);
        if (rc < 0) {
                rc = -errno;
                llapi_error(LLAPI_MSG_ERROR, rc, "cannot get %s lease",
                            lease_mode2str(mode));
        }
        return rc;
}
int llapi_lease_put (int fd)
Remove a lease.
Parameters:
fd File to remove the lease from.
Return values:
type of the lease that was removed (LL_LEASE_READ or LL_LEASE_WRITE).
0 if no lease was present.
-errno on error.
Definition at line 103 of file liblustreapi_lease.c.
{
        int rc;
        rc = ioctl(fd, LL_IOC_SET_LEASE, LL_LEASE_UNLCK);
        if (rc < 0) {
                rc = -errno;
                llapi_error(LLAPI_MSG_ERROR, rc, "cannot put lease");
        }
        return rc;
}
int llapi_open_by_fid (const char * lustre_dir, const lustre_fid * fid, int flags)
Attempt to open a file with Lustre file identifier fid and return an open file descriptor.
Parameters:
[in] lustre_dir path within Lustre filesystem containing fid
[in] fid Lustre file identifier of file to open
[in] flags open() flags
Return values:
non-negative file descriptor on successful open
-1 if an error occurred
Definition at line 4554 of file liblustreapi.c.
{
        char mntdir[PATH_MAX];
        char path[PATH_MAX];
        int rc;
        rc = llapi_search_mounts(lustre_dir, 0, mntdir, NULL);
        if (rc != 0)
                return -1;
        snprintf(path, sizeof(path), "%s/.lustre/fid/"DFID, mntdir, PFID(fid));
        return open(path, flags);
}
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.