Lustre: lib
lib
Data Structures
struct l_wait_info
Defines
#define LWI_ON_SIGNAL_NOOP ((void (*)(void *))(-1))
#define LWI_TIMEOUT(time, cb, data)
#define LWI_TIMEOUT_INTERVAL(time, interval, cb, data)
#define LWI_TIMEOUT_INTR(time, time_cb, sig_cb, data)
#define LWI_TIMEOUT_INTR_ALL(time, time_cb, sig_cb, data)
#define LWI_INTR(cb, data) LWI_TIMEOUT_INTR(0, NULL, cb, data)
#define LUSTRE_FATAL_SIGS
#define add_wait_queue_exclusive_head(waitq, link)
wait_queue_t of Linux (version < 2.6.34) is a FIFO list for exclusively waiting threads, which is not always desirable because all threads will be waken up again and again, even user only needs a few of them to be active most time.
#define __l_wait_event(wq, condition, info, ret, l_add_wait)
#define l_wait_event(wq, condition, info)
#define l_wait_event_exclusive(wq, condition, info)
#define l_wait_event_exclusive_head(wq, condition, info)
#define l_wait_condition(wq, condition)
#define l_wait_condition_exclusive(wq, condition)
#define l_wait_condition_exclusive_head(wq, condition)
Functions
int target_pack_pool_reply (struct ptlrpc_request *req)
Packs current SLV and Limit into req.
int do_set_info_async (struct obd_import *imp, int opcode, int version, size_t keylen, void *key, size_t vallen, void *val, struct ptlrpc_request_set *set)
Send a remote set_info_async.
void target_send_reply (struct ptlrpc_request *req, int rc, int fail_id)
Define Documentation
#define add_wait_queue_exclusive_head (waitq, link)
Value:
{                                                               \
        unsigned long flags;                                    \
                                                                \
        spin_lock_irqsave(&((waitq)->lock), flags);             \
        __add_wait_queue_exclusive(waitq, link);                \
        spin_unlock_irqrestore(&((waitq)->lock), flags);        \
}
wait_queue_t of Linux (version < 2.6.34) is a FIFO list for exclusively waiting threads, which is not always desirable because all threads will be waken up again and again, even user only needs a few of them to be active most time.
This is not good for performance because cache can be polluted by different threads.
LIFO list can resolve this problem because we always wakeup the most recent active thread by default.
NB: please don't call non-exclusive & exclusive wait on the same waitq if add_wait_queue_exclusive_head is used.
Definition at line 240 of file lustre_lib.h.
#define l_wait_condition (wq, condition)
Value:
({                                                              \
        struct l_wait_info lwi = { 0 };                         \
        l_wait_event(wq, condition, &lwi);                      \
})
Definition at line 359 of file lustre_lib.h.
#define l_wait_condition_exclusive (wq, condition)
Value:
({                                                              \
        struct l_wait_info lwi = { 0 };                         \
        l_wait_event_exclusive(wq, condition, &lwi);            \
})
Definition at line 365 of file lustre_lib.h.
#define l_wait_condition_exclusive_head (wq, condition)
Value:
({                                                              \
        struct l_wait_info lwi = { 0 };                         \
        l_wait_event_exclusive_head(wq, condition, &lwi);       \
})
Definition at line 371 of file lustre_lib.h.
#define l_wait_event (wq, condition, info)
Value:
({                                                              \
        int                 __ret;                              \
        struct l_wait_info *__info = (info);                    \
                                                                \
        __l_wait_event(wq, condition, __info,                   \
                       __ret, add_wait_queue);                  \
        __ret;                                                  \
})
Definition at line 329 of file lustre_lib.h.
#define l_wait_event_exclusive (wq, condition, info)
Value:
({                                                              \
        int                 __ret;                              \
        struct l_wait_info *__info = (info);                    \
                                                                \
        __l_wait_event(wq, condition, __info,                   \
                       __ret, add_wait_queue_exclusive);        \
        __ret;                                                  \
})
Definition at line 339 of file lustre_lib.h.
#define l_wait_event_exclusive_head (wq, condition, info)
Value:
({                                                              \
        int                 __ret;                              \
        struct l_wait_info *__info = (info);                    \
                                                                \
        __l_wait_event(wq, condition, __info,                   \
                       __ret, add_wait_queue_exclusive_head);   \
        __ret;                                                  \
})
Definition at line 349 of file lustre_lib.h.
#define LUSTRE_FATAL_SIGS
Value:
(sigmask(SIGKILL) | sigmask(SIGINT) | sigmask(SIGTERM) | \
         sigmask(SIGQUIT) | sigmask(SIGALRM))
Definition at line 211 of file lustre_lib.h.
#define LWI_TIMEOUT (time, cb, data)
Value:
((struct l_wait_info) {                         \
        .lwi_timeout    = time,                 \
        .lwi_on_timeout = cb,                   \
        .lwi_cb_data    = data,                 \
        .lwi_interval   = 0,                    \
        .lwi_allow_intr = 0                     \
})
Definition at line 171 of file lustre_lib.h.
#define LWI_TIMEOUT_INTERVAL (time, interval, cb, data)
Value:
((struct l_wait_info) {                                 \
        .lwi_timeout    = time,                         \
        .lwi_on_timeout = cb,                           \
        .lwi_cb_data    = data,                         \
        .lwi_interval   = interval,                     \
        .lwi_allow_intr = 0                             \
})
Definition at line 180 of file lustre_lib.h.
#define LWI_TIMEOUT_INTR (time, time_cb, sig_cb, data)
Value:
((struct l_wait_info) {                                 \
        .lwi_timeout    = time,                         \
        .lwi_on_timeout = time_cb,                      \
        .lwi_on_signal  = sig_cb,                       \
        .lwi_cb_data    = data,                         \
        .lwi_interval   = 0,                            \
        .lwi_allow_intr = 0                             \
})
Definition at line 189 of file lustre_lib.h.
#define LWI_TIMEOUT_INTR_ALL (time, time_cb, sig_cb, data)
Value:
((struct l_wait_info) {                                         \
        .lwi_timeout    = time,                                 \
        .lwi_on_timeout = time_cb,                              \
        .lwi_on_signal  = sig_cb,                               \
        .lwi_cb_data    = data,                                 \
        .lwi_interval   = 0,                                    \
        .lwi_allow_intr = 1                                     \
})
Definition at line 199 of file lustre_lib.h.
Function Documentation
int do_set_info_async (struct obd_import * imp, int opcode, int version, size_t keylen, void * key, size_t vallen, void * val, struct ptlrpc_request_set * set)
Send a remote set_info_async.
This may go from client to server or server to client.
Definition at line 1574 of file pack_generic.c.
References ptlrpc_check_set(), ptlrpc_queue_wait(), ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_set_add_req(), req_capsule_client_get(), req_capsule_set_size(), and ptlrpc_request::rq_pill.
{
        struct ptlrpc_request *req;
        char                  *tmp;
        int                    rc;
        ENTRY;
        req = ptlrpc_request_alloc(imp, &RQF_OBD_SET_INFO);
        if (req == NULL)
                RETURN(-ENOMEM);
        req_capsule_set_size(&req->rq_pill, &RMF_SETINFO_KEY,
                             RCL_CLIENT, keylen);
        req_capsule_set_size(&req->rq_pill, &RMF_SETINFO_VAL,
                             RCL_CLIENT, vallen);
        rc = ptlrpc_request_pack(req, version, opcode);
        if (rc) {
                ptlrpc_request_free(req);
                RETURN(rc);
        }
        tmp = req_capsule_client_get(&req->rq_pill, &RMF_SETINFO_KEY);
        memcpy(tmp, key, keylen);
        tmp = req_capsule_client_get(&req->rq_pill, &RMF_SETINFO_VAL);
        memcpy(tmp, val, vallen);
        ptlrpc_request_set_replen(req);
        if (set) {
                ptlrpc_set_add_req(set, req);
                ptlrpc_check_set(NULL, set);
        } else {
                rc = ptlrpc_queue_wait(req);
                ptlrpc_req_finished(req);
        }
        RETURN(rc);
}
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.