Lustre: Match entries
Match entries
[LNet]
A match entry (abbreviated as ME) describes a set of criteria to accept incoming requests.
Enumerations
enum lnet_unlink_t { LNET_RETAIN = 0, LNET_UNLINK }
Specifies whether the match entry or memory descriptor should be unlinked automatically (LNET_UNLINK) or not (LNET_RETAIN).
enum lnet_ins_pos_t { LNET_INS_BEFORE, LNET_INS_AFTER, LNET_INS_LOCAL }
Values of the type lnet_ins_pos_t are used to control where a new match entry is inserted.
Functions
int LNetMEAttach (unsigned int portal, lnet_process_id_t match_id_in, __u64 match_bits_in, __u64 ignore_bits_in, lnet_unlink_t unlink_in, lnet_ins_pos_t pos_in, lnet_handle_me_t *handle_out)
Create and attach a match entry to the match list of portal.
int LNetMEInsert (lnet_handle_me_t current_in, lnet_process_id_t match_id_in, __u64 match_bits_in, __u64 ignore_bits_in, lnet_unlink_t unlink_in, lnet_ins_pos_t position_in, lnet_handle_me_t *handle_out)
Create and a match entry and insert it before or after the ME pointed to by current_meh.
int LNetMEUnlink (lnet_handle_me_t current_in)
Unlink a match entry from its match list.
Detailed Description
A match entry (abbreviated as ME) describes a set of criteria to accept incoming requests.
A portal is essentially a match list plus a set of attributes. A match list is a chain of MEs. Each ME includes a pointer to a memory descriptor and a set of match criteria. The match criteria can be used to reject incoming requests based on process ID or the match bits provided in the request. MEs can be dynamically inserted into a match list by LNetMEAttach() and LNetMEInsert(), and removed from its list by LNetMEUnlink().
Enumeration Type Documentation
enum lnet_ins_pos_t
Values of the type lnet_ins_pos_t are used to control where a new match entry is inserted.
The value LNET_INS_BEFORE is used to insert the new entry before the current entry or before the head of the list. The value LNET_INS_AFTER is used to insert the new entry after the current entry or after the last item in the list.
Enumerator:
LNET_INS_BEFORE
insert ME before current position or head of the list
LNET_INS_AFTER
insert ME after current position or tail of the list
LNET_INS_LOCAL
attach ME at tail of local CPU partition ME list
Definition at line 329 of file types.h.
             {
        LNET_INS_BEFORE,
        LNET_INS_AFTER,
        LNET_INS_LOCAL
} lnet_ins_pos_t;
Function Documentation
int LNetMEAttach (unsigned int portal, lnet_process_id_t match_id, __u64 match_bits, __u64 ignore_bits, lnet_unlink_t unlink, lnet_ins_pos_t pos, lnet_handle_me_t * handle)
Create and attach a match entry to the match list of portal.
The new ME is empty, i.e. not associated with a memory descriptor. LNetMDAttach() can be used to attach a MD to an empty ME.
Parameters:
portal The portal table index where the ME should be attached.
match_id Specifies the match criteria for the process ID of the requester. The constants LNET_PID_ANY and LNET_NID_ANY can be used to wildcard either of the identifiers in the lnet_process_id_t structure.
match_bits,ignore_bits Specify the match criteria to apply to the match bits in the incoming request. The ignore bits are used to mask out insignificant bits in the incoming match bits. The resulting bits are then compared to the ME's match bits to determine if the incoming request meets the match criteria.
unlink Indicates whether the ME should be unlinked when the memory descriptor associated with it is unlinked (Note that the check for unlinking a ME only occurs when the memory descriptor is unlinked.). Valid values are LNET_RETAIN and LNET_UNLINK.
pos Indicates whether the new ME should be prepended or appended to the match list. Allowed constants: LNET_INS_BEFORE, LNET_INS_AFTER.
handle On successful returns, a handle to the newly created ME object is saved here. This handle can be used later in LNetMEInsert(), LNetMEUnlink(), or LNetMDAttach() functions.
Return values:
0 On success.
-EINVAL If portal is invalid.
-ENOMEM If new ME object cannot be allocated.
Definition at line 76 of file lib-me.c.
References LNET_INS_AFTER, and LNET_INS_LOCAL.
Referenced by ptl_send_rpc(), ptlrpc_register_bulk(), and ptlrpc_register_rqbd().
{
        struct lnet_match_table *mtable;
        struct lnet_me          *me;
        struct list_head        *head;
        LASSERT(the_lnet.ln_refcount > 0);
        if ((int)portal >= the_lnet.ln_nportals)
                return -EINVAL;
        mtable = lnet_mt_of_attach(portal, match_id,
                                   match_bits, ignore_bits, pos);
        if (mtable == NULL) /* can't match portal type */
                return -EPERM;
        me = lnet_me_alloc();
        if (me == NULL)
                return -ENOMEM;
        lnet_res_lock(mtable->mt_cpt);
        me->me_portal = portal;
        me->me_match_id = match_id;
        me->me_match_bits = match_bits;
        me->me_ignore_bits = ignore_bits;
        me->me_unlink = unlink;
        me->me_md = NULL;
        lnet_res_lh_initialize(the_lnet.ln_me_containers[mtable->mt_cpt],
                               &me->me_lh);
        if (ignore_bits != 0)
                head = &mtable->mt_mhash[LNET_MT_HASH_IGNORE];
        else
                head = lnet_mt_match_head(mtable, match_id, match_bits);
        me->me_pos = head - &mtable->mt_mhash[0];
        if (pos == LNET_INS_AFTER || pos == LNET_INS_LOCAL)
                list_add_tail(&me->me_list, head);
        else
                list_add(&me->me_list, head);
        lnet_me2handle(handle, me);
        lnet_res_unlock(mtable->mt_cpt);
        return 0;
}
int LNetMEInsert (lnet_handle_me_t current_meh, lnet_process_id_t match_id, __u64 match_bits, __u64 ignore_bits, lnet_unlink_t unlink, lnet_ins_pos_t pos, lnet_handle_me_t * handle)
Create and a match entry and insert it before or after the ME pointed to by current_meh.
The new ME is empty, i.e. not associated with a memory descriptor. LNetMDAttach() can be used to attach a MD to an empty ME.
This function is identical to LNetMEAttach() except for the position where the new ME is inserted.
Parameters:
current_meh A handle for a ME. The new ME will be inserted immediately before or immediately after this ME.
match_id,match_bits,ignore_bits,unlink,pos,handle See the discussion for LNetMEAttach().
Return values:
0 On success.
-ENOMEM If new ME object cannot be allocated.
-ENOENT If current_meh does not point to a valid match entry.
Definition at line 147 of file lib-me.c.
References LNET_INS_AFTER, and LNET_INS_LOCAL.
{
        struct lnet_me          *current_me;
        struct lnet_me          *new_me;
        struct lnet_portal      *ptl;
        int                     cpt;
        LASSERT(the_lnet.ln_refcount > 0);
        if (pos == LNET_INS_LOCAL)
                return -EPERM;
        new_me = lnet_me_alloc();
        if (new_me == NULL)
                return -ENOMEM;
        cpt = lnet_cpt_of_cookie(current_meh.cookie);
        lnet_res_lock(cpt);
        current_me = lnet_handle2me(&current_meh);
        if (current_me == NULL) {
                lnet_me_free(new_me);
                lnet_res_unlock(cpt);
                return -ENOENT;
        }
        LASSERT(current_me->me_portal < the_lnet.ln_nportals);
        ptl = the_lnet.ln_portals[current_me->me_portal];
        if (lnet_ptl_is_unique(ptl)) {
                /* nosense to insertion on unique portal */
                lnet_me_free(new_me);
                lnet_res_unlock(cpt);
                return -EPERM;
        }
        new_me->me_pos = current_me->me_pos;
        new_me->me_portal = current_me->me_portal;
        new_me->me_match_id = match_id;
        new_me->me_match_bits = match_bits;
        new_me->me_ignore_bits = ignore_bits;
        new_me->me_unlink = unlink;
        new_me->me_md = NULL;
        lnet_res_lh_initialize(the_lnet.ln_me_containers[cpt], &new_me->me_lh);
        if (pos == LNET_INS_AFTER)
                list_add(&new_me->me_list, &current_me->me_list);
        else
                list_add_tail(&new_me->me_list, &current_me->me_list);
        lnet_me2handle(handle, new_me);
        lnet_res_unlock(cpt);
        return 0;
}
int LNetMEUnlink (lnet_handle_me_t meh)
Unlink a match entry from its match list.
This operation also releases any resources associated with the ME. If a memory descriptor is attached to the ME, then it will be unlinked as well and an unlink event will be generated. It is an error to use the ME handle after calling LNetMEUnlink().
Parameters:
meh A handle for the ME to be unlinked.
Return values:
0 On success.
-ENOENT If meh does not point to a valid ME.
See also:
LNetMDUnlink() for the discussion on delivering unlink event.
Definition at line 227 of file lib-me.c.
Referenced by ptl_send_rpc(), ptlrpc_register_bulk(), and ptlrpc_register_rqbd().
{
        lnet_me_t       *me;
        lnet_libmd_t    *md;
        lnet_event_t    ev;
        int             cpt;
        LASSERT(the_lnet.ln_refcount > 0);
        cpt = lnet_cpt_of_cookie(meh.cookie);
        lnet_res_lock(cpt);
        me = lnet_handle2me(&meh);
        if (me == NULL) {
                lnet_res_unlock(cpt);
                return -ENOENT;
        }
        md = me->me_md;
        if (md != NULL) {
                md->md_flags |= LNET_MD_FLAG_ABORTED;
                if (md->md_eq != NULL && md->md_refcount == 0) {
                        lnet_build_unlink_event(md, &ev);
                        lnet_eq_enqueue_event(md->md_eq, &ev);
                }
        }
        lnet_me_unlink(me);
        lnet_res_unlock(cpt);
        return 0;
}
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.