Lustre: LDLM HANDLES
LDLM HANDLES
Ways to get hold of locks without any addresses.
Functions
void ldlm_lock2handle (const struct ldlm_lock *lock, struct lustre_handle *lockh)
Fills in handle for LDLM lock lock into supplied lockh Does not take any references.
struct ldlm_lock * __ldlm_handle2lock (const struct lustre_handle *handle, __u64 flags)
Obtain a lock reference by handle.
Detailed Description
Ways to get hold of locks without any addresses.
Function Documentation
struct ldlm_lock* __ldlm_handle2lock (const struct lustre_handle * handle, __u64 flags) [read]
Obtain a lock reference by handle.
if flags: atomically get the lock and set the flags. Return NULL if flag already set
Definition at line 594 of file ldlm_lock.c.
References ldlm_lock::l_flags, ldlm_lock::l_reference, ldlm_lock::l_resource, LDLM_LOCK_PUT, lock_res_and_lock(), and unlock_res_and_lock().
Referenced by ldlm_lock_decref(), and ldlm_lock_decref_and_cancel().
{
        struct ldlm_lock *lock;
        ENTRY;
        LASSERT(handle);
        lock = class_handle2object(handle->cookie, NULL);
        if (lock == NULL)
                RETURN(NULL);
        /* It's unlikely but possible that someone marked the lock as
         * destroyed after we did handle2object on it */
        if ((flags == 0) && !ldlm_is_destroyed(lock)) {
                lu_ref_add(&lock->l_reference, "handle", current);
                RETURN(lock);
        }
        lock_res_and_lock(lock);
        LASSERT(lock->l_resource != NULL);
        lu_ref_add_atomic(&lock->l_reference, "handle", current);
        if (unlikely(ldlm_is_destroyed(lock))) {
                unlock_res_and_lock(lock);
                CDEBUG(D_INFO, "lock already destroyed: lock %p\n", lock);
                LDLM_LOCK_PUT(lock);
                RETURN(NULL);
        }
        /* If we're setting flags, make sure none of them are already set. */
        if (flags != 0) {
                if ((lock->l_flags & flags) != 0) {
                        unlock_res_and_lock(lock);
                        LDLM_LOCK_PUT(lock);
                        RETURN(NULL);
                }
                lock->l_flags |= flags;
        }
        unlock_res_and_lock(lock);
        RETURN(lock);
}
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.