Lustre: Events and event queues
Events and event queues
[LNet]
Event queues (abbreviated as EQ) are used to log operations performed on local MDs.
Data Structures
struct lnet_event_t
Information about an event on a MD.
Defines
#define LNET_SEQ_BASETYPE long
#define LNET_SEQ_GT(a, b) (((signed LNET_SEQ_BASETYPE)((a) - (b))) > 0)
#define LNET_EQ_HANDLER_NONE NULL
Typedefs
typedef unsigned LNET_SEQ_BASETYPE lnet_seq_t
typedef void(* lnet_eq_handler_t)(lnet_event_t *event)
Event queue handler function type.
Enumerations
enum lnet_event_kind_t {
LNET_EVENT_GET = 1, LNET_EVENT_PUT, LNET_EVENT_REPLY, LNET_EVENT_ACK,
LNET_EVENT_SEND, LNET_EVENT_UNLINK
}
Six types of events can be logged in an event queue.
Functions
int LNetEQAlloc (unsigned int count_in, lnet_eq_handler_t handler, lnet_handle_eq_t *handle_out)
Create an event queue that has room for count number of events.
int LNetEQFree (lnet_handle_eq_t eventq_in)
Release the resources associated with an event queue if it's idle; otherwise do nothing and it's up to the user to try again.
int LNetEQGet (lnet_handle_eq_t eventq_in, lnet_event_t *event_out)
A nonblocking function that can be used to get the next event in an EQ.
int LNetEQWait (lnet_handle_eq_t eventq_in, lnet_event_t *event_out)
Block the calling process until there is an event in the EQ.
int LNetEQPoll (lnet_handle_eq_t *eventqs_in, int neq_in, int timeout_ms, lnet_event_t *event_out, int *which_eq_out)
Block the calling process until there's an event from a set of EQs or timeout happens.
Detailed Description
Event queues (abbreviated as EQ) are used to log operations performed on local MDs.
In particular, they signal the completion of a data transmission into or out of a MD. They can also be used to hold acknowledgments for completed PUT operations and indicate when a MD has been unlinked. Multiple MDs can share a single EQ. An EQ may have an optional event handler associated with it. If an event handler exists, it will be run for each event that is deposited into the EQ.
In addition to the lnet_handle_eq_t, the LNet API defines two types associated with events: The lnet_event_kind_t defines the kinds of events that can be stored in an EQ. The lnet_event_t defines a structure that holds the information about with an event.
There are five functions for dealing with EQs: LNetEQAlloc() is used to create an EQ and allocate the resources needed, while LNetEQFree() releases these resources and free the EQ. LNetEQGet() retrieves the next event from an EQ, and LNetEQWait() can be used to block a process until an EQ has at least one event. LNetEQPoll() can be used to test or wait on multiple EQs.
Typedef Documentation
typedef void(* lnet_eq_handler_t)(lnet_event_t *event)
Event queue handler function type.
The EQ handler runs for each event that is deposited into the EQ. The handler is supplied with a pointer to the event that triggered the handler invocation.
The handler must not block, must be reentrant, and must not call any LNet API functions. It should return as quickly as possible.
Definition at line 628 of file types.h.
Enumeration Type Documentation
enum lnet_event_kind_t
Six types of events can be logged in an event queue.
Enumerator:
LNET_EVENT_GET
An incoming GET operation has completed on the MD.
LNET_EVENT_PUT
An incoming PUT operation has completed on the MD.
The underlying layers will not alter the memory (on behalf of this operation) once this event has been logged.
LNET_EVENT_REPLY
A REPLY operation has completed.
This event is logged after the data (if any) from the REPLY has been written into the MD.
LNET_EVENT_ACK
An acknowledgment has been received.
LNET_EVENT_SEND
An outgoing send (PUT or GET) operation has completed.
This event is logged after the entire buffer has been sent and it is safe for the caller to reuse the buffer.
Note:
The LNET_EVENT_SEND doesn't guarantee message delivery. It can happen even when the message has not yet been put out on wire.
It's unsafe to assume that in an outgoing GET operation the LNET_EVENT_SEND event would happen before the LNET_EVENT_REPLY event. The same holds for LNET_EVENT_SEND and LNET_EVENT_ACK events in an outgoing PUT operation.
LNET_EVENT_UNLINK
A MD has been unlinked.
Note that LNetMDUnlink() does not necessarily trigger an LNET_EVENT_UNLINK event.
See also:
LNetMDUnlink
Definition at line 504 of file types.h.
             {
        LNET_EVENT_GET          = 1,
        LNET_EVENT_PUT,
        LNET_EVENT_REPLY,
        LNET_EVENT_ACK,
        LNET_EVENT_SEND,
        LNET_EVENT_UNLINK,
} lnet_event_kind_t;
Function Documentation
int LNetEQAlloc (unsigned int count, lnet_eq_handler_t callback, lnet_handle_eq_t * handle)
Create an event queue that has room for count number of events.
The event queue is circular and older events will be overwritten by new ones if they are not removed in time by the user using the functions LNetEQGet(), LNetEQWait(), or LNetEQPoll(). It is up to the user to determine the appropriate size of the event queue to prevent this loss of events. Note that when EQ handler is specified in callback, no event loss can happen, since the handler is run for each event deposited into the EQ.
Parameters:
count The number of events to be stored in the event queue. It will be rounded up to the next power of two.
callback A handler function that runs when an event is deposited into the EQ. The constant value LNET_EQ_HANDLER_NONE can be used to indicate that no event handler is desired.
handle On successful return, this location will hold a handle for the newly created EQ.
Return values:
0 On success.
-EINVAL If an parameter is not valid.
-ENOMEM If memory for the EQ can't be allocated.
See also:
lnet_eq_handler_t for the discussion on EQ handler semantics.
Definition at line 70 of file lib-eq.c.
{
        lnet_eq_t     *eq;
        LASSERT (the_lnet.ln_refcount > 0);
        /* We need count to be a power of 2 so that when eq_{enq,deq}_seq
         * overflow, they don't skip entries, so the queue has the same
         * apparent capacity at all times */
        if (count)
                count = roundup_pow_of_two(count);
        if (callback != LNET_EQ_HANDLER_NONE && count != 0) {
                CWARN("EQ callback is guaranteed to get every event, "
                      "do you still want to set eqcount %d for polling "
                      "event which will have locking overhead? "
                      "Please contact with developer to confirm\n", count);
        }
        /* count can be 0 if only need callback, we can eliminate
         * overhead of enqueue event */
        if (count == 0 && callback == LNET_EQ_HANDLER_NONE)
                return -EINVAL;
        eq = lnet_eq_alloc();
        if (eq == NULL)
                return -ENOMEM;
        if (count != 0) {
                LIBCFS_ALLOC(eq->eq_events, count * sizeof(lnet_event_t));
                if (eq->eq_events == NULL)
                        goto failed;
                /* NB allocator has set all event sequence numbers to 0,
                 * so all them should be earlier than eq_deq_seq */
        }
        eq->eq_deq_seq = 1;
        eq->eq_enq_seq = 1;
        eq->eq_size = count;
        eq->eq_callback = callback;
        eq->eq_refs = cfs_percpt_alloc(lnet_cpt_table(),
                                       sizeof(*eq->eq_refs[0]));
        if (eq->eq_refs == NULL)
                goto failed;
        /* MUST hold both exclusive lnet_res_lock */
        lnet_res_lock(LNET_LOCK_EX);
        /* NB: hold lnet_eq_wait_lock for EQ link/unlink, so we can do
         * both EQ lookup and poll event with only lnet_eq_wait_lock */
        lnet_eq_wait_lock();
        lnet_res_lh_initialize(&the_lnet.ln_eq_container, &eq->eq_lh);
        list_add(&eq->eq_list, &the_lnet.ln_eq_container.rec_active);
        lnet_eq_wait_unlock();
        lnet_res_unlock(LNET_LOCK_EX);
        lnet_eq2handle(handle, eq);
        return 0;
failed:
        if (eq->eq_events != NULL)
                LIBCFS_FREE(eq->eq_events, count * sizeof(lnet_event_t));
        if (eq->eq_refs != NULL)
                cfs_percpt_free(eq->eq_refs);
        lnet_eq_free(eq);
        return -ENOMEM;
}
int LNetEQFree (lnet_handle_eq_t eqh)
Release the resources associated with an event queue if it's idle; otherwise do nothing and it's up to the user to try again.
Parameters:
eqh A handle for the event queue to be released.
Return values:
0 If the EQ is not in use and freed.
-ENOENT If eqh does not point to a valid EQ.
-EBUSY If the EQ is still in use by some MDs.
Definition at line 156 of file lib-eq.c.
{
        struct lnet_eq  *eq;
        lnet_event_t    *events = NULL;
        int             **refs = NULL;
        int             *ref;
        int             rc = 0;
        int             size = 0;
        int             i;
        LASSERT(the_lnet.ln_refcount > 0);
        lnet_res_lock(LNET_LOCK_EX);
        /* NB: hold lnet_eq_wait_lock for EQ link/unlink, so we can do
         * both EQ lookup and poll event with only lnet_eq_wait_lock */
        lnet_eq_wait_lock();
        eq = lnet_handle2eq(&eqh);
        if (eq == NULL) {
                rc = -ENOENT;
                goto out;
        }
        cfs_percpt_for_each(ref, i, eq->eq_refs) {
                LASSERT(*ref >= 0);
                if (*ref == 0)
                        continue;
                CDEBUG(D_NET, "Event equeue (%d: %d) busy on destroy.\n",
                       i, *ref);
                rc = -EBUSY;
                goto out;
        }
        /* stash for free after lock dropped */
        events  = eq->eq_events;
        size    = eq->eq_size;
        refs    = eq->eq_refs;
        lnet_res_lh_invalidate(&eq->eq_lh);
        list_del(&eq->eq_list);
        lnet_eq_free(eq);
 out:
        lnet_eq_wait_unlock();
        lnet_res_unlock(LNET_LOCK_EX);
        if (events != NULL)
                LIBCFS_FREE(events, size * sizeof(lnet_event_t));
        if (refs != NULL)
                cfs_percpt_free(refs);
        return rc;
}
int LNetEQGet (lnet_handle_eq_t eventq, lnet_event_t * event)
A nonblocking function that can be used to get the next event in an EQ.
If an event handler is associated with the EQ, the handler will run before this function returns successfully. The event is removed from the queue.
Parameters:
eventq A handle for the event queue.
event On successful return (1 or -EOVERFLOW), this location will hold the next event in the EQ.
Return values:
0 No pending event in the EQ.
1 Indicates success.
-ENOENT If eventq does not point to a valid EQ.
-EOVERFLOW Indicates success (i.e., an event is returned) and that at least one event between this event and the last event obtained from the EQ has been dropped due to limited space in the EQ.
Definition at line 290 of file lib-eq.c.
References LNetEQPoll().
{
        int which;
        return LNetEQPoll(&eventq, 1, 0,
                         event, &which);
}
int LNetEQPoll (lnet_handle_eq_t * eventqs, int neq, int timeout_ms, lnet_event_t * event, int * which)
Block the calling process until there's an event from a set of EQs or timeout happens.
If an event handler is associated with the EQ, the handler will run before this function returns successfully, in which case the corresponding event is consumed.
LNetEQPoll() provides a timeout to allow applications to poll, block for a fixed period, or block indefinitely.
Parameters:
eventqs,neq An array of EQ handles, and size of the array.
timeout_ms Time in milliseconds to wait for an event to occur on one of the EQs. The constant LNET_TIME_FOREVER can be used to indicate an infinite timeout.
event,which On successful return (1 or -EOVERFLOW), event will hold the next event in the EQs, and which will contain the index of the EQ from which the event was taken.
Return values:
0 No pending event in the EQs after timeout.
1 Indicates success.
-EOVERFLOW Indicates success (i.e., an event is returned) and that at least one event between this event and the last event obtained from the EQ indicated by which has been dropped due to limited space in the EQ.
-ENOENT If there's an invalid handle in eventqs.
Definition at line 392 of file lib-eq.c.
Referenced by LNetEQGet(), and LNetEQWait().
{
        int     wait = 1;
        int     rc;
        int     i;
        ENTRY;
        LASSERT (the_lnet.ln_refcount > 0);
        if (neq < 1)
                RETURN(-ENOENT);
        lnet_eq_wait_lock();
        for (;;) {
                for (i = 0; i < neq; i++) {
                        lnet_eq_t *eq = lnet_handle2eq(&eventqs[i]);
                        if (eq == NULL) {
                                lnet_eq_wait_unlock();
                                RETURN(-ENOENT);
                        }
                        rc = lnet_eq_dequeue_event(eq, event);
                        if (rc != 0) {
                                lnet_eq_wait_unlock();
                                *which = i;
                                RETURN(rc);
                        }
                }
                if (wait == 0)
                        break;
                /*
                 * return value of lnet_eq_wait_locked:
                 * -1 : did nothing and it's sure no new event
                 *  1 : sleep inside and wait until new event
                 *  0 : don't want to wait anymore, but might have new event
                 *      so need to call dequeue again
                 */
                wait = lnet_eq_wait_locked(&timeout_ms);
                if (wait < 0) /* no new event */
                        break;
        }
        lnet_eq_wait_unlock();
        RETURN(0);
}
int LNetEQWait (lnet_handle_eq_t eventq, lnet_event_t * event)
Block the calling process until there is an event in the EQ.
If an event handler is associated with the EQ, the handler will run before this function returns successfully. This function returns the next event in the EQ and removes it from the EQ.
Parameters:
eventq A handle for the event queue.
event On successful return (1 or -EOVERFLOW), this location will hold the next event in the EQ.
Return values:
1 Indicates success.
-ENOENT If eventq does not point to a valid EQ.
-EOVERFLOW Indicates success (i.e., an event is returned) and that at least one event between this event and the last event obtained from the EQ has been dropped due to limited space in the EQ.
Definition at line 316 of file lib-eq.c.
References LNetEQPoll().
{
        int which;
        return LNetEQPoll(&eventq, 1, LNET_TIME_FOREVER,
                         event, &which);
}
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.