Lustre: ha
ha
Functions
int ptlrpc_replay (struct obd_import *imp)
int ptlrpc_resend (struct obd_import *imp)
Schedule resending of request on sending_list.
void ptlrpc_free_committed (struct obd_import *imp)
Iterates through replay_list on import and prunes all requests have transno smaller than last_committed for the import and don't have rq_replay set.
void ptlrpc_wake_delayed (struct obd_import *imp)
Go through all requests in delayed list and wake their threads for resending.
int ptlrpc_recover_import (struct obd_import *imp, char *new_uuid, int async)
int ptlrpc_set_import_active (struct obd_import *imp, int active)
Administratively active/deactive a client.
void ptlrpc_activate_import (struct obd_import *imp)
void ptlrpc_deactivate_import (struct obd_import *imp)
void ptlrpc_invalidate_import (struct obd_import *imp)
This function will invalidate the import, if necessary, then block for all the RPC completions, and finally notify the obd to invalidate its state (ie cancel locks, clear pending requests, etc).
void ptlrpc_fail_import (struct obd_import *imp, __u32 conn_cnt)
void ptlrpc_pinger_force (struct obd_import *imp)
Function Documentation
void ptlrpc_free_committed (struct obd_import * imp)
Iterates through replay_list on import and prunes all requests have transno smaller than last_committed for the import and don't have rq_replay set.
Since requests are sorted in transno order, stops when meetign first transno bigger than last_committed. caller must hold imp->imp_lock
Definition at line 2626 of file client.c.
References DEBUG_REQ, obd_import::imp_committed_list, obd_import::imp_generation, obd_import::imp_last_generation_checked, obd_import::imp_last_transno_checked, obd_import::imp_lock, obd_import::imp_obd, obd_import::imp_peer_committed_transno, obd_import::imp_replay_list, ptlrpc_request::rq_replay, ptlrpc_request::rq_replay_list, and ptlrpc_request::rq_transno.
Referenced by ptlrpc_abort_inflight().
{
        struct ptlrpc_request   *req, *saved;
        struct ptlrpc_request   *last_req = NULL; /* temporary fire escape */
        bool                     skip_committed_list = true;
        ENTRY;
        LASSERT(imp != NULL);
        assert_spin_locked(&imp->imp_lock);
        if (imp->imp_peer_committed_transno == imp->imp_last_transno_checked &&
            imp->imp_generation == imp->imp_last_generation_checked) {
                CDEBUG(D_INFO, "%s: skip recheck: last_committed "LPU64"\n",
                       imp->imp_obd->obd_name, imp->imp_peer_committed_transno);
                RETURN_EXIT;
        }
        CDEBUG(D_RPCTRACE, "%s: committing for last_committed "LPU64" gen %d\n",
               imp->imp_obd->obd_name, imp->imp_peer_committed_transno,
               imp->imp_generation);
        if (imp->imp_generation != imp->imp_last_generation_checked ||
            imp->imp_last_transno_checked == 0)
                skip_committed_list = false;
        imp->imp_last_transno_checked = imp->imp_peer_committed_transno;
        imp->imp_last_generation_checked = imp->imp_generation;
        list_for_each_entry_safe(req, saved, &imp->imp_replay_list,
                                     rq_replay_list) {
                /* XXX ok to remove when 1357 resolved - rread 05/29/03  */
                LASSERT(req != last_req);
                last_req = req;
                if (req->rq_transno == 0) {
                        DEBUG_REQ(D_EMERG, req, "zero transno during replay");
                        LBUG();
                }
                if (req->rq_import_generation < imp->imp_generation) {
                        DEBUG_REQ(D_RPCTRACE, req, "free request with old gen");
                        GOTO(free_req, 0);
                }
                /* not yet committed */
                if (req->rq_transno > imp->imp_peer_committed_transno) {
                        DEBUG_REQ(D_RPCTRACE, req, "stopping search");
                        break;
                }
                if (req->rq_replay) {
                        DEBUG_REQ(D_RPCTRACE, req, "keeping (FL_REPLAY)");
                        list_move_tail(&req->rq_replay_list,
                                           &imp->imp_committed_list);
                        continue;
                }
                DEBUG_REQ(D_INFO, req, "commit (last_committed "LPU64")",
                          imp->imp_peer_committed_transno);
free_req:
                ptlrpc_free_request(req);
        }
        if (skip_committed_list)
                GOTO(out, 0);
        list_for_each_entry_safe(req, saved, &imp->imp_committed_list,
                                     rq_replay_list) {
                LASSERT(req->rq_transno != 0);
                if (req->rq_import_generation < imp->imp_generation) {
                        DEBUG_REQ(D_RPCTRACE, req, "free stale open request");
                        ptlrpc_free_request(req);
                } else if (!req->rq_replay) {
                        DEBUG_REQ(D_RPCTRACE, req, "free closed open request");
                        ptlrpc_free_request(req);
                }
        }
out:
        EXIT;
}
int ptlrpc_resend (struct obd_import * imp)
Schedule resending of request on sending_list.
This is done after we completed replaying of requests and locks.
Definition at line 196 of file recover.c.
References obd_import::imp_lock, obd_import::imp_state, and ptlrpc_request::rq_list.
Referenced by ptlrpc_import_recovery_state_machine().
{
        struct ptlrpc_request *req, *next;
        ENTRY;
        /* As long as we're in recovery, nothing should be added to the sending
         * list, so we don't need to hold the lock during this iteration and
         * resend process.
         */
        /* Well... what if lctl recover is called twice at the same time?
         */
        spin_lock(&imp->imp_lock);
        if (imp->imp_state != LUSTRE_IMP_RECOVER) {
                spin_unlock(&imp->imp_lock);
                RETURN(-1);
        }
        list_for_each_entry_safe(req, next, &imp->imp_sending_list, rq_list) {
                LASSERTF((long)req > PAGE_CACHE_SIZE && req != LP_POISON,
                         "req %p bad\n", req);
                LASSERTF(req->rq_type != LI_POISON, "req %p freed\n", req);
                /* If the request is allowed to be sent during replay and it
                 * is not timeout yet, then it does not need to be resent. */
                if (!ptlrpc_no_resend(req) &&
                    (req->rq_timedout || !req->rq_allow_replay))
                        ptlrpc_resend_req(req);
        }
        spin_unlock(&imp->imp_lock);
        RETURN(0);
}
int ptlrpc_set_import_active (struct obd_import * imp, int active)
Administratively active/deactive a client.
This should only be called by the ioctl interface, currently
the lctl deactivate and activate commands
echo 0/1 >> /proc/osc/XXX/active
client umount -f (ll_umount_begin)
Definition at line 290 of file recover.c.
References obd_import::imp_lock, obd_import::imp_obd, and ptlrpc_invalidate_import().
{
        struct obd_device *obd = imp->imp_obd;
        int rc = 0;
        ENTRY;
        LASSERT(obd);
        /* When deactivating, mark import invalid, and abort in-flight
         * requests. */
        if (!active) {
                LCONSOLE_WARN("setting import %s INACTIVE by administrator "
                              "request\n", obd2cli_tgt(imp->imp_obd));
                /* set before invalidate to avoid messages about imp_inval
                 * set without imp_deactive in ptlrpc_import_delay_req */
                spin_lock(&imp->imp_lock);
                imp->imp_deactive = 1;
                spin_unlock(&imp->imp_lock);
                obd_import_event(imp->imp_obd, imp, IMP_EVENT_DEACTIVATE);
                ptlrpc_invalidate_import(imp);
        }
        /* When activating, mark import valid, and attempt recovery */
        if (active) {
                CDEBUG(D_HA, "setting import %s VALID\n",
                       obd2cli_tgt(imp->imp_obd));
                spin_lock(&imp->imp_lock);
                imp->imp_deactive = 0;
                spin_unlock(&imp->imp_lock);
                obd_import_event(imp->imp_obd, imp, IMP_EVENT_ACTIVATE);
                rc = ptlrpc_recover_import(imp, NULL, 0);
        }
        RETURN(rc);
}
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.