Lustre: Default AST handlers for local locks
Default AST handlers for local locks
[Lustre Distributed Lock Manager]
These AST handlers are typically used for server-side local locks and are also used by client-side lock handlers to perform minimum level base processing.
Functions
int ldlm_blocking_ast_nocheck (struct ldlm_lock *lock)
A helper to build a blocking AST function.
int ldlm_blocking_ast (struct ldlm_lock *lock, struct ldlm_lock_desc *desc, void *data, int flag)
Server blocking AST.
int ldlm_glimpse_ast (struct ldlm_lock *lock, void *reqp)
Implements ldlm_lock::l_glimpse_ast for extent locks acquired on the server.
int ldlm_completion_ast_async (struct ldlm_lock *lock, __u64 flags, void *data)
Implementation of ->l_completion_ast() for a client, that doesn't wait until lock is granted.
int ldlm_completion_ast (struct ldlm_lock *lock, __u64 flags, void *data)
Generic LDLM "completion" AST.
Detailed Description
These AST handlers are typically used for server-side local locks and are also used by client-side lock handlers to perform minimum level base processing.
Function Documentation
int ldlm_blocking_ast (struct ldlm_lock * lock, struct ldlm_lock_desc * desc, void * data, int flag)
Server blocking AST.
->l_blocking_ast() callback for LDLM locks acquired by server-side OBDs.
Parameters:
lock the lock which blocks a request or cancelling lock
desc unused
data unused
flag indicates whether this cancelling or blocking callback
Return values:
0
See also:
ldlm_blocking_ast_nocheck
Definition at line 354 of file ldlm_request.c.
References ldlm_lock::l_blocking_ast, ldlm_blocking_ast(), ldlm_blocking_ast_nocheck(), lock_res_and_lock(), and unlock_res_and_lock().
Referenced by ldlm_blocking_ast().
{
        ENTRY;
        if (flag == LDLM_CB_CANCELING) {
                /* Don't need to do anything here. */
                RETURN(0);
        }
        lock_res_and_lock(lock);
        /* Get this: if ldlm_blocking_ast is racing with intent_policy, such
         * that ldlm_blocking_ast is called just before intent_policy method
         * takes the lr_lock, then by the time we get the lock, we might not
         * be the correct blocking function anymore.  So check, and return
         * early, if so. */
        if (lock->l_blocking_ast != ldlm_blocking_ast) {
                unlock_res_and_lock(lock);
                RETURN(0);
        }
        RETURN(ldlm_blocking_ast_nocheck(lock));
}
int ldlm_blocking_ast_nocheck (struct ldlm_lock * lock)
A helper to build a blocking AST function.
Perform a common operation for blocking ASTs: defferred lock cancellation.
Parameters:
lock the lock blocking or canceling AST was called on
Return values:
0
See also:
mdt_blocking_ast
ldlm_blocking_ast
Definition at line 315 of file ldlm_request.c.
References ldlm_lock::l_readers, ldlm_cli_cancel(), ldlm_lock2handle(), and unlock_res_and_lock().
Referenced by ldlm_blocking_ast().
{
        int do_ast;
        ENTRY;
        ldlm_set_cbpending(lock);
        do_ast = (!lock->l_readers && !lock->l_writers);
        unlock_res_and_lock(lock);
        if (do_ast) {
                struct lustre_handle lockh;
                int rc;
                LDLM_DEBUG(lock, "already unused, calling ldlm_cli_cancel");
                ldlm_lock2handle(lock, &lockh);
                rc = ldlm_cli_cancel(&lockh, LCF_ASYNC);
                if (rc < 0)
                        CERROR("ldlm_cli_cancel: %d\n", rc);
        } else {
                LDLM_DEBUG(lock, "Lock still has references, will be "
                           "cancelled later");
        }
        RETURN(0);
}
int ldlm_completion_ast (struct ldlm_lock * lock, __u64 flags, void * data)
Generic LDLM "completion" AST.
This is called in several cases:
when a reply to an ENQUEUE RPC is received from the server (ldlm_cli_enqueue_fini()). Lock might be granted or not granted at this point (determined by flags);
when LDLM_CP_CALLBACK RPC comes to client to notify it that lock has been granted;
when ldlm_lock_match(LDLM_FL_LVB_READY) is about to wait until lock gets correct lvb;
to force all locks when resource is destroyed (cleanup_resource());
during lock conversion (not used currently).
If lock is not granted in the first case, this function waits until second or penultimate cases happen in some other thread.
Definition at line 230 of file ldlm_request.c.
References obd_import::imp_conn_cnt, obd_import::imp_lock, ldlm_lock::l_conn_export, ldlm_lock::l_last_activity, ldlm_lock::l_waitq, LDLM_FL_BLOCKED_MASK, and LDLM_FL_WAIT_NOREPROC.
{
        /* XXX ALLOCATE - 160 bytes */
        struct lock_wait_data lwd;
        struct obd_device *obd;
        struct obd_import *imp = NULL;
        struct l_wait_info lwi;
        __u32 timeout;
        int rc = 0;
        ENTRY;
        if (flags == LDLM_FL_WAIT_NOREPROC) {
                LDLM_DEBUG(lock, "client-side enqueue waiting on pending lock");
                goto noreproc;
        }
        if (!(flags & LDLM_FL_BLOCKED_MASK)) {
                wake_up(&lock->l_waitq);
                RETURN(0);
        }
        LDLM_DEBUG(lock, "client-side enqueue returned a blocked lock, "
                   "sleeping");
noreproc:
        obd = class_exp2obd(lock->l_conn_export);
        /* if this is a local lock, then there is no import */
        if (obd != NULL) {
                imp = obd->u.cli.cl_import;
        }
        timeout = ldlm_cp_timeout(lock);
        lwd.lwd_lock = lock;
        lock->l_last_activity = cfs_time_current_sec();
        if (ldlm_is_no_timeout(lock)) {
                LDLM_DEBUG(lock, "waiting indefinitely because of NO_TIMEOUT");
                lwi = LWI_INTR(interrupted_completion_wait, &lwd);
        } else {
                lwi = LWI_TIMEOUT_INTR(cfs_time_seconds(timeout),
                                       ldlm_expired_completion_wait,
                                       interrupted_completion_wait, &lwd);
        }
        if (imp != NULL) {
                spin_lock(&imp->imp_lock);
                lwd.lwd_conn_cnt = imp->imp_conn_cnt;
                spin_unlock(&imp->imp_lock);
        }
        if (ns_is_client(ldlm_lock_to_ns(lock)) &&
            OBD_FAIL_CHECK_RESET(OBD_FAIL_LDLM_INTR_CP_AST,
                                 OBD_FAIL_LDLM_CP_BL_RACE | OBD_FAIL_ONCE)) {
                ldlm_set_fail_loc(lock);
                rc = -EINTR;
        } else {
                /* Go to sleep until the lock is granted or cancelled. */
                rc = l_wait_event(lock->l_waitq,
                                  is_granted_or_cancelled(lock), &lwi);
        }
        if (rc) {
                LDLM_DEBUG(lock, "client-side enqueue waking up: failed (%d)",
                           rc);
                RETURN(rc);
        }
        RETURN(ldlm_completion_tail(lock, data));
}
int ldlm_completion_ast_async (struct ldlm_lock * lock, __u64 flags, void * data)
Implementation of ->l_completion_ast() for a client, that doesn't wait until lock is granted.
Suitable for locks enqueued through ptlrpcd, of other threads that cannot block for long.
Definition at line 188 of file ldlm_request.c.
References ldlm_lock::l_resource, ldlm_lock::l_waitq, LDLM_FL_BLOCKED_MASK, LDLM_FL_WAIT_NOREPROC, and ldlm_reprocess_all().
{
        ENTRY;
        if (flags == LDLM_FL_WAIT_NOREPROC) {
                LDLM_DEBUG(lock, "client-side enqueue waiting on pending lock");
                RETURN(0);
        }
        if (!(flags & LDLM_FL_BLOCKED_MASK)) {
                wake_up(&lock->l_waitq);
                RETURN(ldlm_completion_tail(lock, data));
        }
        LDLM_DEBUG(lock, "client-side enqueue returned a blocked lock, "
                   "going forward");
        ldlm_reprocess_all(lock->l_resource);
        RETURN(0);
}
int ldlm_glimpse_ast (struct ldlm_lock * lock, void * reqp)
Implements ldlm_lock::l_glimpse_ast for extent locks acquired on the server.
Returning -ELDLM_NO_LOCK_DATA actually works, but the reason for that is rather subtle: with OST-side locking, it may so happen that _all_ extent locks are held by the OST. If client wants to obtain the current file size it calls ll_glimpse_size(), and (as all locks are held only on the server), this dummy glimpse callback fires and does nothing. The client still receives the correct file size due to the following fragment of code in ldlm_cb_interpret():
if (rc == -ELDLM_NO_LOCK_DATA) { LDLM_DEBUG(lock, "lost race - client has a lock but no" "inode"); ldlm_res_lvbo_update(lock->l_resource, NULL, 1); }
That is, after the glimpse returns this error, ofd_lvbo_update() is called and returns the updated file attributes from the inode to the client.
See also comment in ofd_intent_policy() on why servers must set a non-NULL l_glimpse_ast when grabbing DLM locks. Otherwise, the server will assume that the object is in the process of being destroyed.
Parameters:
[in] lock DLM lock being glimpsed, unused
[in] reqp pointer to ptlrpc_request, unused
Return values:
-ELDLM_NO_LOCK_DATA to get attributes from disk object
Definition at line 407 of file ldlm_request.c.
{
        return -ELDLM_NO_LOCK_DATA;
}
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.