Lustre: cl_object_operations Struct Reference
cl_object_operations Struct Reference
[cl_object]
Operations implemented for each cl object layer.
#include <cl_object.h>
Data Fields
int(* coo_page_init)(const struct lu_env *env, struct cl_object *obj, struct cl_page *page, pgoff_t index)
Initialize page slice for this layer.
int(* coo_lock_init)(const struct lu_env *env, struct cl_object *obj, struct cl_lock *lock, const struct cl_io *io)
Initialize lock slice for this layer.
int(* coo_io_init)(const struct lu_env *env, struct cl_object *obj, struct cl_io *io)
Initialize io state for a given layer.
int(* coo_attr_get)(const struct lu_env *env, struct cl_object *obj, struct cl_attr *attr)
Fill portion of attr that this layer controls.
int(* coo_attr_update)(const struct lu_env *env, struct cl_object *obj, const struct cl_attr *attr, unsigned valid)
Update attributes.
int(* coo_conf_set)(const struct lu_env *env, struct cl_object *obj, const struct cl_object_conf *conf)
Update object configuration.
int(* coo_glimpse)(const struct lu_env *env, const struct cl_object *obj, struct ost_lvb *lvb)
Glimpse ast.
int(* coo_prune)(const struct lu_env *env, struct cl_object *obj)
Object prune method.
int(* coo_getstripe)(const struct lu_env *env, struct cl_object *obj, struct lov_user_md __user *lum)
Object getstripe method.
int(* coo_fiemap)(const struct lu_env *env, struct cl_object *obj, struct ll_fiemap_info_key *fmkey, struct fiemap *fiemap, size_t *buflen)
Get FIEMAP mapping from the object.
int(* coo_layout_get)(const struct lu_env *env, struct cl_object *obj, struct cl_layout *layout)
Get layout and generation of the object.
loff_t(* coo_maxbytes)(struct cl_object *obj)
Get maximum size of the object.
void(* coo_req_attr_set)(const struct lu_env *env, struct cl_object *obj, struct cl_req_attr *attr)
Set request attributes.
Detailed Description
Operations implemented for each cl object layer.
See also:
vvp_ops, lov_ops, lovsub_ops, osc_ops
Definition at line 298 of file cl_object.h.
Field Documentation
int(* cl_object_operations::coo_attr_get)(const struct lu_env *env, struct cl_object *obj, struct cl_attr *attr)
Fill portion of attr that this layer controls.
This method is called top-to-bottom through all object layers.
Precondition:
cl_object_header::coh_attr_guard of the top-object is locked.
Returns:
0: to continue
+ve: to stop iterating through layers (but 0 is returned from enclosing cl_object_attr_get())
-ve: to signal error
Referenced by cl_object_attr_get().
int(* cl_object_operations::coo_attr_update)(const struct lu_env *env, struct cl_object *obj, const struct cl_attr *attr, unsigned valid)
Update attributes.
valid is a bitmask composed from enum cl_attr_valid, and indicating what attributes are to be set.
Precondition:
cl_object_header::coh_attr_guard of the top-object is locked.
Returns:
the same convention as for cl_object_operations::coo_attr_get() is used.
Referenced by cl_object_attr_update().
int(* cl_object_operations::coo_conf_set)(const struct lu_env *env, struct cl_object *obj, const struct cl_object_conf *conf)
Update object configuration.
Called top-to-bottom to modify object configuration.
XXX error conditions and handling.
Referenced by cl_conf_set().
int(* cl_object_operations::coo_glimpse)(const struct lu_env *env, const struct cl_object *obj, struct ost_lvb *lvb)
Glimpse ast.
Executed when glimpse ast arrives for a lock on this object. Layers are supposed to fill parts of lvb that will be shipped to the glimpse originator as a glimpse result.
See also:
vvp_object_glimpse(), lovsub_object_glimpse(),
osc_object_glimpse()
Referenced by cl_object_glimpse().
int(* cl_object_operations::coo_io_init)(const struct lu_env *env, struct cl_object *obj, struct cl_io *io)
Initialize io state for a given layer.
called top-to-bottom once per io existence to initialize io state. If layer wants to keep some state for this type of io, it has to embed struct cl_io_slice in lu_env::le_ses, and register slice with cl_io_slice_add(). It is guaranteed that all threads participating in this io share the same session.
int(* cl_object_operations::coo_lock_init)(const struct lu_env *env, struct cl_object *obj, struct cl_lock *lock, const struct cl_io *io)
Initialize lock slice for this layer.
Called top-to-bottom through every object layer when a new cl_lock is instantiated. Layer keeping private per-lock data, or requiring its own lock operations vector should allocate these data here, and attach then to the lock by calling cl_lock_slice_add(). Mandatory.
int(* cl_object_operations::coo_page_init)(const struct lu_env *env, struct cl_object *obj, struct cl_page *page, pgoff_t index)
Initialize page slice for this layer.
Called top-to-bottom through every object layer when a new cl_page is instantiated. Layer keeping private per-page data, or requiring its own page operations vector should allocate these data here, and attach then to the page by calling cl_page_slice_add(). vmpage is locked (in the VM sense). Optional.
Return values:
NULL success.
ERR_PTR(errno) failure code.
valid-pointer pointer to already existing referenced page to be used instead of newly created.
int(* cl_object_operations::coo_prune)(const struct lu_env *env, struct cl_object *obj)
Object prune method.
Called when the layout is going to change on this object, therefore each layer has to clean up their cache, mainly pages and locks.
Referenced by cl_object_prune().
The documentation for this struct was generated from the following file:
lustre/include/cl_object.h
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.