Lustre: lu_context_key Struct Reference
lu_context_key Struct Reference
[lu]
Key.
#include <lu_object.h>
Data Fields
__u32 lct_tags
Set of tags for which values of this key are to be instantiated.
void *(* lct_init)(const struct lu_context *ctx, struct lu_context_key *key)
Value constructor.
void(* lct_fini)(const struct lu_context *ctx, struct lu_context_key *key, void *data)
Value destructor.
void(* lct_exit)(const struct lu_context *ctx, struct lu_context_key *key, void *data)
Optional method called on lu_context_exit() for all allocated keys.
int lct_index
Internal implementation detail: index within lu_context::lc_value[] reserved for this key.
atomic_t lct_used
Internal implementation detail: number of values created for this key.
struct module * lct_owner
Internal implementation detail: module for this key.
struct lu_ref lct_reference
References to this key.
Detailed Description
Key.
Represents per-context value slot.
Keys are usually registered when module owning the key is initialized, and de-registered when module is unloaded. Once key is registered, all new contexts with matching tags, will get key value. "Old" contexts, already initialized at the time of key registration, can be forced to get key value by calling lu_context_refill().
Every key value is counted in lu_context_key::lct_used and acquires a reference on an owning module. This means, that all key values have to be destroyed before module can be unloaded. This is usually achieved by stopping threads started by the module, that created contexts in their entry functions. Situation is complicated by the threads shared by multiple modules, like ptlrpcd daemon on a client. To work around this problem, contexts, created in such threads, are `remembered' (see LCT_REMEMBER)---i.e., added into a global list. When module is preparing for unloading it does the following:
marks its keys as `quiescent' (lu_context_tag::LCT_QUIESCENT) preventing new key values from being allocated in the new contexts, and
scans a list of remembered contexts, destroying values of module keys, thus releasing references to the module.
This is done by lu_context_key_quiesce(). If module is re-activated before key has been de-registered, lu_context_key_revive() call clears `quiescent' marker.
lu_context code doesn't provide any internal synchronization for these activities---it's assumed that startup (including threads start-up) and shutdown are serialized by some external means.
See also:
lu_context
Definition at line 1090 of file lu_object.h.
Field Documentation
void(* lu_context_key::lct_exit)(const struct lu_context *ctx, struct lu_context_key *key, void *data)
Optional method called on lu_context_exit() for all allocated keys.
Can be used by debugging code checking that locks are released, etc.
Referenced by lu_context_exit().
void(* lu_context_key::lct_fini)(const struct lu_context *ctx, struct lu_context_key *key, void *data)
Value destructor.
Called when context with previously allocated value of this slot is destroyed. data is a value that was returned by a matching call to lu_context_key::lct_init().
Referenced by lu_context_key_register().
void*(* lu_context_key::lct_init)(const struct lu_context *ctx, struct lu_context_key *key)
Value constructor.
This is called when new value is created for a context. Returns pointer to new value of error pointer.
Referenced by lu_context_key_register().
struct lu_ref lu_context_key::lct_reference [read]
References to this key.
For debugging.
Definition at line 1132 of file lu_object.h.
Referenced by lu_context_key_degister(), and lu_context_key_register().
The documentation for this struct was generated from the following file:
lustre/include/lu_object.h
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.