Lustre: cl_io_operations Struct Reference
cl_io_operations Struct Reference
[cl_io]
Per-layer io operations.
#include <cl_object.h>
Data Fields
struct {
int(* cio_iter_init)(const struct lu_env *env, const struct cl_io_slice *slice)
Prepare io iteration at a given layer.
void(* cio_iter_fini)(const struct lu_env *env, const struct cl_io_slice *slice)
Finalize io iteration.
int(* cio_lock)(const struct lu_env *env, const struct cl_io_slice *slice)
Collect locks for the current iteration of io.
void(* cio_unlock)(const struct lu_env *env, const struct cl_io_slice *slice)
Finalize unlocking.
int(* cio_start)(const struct lu_env *env, const struct cl_io_slice *slice)
Start io iteration.
void(* cio_end)(const struct lu_env *env, const struct cl_io_slice *slice)
Called top-to-bottom at the end of io loop.
void(* cio_advance)(const struct lu_env *env, const struct cl_io_slice *slice, size_t nob)
Called bottom-to-top to notify layers that read/write IO iteration finished, with nob bytes transferred.
void(* cio_fini)(const struct lu_env *env, const struct cl_io_slice *slice)
Called once per io, bottom-to-top to release io resources.
} op [CIT_OP_NR]
Vector of io state transition methods for every io type.
int(* cio_submit)(const struct lu_env *env, const struct cl_io_slice *slice, enum cl_req_type crt, struct cl_2queue *queue)
Submit pages from queue->c2_qin for IO, and move successfully submitted pages into queue->c2_qout.
int(* cio_commit_async)(const struct lu_env *env, const struct cl_io_slice *slice, struct cl_page_list *queue, int from, int to, cl_commit_cbt cb)
Queue async page for write.
int(* cio_read_ahead)(const struct lu_env *env, const struct cl_io_slice *slice, pgoff_t start, struct cl_read_ahead *ra)
Decide maximum read ahead extent.
int(* cio_print)(const struct lu_env *env, void *cookie, lu_printer_t p, const struct cl_io_slice *slice)
Optional debugging helper.
Detailed Description
Per-layer io operations.
See also:
vvp_io_ops, lov_io_ops, lovsub_io_ops, osc_io_ops
Definition at line 1481 of file cl_object.h.
Field Documentation
int(* cl_io_operations::cio_commit_async)(const struct lu_env *env, const struct cl_io_slice *slice, struct cl_page_list *queue, int from, int to, cl_commit_cbt cb)
Queue async page for write.
The difference between cio_submit and cio_queue is that cio_submit is for urgent request.
Referenced by cl_io_commit_async().
void(* cl_io_operations::cio_end)(const struct lu_env *env, const struct cl_io_slice *slice)
Called top-to-bottom at the end of io loop.
Here layer might wait for an unfinished asynchronous io.
Referenced by cl_io_end().
void(* cl_io_operations::cio_iter_fini)(const struct lu_env *env, const struct cl_io_slice *slice)
Finalize io iteration.
Called bottom-to-top at the end of each iteration of "io loop". Here layers can decide whether IO has to be continued.
See also:
cl_io_operations::cio_iter_init()
Referenced by cl_io_iter_fini().
int(* cl_io_operations::cio_iter_init)(const struct lu_env *env, const struct cl_io_slice *slice)
Prepare io iteration at a given layer.
Called top-to-bottom at the beginning of each iteration of "io loop" (if it makes sense for this type of io). Here layer selects what work it will do during this iteration.
See also:
cl_io_operations::cio_iter_fini()
Referenced by cl_io_iter_init().
int(* cl_io_operations::cio_lock)(const struct lu_env *env, const struct cl_io_slice *slice)
Collect locks for the current iteration of io.
Called top-to-bottom to collect all locks necessary for this iteration. This methods shouldn't actually enqueue anything, instead it should post a lock through cl_io_lock_add(). Once all locks are collected, they are sorted and enqueued in the proper order.
Referenced by cl_io_lock().
int(* cl_io_operations::cio_print)(const struct lu_env *env, void *cookie, lu_printer_t p, const struct cl_io_slice *slice)
Optional debugging helper.
Print given io slice.
int(* cl_io_operations::cio_read_ahead)(const struct lu_env *env, const struct cl_io_slice *slice, pgoff_t start, struct cl_read_ahead *ra)
Decide maximum read ahead extent.
Precondition:
io->ci_type == CIT_READ
Referenced by cl_io_read_ahead().
int(* cl_io_operations::cio_start)(const struct lu_env *env, const struct cl_io_slice *slice)
Start io iteration.
Once all locks are acquired, called top-to-bottom to commence actual IO. In the current implementation, top-level vvp_io_{read,write}_start() does all the work synchronously by calling generic_file_*(), so other layers are called when everything is done.
Referenced by cl_io_start().
int(* cl_io_operations::cio_submit)(const struct lu_env *env, const struct cl_io_slice *slice, enum cl_req_type crt, struct cl_2queue *queue)
Submit pages from queue->c2_qin for IO, and move successfully submitted pages into queue->c2_qout.
Return non-zero if failed to submit even the single page. If submission failed after some pages were moved into queue->c2_qout, completion callback with non-zero ioret is executed on them.
Referenced by cl_io_submit_rw().
void(* cl_io_operations::cio_unlock)(const struct lu_env *env, const struct cl_io_slice *slice)
Finalize unlocking.
Called bottom-to-top to finish layer specific unlocking functionality, after generic code released all locks acquired by cl_io_operations::cio_lock().
Referenced by cl_io_unlock().
struct { ... } cl_io_operations::op[CIT_OP_NR]
Vector of io state transition methods for every io type.
See also:
cl_page_operations::io
Referenced by cl_io_end(), cl_io_fini(), cl_io_iter_fini(), cl_io_iter_init(), cl_io_lock(), cl_io_rw_advance(), cl_io_start(), and cl_io_unlock().
The documentation for this struct was generated from the following file:
lustre/include/cl_object.h
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.